### ISSUE TITLE
Toolbar has no option to display items as text

### ISSUE THREAD

**Issue by billkendrick** [bit-team/backintime#1105]
The toolbar in Back In Time shows icons only. While tooltips appear after hovering on them, there appears to be no option to display the tools with text (or as text-only).

Compare to Kate text editor or Okular image viewer. Their toolbars provide options (available via right-click menu) to display entries as: Icons only, Text only, Text Alongside Icons, and Text Under icons.

Thanks for your consideration!

Version: 1.2.1
Source: Kubuntu 20.04 repositories

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Why do you need text there?

I would assume this FeatureRequest is out of project ressources here or you could say it is not important enough compared to other Issues and open PRs. Sorry.

Maybe you can provide a PR?

**Comment by billkendrick** [comment]
I would call this "nice-to-have," since the hover option is probably a suitable alternative.  I'm used to most other Qt & KDE apps having text labels on buttons, as a configurable option, and it's helpful for new users to understand what a button does before pressing it. :smile: 

I assumed (sorry!) that it would be trivial, though without having any personal experience developing Qt apps myself.  Feel free to close if you deem this "won't-fix".  Thanks!

**Comment by emtiu** [comment]
This functionality existed in the past (verified for backintime 1.0.36 on KDE4 in an old VM), but my current best guess is that it has disappeared in migration to Qt5 (see also #167).

I also think it would be nice to have it back, if only to conform better to KDE standards.

**Comment by s4moore** [comment]
Hello, I would to work on this issue.

I have completed one small task already for BIT and found that task through a search for "Good First Issue".

I have some experience in C, Python, HTML / CSS, Javascript, and a little bit of React, and am trying to develop my skills.

Thanks,
Sam

**Comment by buhtz** [comment]
Hello Samuel,
thank you for your efforts. Let me know if I can be of assistance. Don't hesitate to ask.
Regards,
Christian

**Comment by s4moore** [comment]
Hi Christian,

Many thanks, is it best to message you here?

**Comment by buhtz** [comment]
Yes. Here or in a PR if you have opened one.

**Comment by daviewales** [comment]
I'm getting this error since commit 9f7891e8c5889209db5cef14bfa72a53e736c3dd:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 2459, in <module>
    mainWindow = MainWindow(cfg, appInstance, qapp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/app.py", line 135, in __init__
    self._create_main_toolbar()
  File "/usr/share/backintime/qt/app.py", line 796, in _create_main_toolbar
    Qt.ToolButtonStyle(StateData().toolbar_button_style))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StateData' object has no attribute 'toolbar_button_style'
```

**Comment by buhtz** [comment]
Mhm... it should be there.

https://github.com/bit-team/backintime/blob/c89805bbf84b2bb5e9bafc3deaea4566ef8c24b7/qt/statedata.py#L361-L372

Maybe you somehow mixed some versions of the code? Are you on the latest dev?

**Comment by daviewales** [comment]
Sorry, I must have mixed something up. It's working now.
