### ISSUE TITLE
Module exists and cannot be found

### ISSUE THREAD

**Issue by jim-moe** [bit-team/backintime#1113]
python 3.6.10
opensuse tumbleweed
linux 5.8.4

BackInTime 1.2.1 has recently been having difficulties functioning. See below.

Module PyQt5 is most definitely installed; YaST shows it installed and I found the folder in /usr/pib64/python3. Apparently there is more to getting modules loaded than there used to be.

Any suggestions for repairing this?

(Also, I am not familiar with Python.)

----[ error message (verbose option) ]----
```
Traceback (most recent call last):
  File "/home/jmoe/diy/backintime-master/qt/app.py", line 35, in <module>
    import qttools
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jmoe/diy/backintime-master/qt/qttools.py", line 21, in <module>
    from PyQt5.QtGui import (QFont, QColor, QKeySequence)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyQt5'
```
----[ end ]----

----[ the 1st code lines causing the above ]----
```
qttools.py:
  import os
  import sys
  import gettext
  from PyQt5.QtGui import (QFont, QColor, QKeySequence) <<<-- line 21
  ...

app.py:
  import os
  import sys

  if not os.getenv('DISPLAY', ''):
    os.putenv('DISPLAY', ':0.0')

  import datetime
  import gettext
  import re
  import subprocess
  import shutil
  import signal
  from contextlib import contextmanager
  from tempfile import TemporaryDirectory

  import qttools    <<<--- line 35
  qttools.registerBackintimePath('common')
  ...

----[ end ]----

**Comment by jim-moe** [comment]
SOLVED

My python installation was buggered. BIT runs okay again.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks for reporting back.
Please close the Issue.
