### ISSUE TITLE
Blocking error not shown in GUI

### ISSUE THREAD

**Issue by mat-m** [bit-team/backintime#1121]
Hello

I had an issue where snapshots were not taken. Using the GUI, I had no information and no log was generated.

I decided to run in CLI and got:
```
DEBUG: [common/snapshots.py:1751 Snapshots.flockExclusive] Set flock /tmp/backintime.lock
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 739, in backup
    ret = takeSnapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
    ret = snapshots.Snapshots(cfg).backup(force)
  File "/usr/share/backintime/common/snapshots.py", line 633, in backup
    self.flockExclusive()
  File "/usr/share/backintime/common/snapshots.py", line 1752, in flockExclusive
    self.flock = open(self.GLOBAL_FLOCK, 'w')
PermissionError: [Errno 13] Permission denied: '/tmp/backintime.lock'
 ```

Is there a way to push these errors in the GUI, or at least ask to run the CLI to check ?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Maybe related to #1122 

How can you reproduce this behaviour/error?

**Comment by mat-m** [comment]
On the same host, I defined two users lauching a different backup at the same time. In my case, it was `@reboot`, but I think it would trigger it also when setting the same custom hours, or even with a simultaneous command line

**Comment by buhtzz** [comment]
@mat-m There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Maybe a duplicate or a neighbor problem.

Tag: Bug, Medium, Scheduling, Feedback

**Comment by mat-m** [comment]
@buhtzz Glad a new team is coming ! Thanks so much for this !
I worked it around by using different times. But the lock name is too generic to handle mutli-users  or multi-targets. I actually don't know what you want to lock. In my opinion, the lock should be on the target dir

**Comment by mat-m** [comment]
Can be considered as dup of #1122, where I will repost my last message.

**Comment by mat-m** [comment]
Ah, no.  My point here is that the error was not pushed to the GUI. I had to run BIT in console to see it and understand why it blocked trough the GUI

**Comment by emtiu** [comment]
Related Issues or possible duplicates:
* #84 
* #907
