### ISSUE TITLE
AttributeError: 'TempPasswordThread' object has no attribute 'isAlive' (Python 3.9)

### ISSUE THREAD

**Issue by FMeinicke** [bit-team/backintime#1134]
Hi,  
I've been using BackInTime for quite some time now and I recently discovered that my automatically scheduled backups weren't running any more. So, I checked my config but couldn't find anything. I noticed, however, that the field for the SSH private key was empty. So I thought I would just re-enter my password and hope for the best (as a side note, I have the 'Save password to keyring' option enabled). 

Unfortunately, when I then clicked on 'OK' to save the config, BIT just crashed. `journalctl` gave the following:

<details>
<summary>Click to expand log</summary>

```log
Feb 19 08:51:58 manjaro python[736031]: Traceback (most recent call last):
                                          File "/usr/share/backintime/qt/settingsdialog.py", line 1754, in accept
                                            if self.validate():
                                          File "/usr/share/backintime/qt/settingsdialog.py", line 1498, in validate
                                            if not self.saveProfile():
                                          File "/usr/share/backintime/qt/settingsdialog.py", line 1359, in saveProfile
                                            mnt.preMountCheck(mode = mode, first_run = True, **mount_kwargs)
                                          File "/usr/share/backintime/common/mount.py", line 218, in preMountCheck
                                            return backend.preMountCheck(first_run)
                                          File "/usr/share/backintime/common/sshtools.py", line 186, in preMountCheck
                                            self.unlockSshAgent(force = True)
                                          File "/usr/share/backintime/common/sshtools.py", line 309, in unlockSshAgent
                                            thread.stop()
                                          File "/usr/share/backintime/common/password_ipc.py", line 135, in stop
                                            if self.isAlive():
                                        AttributeError: 'TempPasswordThread' object has no attribute 'isAlive'
Feb 19 08:51:58 manjaro audit[736031]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 pid=736031 comm="python" exe="/usr/bin/python3.9" sig=6 res=1
Feb 19 08:51:58 manjaro audit: BPF prog-id=33 op=LOAD
Feb 19 08:51:58 manjaro audit: BPF prog-id=34 op=LOAD
Feb 19 08:51:58 manjaro systemd[1]: Started Process Core Dump (PID 761658/UID 0).
Feb 19 08:51:58 manjaro audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@8-761658-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 19 08:51:59 manjaro systemd-coredump[761668]: Process 736031 (python) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 736031:
                                                  #0  0x00007f3ec927def5 raise (libc.so.6 + 0x3cef5)
                                                  #1  0x00007f3ec9267862 abort (libc.so.6 + 0x26862)
                                                  #2  0x00007f3ec797e9ac _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x909ac)
                                                  #3  0x00007f3ec4a0a043 n/a (QtCore.abi3.so + 0xa9043)
                                                  #4  0x00007f3ec4b72b26 n/a (QtCore.abi3.so + 0x211b26)
                                                  #5  0x00007f3ec4b736a0 n/a (QtCore.abi3.so + 0x2126a0)
                                                  #6  0x00007f3ec7bdab12 n/a (libQt5Core.so.5 + 0x2ecb12)
                                                  #7  0x00007f3ec3f82489 n/a (libQt5Widgets.so.5 + 0x2f2489)
                                                  #8  0x00007f3ec7bdae10 n/a (libQt5Core.so.5 + 0x2ece10)
                                                  #9  0x00007f3ec3edbd53 _ZN15QAbstractButton7clickedEb (libQt5Widgets.so.5 + 0x24bd53)
                                                  #10 0x00007f3ec3edc6dc n/a (libQt5Widgets.so.5 + 0x24c6dc)
                                                  #11 0x00007f3ec3ede083 n/a (libQt5Widgets.so.5 + 0x24e083)
                                                  #12 0x00007f3ec3ede263 _ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5 + 0x24e263)
                                                  #13 0x00007f3ec3e2bb0e _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x19bb0e)
                                                  #14 0x00007f3ec3dea752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
                                                  #15 0x00007f3ec3df187b _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x16187b)
                                                  #16 0x00007f3ec46d2ecf n/a (QtWidgets.abi3.so + 0x37decf)
                                                  #17 0x00007f3ec7ba3a7a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b5a7a)
                                                  #18 0x00007f3ec3df087e _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb (libQt5Widgets.so.5 + 0x16087e)
                                                  #19 0x00007f3ec3e44249 n/a (libQt5Widgets.so.5 + 0x1b4249)
                                                  #20 0x00007f3ec3e4763f n/a (libQt5Widgets.so.5 + 0x1b763f)
                                                  #21 0x00007f3ec3dea752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
                                                  #22 0x00007f3ec46d2ecf n/a (QtWidgets.abi3.so + 0x37decf)
                                                  #23 0x00007f3ec7ba3a7a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b5a7a)
                                                  #24 0x00007f3ec7f7d594 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5 + 0x13a594)
                                                  #25 0x00007f3ec7f52bb5 _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5 + 0x10fbb5)
                                                  #26 0x00007f3ec327816c n/a (libQt5XcbQpa.so.5 + 0x5f16c)
                                                  #27 0x00007f3ec6d43b74 g_main_context_dispatch (libglib-2.0.so.0 + 0x52b74)
                                                  #28 0x00007f3ec6d97c31 n/a (libglib-2.0.so.0 + 0xa6c31)
                                                  #29 0x00007f3ec6d423a1 g_main_context_iteration (libglib-2.0.so.0 + 0x513a1)
                                                  #30 0x00007f3ec7bfc6e1 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30e6e1)
                                                  #31 0x00007f3ec7ba23fc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b43fc)
                                                  #32 0x00007f3ec7baa894 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2bc894)
                                                  #33 0x00007f3ec46d1baf n/a (QtWidgets.abi3.so + 0x37cbaf)
                                                  #34 0x00007f3ec955a2a2 n/a (libpython3.9.so.1.0 + 0x14c2a2)
                                                  #35 0x00007f3ec954071d _PyObject_MakeTpCall (libpython3.9.so.1.0 + 0x13271d)
                                                  #36 0x00007f3ec953c462 _PyEval_EvalFrameDefault (libpython3.9.so.1.0 + 0x12e462)
                                                  #37 0x00007f3ec953628d n/a (libpython3.9.so.1.0 + 0x12828d)
                                                  #38 0x00007f3ec9535c51 _PyEval_EvalCodeWithName (libpython3.9.so.1.0 + 0x127c51)
                                                  #39 0x00007f3ec95f7b13 PyEval_EvalCode (libpython3.9.so.1.0 + 0x1e9b13)
                                                  #40 0x00007f3ec9607b9d n/a (libpython3.9.so.1.0 + 0x1f9b9d)
                                                  #41 0x00007f3ec960396b n/a (libpython3.9.so.1.0 + 0x1f596b)
                                                  #42 0x00007f3ec94a57c4 PyRun_FileExFlags (libpython3.9.so.1.0 + 0x977c4)
                                                  #43 0x00007f3ec94a514c PyRun_SimpleFileExFlags (libpython3.9.so.1.0 + 0x9714c)
                                                  #44 0x00007f3ec9619c99 Py_RunMain (libpython3.9.so.1.0 + 0x20bc99)
                                                  #45 0x00007f3ec95eaba9 Py_BytesMain (libpython3.9.so.1.0 + 0x1dcba9)
                                                  #46 0x00007f3ec9268b25 __libc_start_main (libc.so.6 + 0x27b25)
                                                  #47 0x0000560ede0f704e _start (python3.9 + 0x104e)
                                                  
                                                  Stack trace of thread 736168:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3ec79c20d4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd40d4)
                                                  #3  0x00007f3ec40177b3 n/a (libQt5Widgets.so.5 + 0x3877b3)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736601:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736597:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736617:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736135:
                                                  #0  0x00007f3ec933547f __poll (libc.so.6 + 0xf447f)
                                                  #1  0x00007f3ec6d97bbf n/a (libglib-2.0.so.0 + 0xa6bbf)
                                                  #2  0x00007f3ec6d423a1 g_main_context_iteration (libglib-2.0.so.0 + 0x513a1)
                                                  #3  0x00007f3ec7bfc6e1 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30e6e1)
                                                  #4  0x00007f3ec7ba23fc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b43fc)
                                                  #5  0x00007f3ec79bad22 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccd22)
                                                  #6  0x00007f3ec315f098 n/a (libQt5DBus.so.5 + 0x17098)
                                                  #7  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #8  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #9  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736602:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736598:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736603:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736599:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736604:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736600:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736605:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736606:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736607:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736611:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736612:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736613:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736614:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736616:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736618:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736630:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                                                  #2  0x00007f3ec79c2058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                                                  #3  0x00007f3ec79bf504 n/a (libQt5Core.so.5 + 0xd1504)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736631:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                                                  #2  0x00007f3ec79c2058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                                                  #3  0x00007f3ec79bf504 n/a (libQt5Core.so.5 + 0xd1504)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736632:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                                                  #2  0x00007f3ec79c2058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                                                  #3  0x00007f3ec79bf504 n/a (libQt5Core.so.5 + 0xd1504)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736633:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                                                  #2  0x00007f3ec79c2058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                                                  #3  0x00007f3ec79bf504 n/a (libQt5Core.so.5 + 0xd1504)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 752461:
                                                  #0  0x00007f3ec9337cf3 pselect (libc.so.6 + 0xf6cf3)
                                                  #1  0x00007f3ec069c524 n/a (libusbmuxd-2.0.so.6 + 0x2524)
                                                  #2  0x00007f3ec069d8a9 n/a (libusbmuxd-2.0.so.6 + 0x38a9)
                                                  #3  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #4  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736610:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736615:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736115:
                                                  #0  0x00007f3ec933547f __poll (libc.so.6 + 0xf447f)
                                                  #1  0x00007f3ec4c8063b n/a (libxcb.so.1 + 0xc63b)
                                                  #2  0x00007f3ec4c8237b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                                                  #3  0x00007f3ec3277131 n/a (libQt5XcbQpa.so.5 + 0x5e131)
                                                  #4  0x00007f3ec79bbf0f n/a (libQt5Core.so.5 + 0xcdf0f)
                                                  #5  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #6  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736608:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
                                                  
                                                  Stack trace of thread 736609:
                                                  #0  0x00007f3ec92359ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                                  #1  0x00007f3ec922f260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                                  #2  0x00007f3eaad1eb3c n/a (radeonsi_dri.so + 0x4edb3c)
                                                  #3  0x00007f3eaad1d308 n/a (radeonsi_dri.so + 0x4ec308)
                                                  #4  0x00007f3ec9229299 start_thread (libpthread.so.0 + 0x9299)
                                                  #5  0x00007f3ec9340153 __clone (libc.so.6 + 0xff153)
Feb 19 08:51:59 manjaro systemd[1]: systemd-coredump@8-761658-0.service: Succeeded.
Feb 19 08:51:59 manjaro audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@8-761658-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 19 08:51:59 manjaro systemd[1479]: app-backintime\x2dqt-6eb2e80446dc44a1a39641a461da9c69.scope: Succeeded.
```

</details>

**System Info:**  
OS: Manjaro 20.2.1  
Kernel: 5.10.15-1-MANJARO  
DE: Plasma   
WM: KWin  
backintime: 1.2.1 (installed from the community repo) 

I hope this helps to find the cause of the bug. If you need more info I'm happy to help.

Thanks in advance!

**Comment by hannes101** [comment]
Can confirm that this fixes the crash. Incorporated in the downstream fedora package.
