### ISSUE TITLE
Probliem with Invalid Characters in backintime-qt-root

### ISSUE THREAD

**Issue by urilabob** [bit-team/backintime#1190]
When backintime-qt-root goes to open the sudo password interface, it instead gets an error 'termios.error: (25, 'Inappropriate ioctl for device')". This stems from an attempt to handle a keycode above 255 (guessing this means that something is set to ascii where it needs to be unicode). I'll be happy to chase any further documentation needed, but don't know python at all, so tracing the actual problem is probably beyond me. It's worth noting that the problem arises before anything appears on screen (i.e. I never get to see the authentication window), so it's not a problem with typed input. However I am trying to re-use backintime after a previous attempt to set up an encrypted backup failed (long ago), so it could somehow be related to that. I have been unable to completely reset backintime despite reinstalling with dnf, so maybe there are some corrupted files somewhere that need cleaning up. But the actual error looks more like it is trying to open a sudo password window but failing to do so.

System: Linux version 5.14.14-200.fc34.x86_64
Backintime version: backintime 1.3.1

Relevant portions of journal (note: I will report the uncaught exception separately)

Oct 30 09:21:59 bobslin python3[7393]: detected unhandled Python exception in '/usr/share/backintime/qt/app.py'
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: Traceback (most recent call last):
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 69, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     old = termios.tcgetattr(fd)     # a copy to save
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: termios.error: (25, 'Inappropriate ioctl for device')
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: During handling of the above exception, another exception occurred:
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: Traceback (most recent call last):
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/qt/app.py", line 1607, in <module>
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     mainWindow = MainWindow(cfg, appInstance, qapp)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/qt/app.py", line 485, in __init__
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     hash_id = mnt.mount()
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/common/mount.py", line 134, in mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     return backend.mount(check = check)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/common/mount.py", line 420, in mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     self._mount()
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/common/encfstools.py", line 63, in _mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     self.password = self.config.password(self.parent, self.profile_id, self.mode)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/common/config.py", line 696, in password
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     return self.pw.password(parent, profile_id, mode, pw_id, only_from_keyring)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/share/backintime/common/password.py", line 200, in password
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     password = getpass.getpass(prompt)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 91, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     passwd = fallback_getpass(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 126, in fallback_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     return _raw_input(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 148, in _raw_input
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     raise EOFError
Oct 30 09:21:59 bobslin backintime-Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     password = getpass.getpass(prompt)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 91, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     passwd = fallback_getpass(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 126, in fallback_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     return _raw_input(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:   File "/usr/lib64/python3.9/getpass.py", line 148, in _raw_input
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]:     raise EOFError
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: EOFError
Oct 30 09:22:00 bobslin abrt-server[7409]: Deleting problem directory Python3-2021-10-30-09:21:59-7393 (dup of Python3-2021-10-30-09:09:02-5751)
Oct 30 09:22:00 bobslin abrt-notification[7416]: [🡕] Process 5751 (app.py) of user 0 encountered an uncaught termios.error exception
Oct 30 09:22:00 bobslin gnome-shell[7419]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Oct 30 09:22:00 bobslin gnome-shell[7419]: > Warning:          Unsupported maximum keycode 708, clipping.
Oct 30 09:22:00 bobslin gnome-shell[7419]: >                   X11 cannot support keycodes above 255.
Oct 30 09:22:00 bobslin gnome-shell[7419]: Errors from xkbcomp are not fatal to the X server
qt-root.desktop[7393]: EOFError
Oct 30 09:22:00 bobslin abrt-server[7409]: Deleting problem directory Python3-2021-10-30-09:21:59-7393 (dup of Python3-2021-10-30-09:09:02-5751)
Oct 30 09:22:00 bobslin abrt-notification[7416]: [🡕] Process 5751 (app.py) of user 0 encountered an uncaught termios.error exception
Oct 30 09:22:00 bobslin gnome-shell[7419]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Oct 30 09:22:00 bobslin gnome-shell[7419]: > Warning:          Unsupported maximum keycode 708, clipping.
Oct 30 09:22:00 bobslin gnome-shell[7419]: >                   X11 cannot support keycodes above 255.
Oct 30 09:22:00 bobslin gnome-shell[7419]: Errors from xkbcomp are not fatal to the X server

**Comment by urilabob** [comment]
I'm sorry, my description of the process was wrong. Running backintime-qt-root does successfully open the user password window, the crash appears after I have entered the password (note: the password does not contain any non-ASCII characters).

**Comment by urilabob** [comment]
OK, a bit more information. Completely removing /root/.local/share/backintime and reinstalling backintime has fixed the problem (note: previous reinstalls did inot fix the problem). So it is very likely that the problem was not a result of terminal handling at all, but a misinterpreted exception as a result of something corrupted in /root/.local/share/backintime. Unfortunately fixing the problem means that I can't help further with debugging it. However fixing the missing eception handlers might help diagnising the bug if it ever occurs again.
