### ISSUE TITLE
Permissions not restored

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#120]
I made a backup of my system (including /home) as root.
I restored  /home , all files has been copied but BIT hangs when restoring permissions.
All file in /home have the wrong permissions (root).

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-04-29T17:15:01Z
 * owner: upl97o0
 * the launchpad url was https://bugs.launchpad.net/bugs/1174424

**Comment by Germar** [comment]
(by germar)
Which version do you  use?

If this was with 1.0.22 in combination with the new 'Full rsync mode' than this bug is already fixed for the next version. For now you can use the attached patch:
sudo patch /usr/share/backintime/common/snapshots.py  snapshots.diff

If you used an other version please run backintime-gnome (or backintime-kde4) from Terminal, restore again and post the output from Terminal in here.

Regards,
Germar

**Comment by Germar** [comment]
(by upl97o0)
Hi,

I'm using version 1.0.10

I tried to restor only one file in console with "sudo backintime-gnome"

This is my output:

*****
Back In Time
Version: 1.0.10

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Where: 
INFO: Restore: /home/ucd1701/NAMES.DIC to: 
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o -R -v --chmod=ugo=rwX --backup --suffix=.backup.20130430 "/media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193/backup/./home/ucd1701/NAMES.DIC" /" returns 0
INFO: Restore permissions
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 906, in on_restore_this
    gnometools.restore(self, self.snapshot_id, self.store_folder_view.get_value( iter, 1 ) )
  File "/usr/share/backintime/gnome/gnometools.py", line 75, in restore
    restoredialog.restore(parent, snapshot_id, path, where )
  File "/usr/share/backintime/gnome/restoredialog.py", line 40, in restore
    RestoreDialog(parent, snapshot_id, what, where).run()
  File "/usr/share/backintime/gnome/restoredialog.py", line 95, in run
    self.snapshots.restore( self.snapshot_id, self.what, self.callback, self.where )
  File "/usr/share/backintime/common/snapshots.py", line 496, in restore
    file_info_dict = self.load_fileinfo_dict( snapshot_id, info_file.get_int_value( 'snapshot_version' ) )
  File "/usr/share/backintime/common/snapshots.py", line 320, in load_fileinfo_dict
    return file_info_dict
NameError: global name 'file_info_dict' is not defined

****


Chris

**Comment by Germar** [comment]
(by upl97o0)
Sorry, I think I tried to restore a local file and not form my backup:


This ist the right output:


Back In Time
Version: 1.0.10

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Where: 
INFO: Restore: /home/ucd1701/NAMES.DIC to: 
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o -R -v --chmod=ugo=rwX --backup --suffix=.backup.20130430 "/media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193/backup/./home/ucd1701/NAMES.DIC" /" returns 0
INFO: Restore permissions
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 906, in on_restore_this
    gnometools.restore(self, self.snapshot_id, self.store_folder_view.get_value( iter, 1 ) )
  File "/usr/share/backintime/gnome/gnometools.py", line 75, in restore
    restoredialog.restore(parent, snapshot_id, path, where )
  File "/usr/share/backintime/gnome/restoredialog.py", line 40, in restore
    RestoreDialog(parent, snapshot_id, what, where).run()
  File "/usr/share/backintime/gnome/restoredialog.py", line 95, in run
    self.snapshots.restore( self.snapshot_id, self.what, self.callback, self.where )
  File "/usr/share/backintime/common/snapshots.py", line 496, in restore
    file_info_dict = self.load_fileinfo_dict( snapshot_id, info_file.get_int_value( 'snapshot_version' ) )
  File "/usr/share/backintime/common/snapshots.py", line 320, in load_fileinfo_dict
    return file_info_dict
NameError: global name 'file_info_dict' is not defined

**Comment by Germar** [comment]
(by germar)
The NameError Exception is caused by a wrong variable name. You can fix that with this patch.
But with that fixed BIT will still not restore the permissions. Did you recently update from an older version (<0.9.26)?
Please post the output of:
cd /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193/
ls -la
cat info

Does this happen with other snapshots, too? Maybe BIT failed for what ever reason on this snapshot.

Regards,
Germar

**Comment by Germar** [comment]
(by upl97o0)
Hi Germar,

I did't uptate from an older version. I installed 1.0.10 new and the first time.

this is the output:

*****
ucd1701@ucd1701-ThinkPad ~ $ cd /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193/
ucd1701@ucd1701-ThinkPad /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193 $ ls -la
insgesamt 12
dr-xr-xr-x  3 root root 4096 Apr 29 09:11 .
drwxr-xr-x  5 root root 4096 Apr 29 09:11 ..
dr-xr-xr-x 20 root root 4096 Mär 14 14:41 backup
-r--r--r--  1 root root    0 Apr 29 09:11 config
-r--r--r--  1 root root    0 Apr 29 09:11 failed
-r--r--r--  1 root root    0 Apr 29 09:11 fileinfo.bz2
-r--r--r--  1 root root    0 Apr 29 09:11 info
-r--r--r--  1 root root    0 Apr 29 09:11 takesnapshot.log.bz2
ucd1701@ucd1701-ThinkPad /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193 $ cat info
ucd1701@ucd1701-ThinkPad /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193 $ cd /media/ucd1701/Sicherung/backintime/ucd1701-ThinkPad/root/1/20130429-090353-193/
******

An older snapshot seem working fine

Restore permissions:
chmod /home/ucd1701/hydra.restore 100644
chown /home/ucd1701/hydra.restore 1000 : 1000

Regards,
 Chris

**Comment by Germar** [comment]
(by germar)
Hi Chris,

This snapshot failed! Backintime shows a bold 'WITH ERRORS!' beside that snapshot in the snapshot tree, doesn't it? The file that stores the permission 'fileinfo.bz2' is empty. The log is empty too. So I can't say why it failed.

Can you restore from an older snapshot or do you urgently need this one?

Regards,
Germar

**Comment by Germar** [comment]
(by upl97o0)
Hi Germar

I think you can close this bug report.

I could restore an older snapshot and a new one I made today.
All permissions were ok.

I think somthing went wrong with this certain snapshot.

Should I install the patch anyway?
Thanks for your help.

Regards,
 Chris

**Comment by Germar** [comment]
(by upl97o0)
'WITH ERRORS!'  is an error in all of my snapshots and concerns a permission problme in /run/user/ dirctory which seems to me not really important...

[E] Error: rsync: readlink_stat("/run/user/ucd1701/gvfs") failed: Permission denied (13)

**Comment by Germar** [comment]
(by germar)
Hi Chris,

That's right. /run doesn't need to be backed up and causes lots of problems. It is a tmpfs mount that will be created by initrd or systemd on boot. So you can exclude /run.

The second patch only fixes the NameError exception that should normally never occur and the first is just for 1.0.22. So you don't need to install those.

Regards,
Germar
