### ISSUE TITLE
GUI and command line broken since 1.3.1-4

### ISSUE THREAD

**Issue by sspade1** [bit-team/backintime#1206]
`$ backintime-qt
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 35, in <module>
    import qttools
  File "/usr/share/backintime/qt/qttools.py", line 47, in <module>
    import snapshots
  File "/usr/share/backintime/common/snapshots.py", line 34, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 1805, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'`

Same error with running:
`$/usr/bin/backintime --backup-job`

I tried to downgrade in Artix Linux, but no previous version is available.
Since Python has been updated to 3.10.1-1 on the same date (13/12), I downgraded down to 5 previous versions, but I get either same or another error when running backintime-qt.
I like BIT very much, but it is important that a backup program is reliable through updates. We need more reliability than new functionalities.

Regards

**Comment by sspade1** [comment]
Simple fix about this problem:
Uninstall then install

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
@emtiu please close.
