### ISSUE TITLE
after finishing and quitting, enfs and python still running

### ISSUE THREAD

**Issue by wolftune** [bit-team/backintime#1209]
On Ubuntu based system w/ BIT 1.3.1

I can run backups, get to done, quit the GUI, and then two backintime-related entries persist in System Activity: encfs (user owned) and a Python process (root owned).

**Comment by wolftune** [comment]
Update, I ran `backintime-qt` in command line, same error. When I choose "quite" in the GUI, nothing showed in the command line. When I did ctrl-C, I got a traceback

```
INFO: Lock
INFO: Take a new snapshot. Profile: 2 main2
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock

^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

And even then, a python3 activity remained listed under root within System Activity, and I had to `sudo kill -9` to stop it

**Comment by buhtzz** [comment]
Tag: Qt

**Comment by emtiu** [comment]
Hi @wolftune, if you're still running backintime and still encountering this problem: Could you post the console output again, this time running `backintime-qt --debug`?

**Comment by wolftune** [comment]
```
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /home/aaron/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/aaron/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile, 2=main2, 3=offsite-backup
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1607, in <module>
    mainWindow = MainWindow(cfg, appInstance, qapp)
  File "/usr/share/backintime/qt/app.py", line 485, in __init__
    hash_id = mnt.mount()
  File "/usr/share/backintime/common/mount.py", line 134, in mount
    return backend.mount(check = check)
  File "/usr/share/backintime/common/mount.py", line 408, in mount
    self.createMountStructure()
  File "/usr/share/backintime/common/mount.py", line 654, in createMountStructure
    tools.mkdir(self.currentMountpoint, 0o700, False)
  File "/usr/share/backintime/common/tools.py", line 312, in mkdir
    os.mkdir(path, mode)
FileExistsError: [Errno 17] File exists: '/home/aaron/.local/share/backintime/mnt/A588EEE/mountpoint'
```

This might have something to do with something weird with my mountpoint setup, dunno. Okay, yeah, I see the ghost thing in Dolphin still, something weird there. I'll get that cleared and then revisit this after logging out and in.

I do recall something before where the problem was that a status of something would make BiT crash, and when I added some ignore (which I didn't want backed up anyway, something that was like BiT's own config or temp area) the crashing ended. Then, it was less of a problem for BiT process to linger because having it linger didn't block me from opening it again (unlike the current status).

**Comment by wolftune** [comment]
Okay, I tried after restarting and with a drive that successfully and fully unmounted afterwards.

I still have backintime running after quitting the GUI. Two processes showed "backintime-qt" and "python3" from /usr/bin/python3 -Es /usr/share/backintime/qt/serviceHelper.py (double instances, one user one root)

If I force the user instance of python3 process to close, backintime-qt stops too. Not so the other way around.

No errors in the debugging (the only error is in the drive missing)

```
DEBUG: [common/backintime.py:670 getConfig] config file: /home/aaron/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/aaron/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile, 2=main2, 3=offsite-backup
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/mount.py:680 EncFS_mount.mountProcessLockAcquire] Acquire mountprocess lock /home/aaron/.local/share/backintime/mnt/17394.lock
DEBUG: [common/mount.py:574 EncFS_mount.checkFuse] Check fuse
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/encfstools.py:64 EncFS_mount._mount] Provide password through temp FIFO
DEBUG: [common/encfstools.py:130 EncFS_mount.isConfigured] No encfs config in /media/aaron/backintime-t450s/back-in-time/.encfs6.xml
DEBUG: [common/mount.py:692 EncFS_mount.mountProcessLockRelease] Release mountprocess lock /home/aaron/.local/share/backintime/mnt/17394.lock
ERROR: [common/config.py:1357 Config.canBackup] /home/aaron/.local/share/backintime/mnt/1_17394/backintime/aaron-ThinkPad-T450s/aaron/1 does not exist
DEBUG: [common/tools.py:1237 readCrontab] Read 2 lines from users crontab
DEBUG: [common/config.py:1466 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1500 Config.cronLine] Profile: Main profile | Automatic backup: Disabled
DEBUG: [common/config.py:1500 Config.cronLine] Profile: main2 | Automatic backup: Disabled
DEBUG: [common/config.py:1500 Config.cronLine] Profile: offsite-backup | Automatic backup: Disabled
DEBUG: [common/config.py:1450 setupCron] Crontab didn't change. Skip writing.
```

I noticed that when I closed the GUI debug version, nothing showed in the CLI at all. It's as though the GUI closing is just doing nothing. The processes only stopped at all after I did ctrl-C in the terminal.

**Comment by emtiu** [comment]
Thanks a lot for the debug info! We'll see if we can get this reproduced.

**Comment by wolftune** [comment]
I have indeed been using encfs for one of my backup drives

**Comment by aryoda** [comment]
> I have indeed been using encfs for one of my backup drives, but the pass is something I enter when starting BiT

Is your main config using the encfs drive?

And which password do you mean? Are you starting BiT as root (I thought no), is it a password to open a keyring/password safe or some automount thing of dolphin?

I saw this in your debug output which is IMHO a hint for BiT asking for the encfs password:

> DEBUG: [common/encfstools.py:64 EncFS_mount._mount] Provide password through temp FIFO

**Comment by wolftune** [comment]
My main config uses the encfs drive

I am not starting BiT as root. The pass I enter is what I used with an older GPG key, and I never use it anymore in any other context.

**Comment by buhtz** [comment]
Hello Aaron,
current maintainer here. 😄 

The last comments are quit old. How is the current status. Which version do you use and do you still see the problem?

Please note that BIT 1.6.1 is the last version with EncFS support. Starting with 2.0.0 EncFS profiles simply will be removed from the config.

It would be nice if you could give me steps to reproduce this in the latest stable BIT release 1.6.1.

Regards,
Christian

**Comment by wolftune** [comment]
Hi! I'm still using BiT, but apparently at 1.4.3 still. Will 2.0 still offer encryption in some other way? Will older backups still be able to be used or be transitioned to something new or what?

I don't think I've been having the problems actually. I have continued using BiT and have not encountered these old issues. They might be fixed even at or before 1.4.3

**Comment by buhtz** [comment]
Hello Aaron,
thank you for your message and questions. Please have a look here: https://github.com/bit-team/backintime/blob/dev/doc/ENCRYPT_TRANSITION.md

Let me know if you still have open questions after reading this.

Best,
Christian

**Comment by wolftune** [comment]
Okay, sounds like it's reasonable that I just keep using the version I have for now, and I'll make new backups when v2 is out and accept that the old backups will eventually get erased (and can be accessed prior to that using the old version of BiT).

I'll close this for now

**Comment by buhtz** [comment]
> Okay, sounds like it's reasonable that I just keep using the version I have for now, and I'll make new backups when v2 is out

I will prepare release candidates (like beta-versions) before the release. It would help a lot if you could test them.

> and accept that the old backups will eventually get erased

BIT won't erase any exiting backup. It erase only the EncFS profile configuration but not the backups behind it. You can access them without BIT everytime.

I really appreciate your feedback. Feel free to ask further questions suggest modifications.
