### ISSUE TITLE
BiT crashes when choosing "local encrypted" backup method

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#122]
I read that BiT since short supports encrypted backups. Of course I want that after having a full partition encryption and as BiT was my favourite backup tool! After choosing local encrypted backup, entering a password and clicking on OK - BiT crashes reproducibly with following error:
--
Back In Time
Version: 1.0.26

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

which: no gloobus-preview in (/usr/bin:/usr/sbin)
The application is not configured !
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1280, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 321, in __init__
    settingsdialog.SettingsDialog( self.config, self.snapshots, self ).run()
  File "/usr/share/backintime/gnome/settingsdialog.py", line 1102, in run
    if not self.validate():
  File "/usr/share/backintime/gnome/settingsdialog.py", line 1246, in validate
    if not self.save_profile():
  File "/usr/share/backintime/gnome/settingsdialog.py", line 945, in save_profile
    mnt.pre_mount_check(mode = mode, first_run = True, **mount_kwargs)
  File "/usr/share/backintime/common/mount.py", line 120, in pre_mount_check
    return tools.pre_mount_check(first_run)
  File "/usr/share/backintime/common/encfstools.py", line 107, in pre_mount_check
    self.check_fuse()
  File "/usr/share/backintime/common/encfstools.py", line 165, in check_fuse
    fuse_grp_members = grp.getgrnam('fuse')[3]
KeyError: 'getgrnam(): name not found: fuse'
--

I'm using kernel 3.10.10-1 with FUSE 2.9.3-1 and EncFS 1.7.4-11.

Any idea?

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-09-14T23:56:20Z
 * owner: emak
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1225561

**Comment by Germar** [comment]
(by germar)
The crash is a bug. But it only occur because you don't have a 'fuse' group in which you are member. Please run 'sudo adduser <YOUR_USER> fuse' in Terminal.

**Comment by Germar** [comment]
(by germar)
Sorry, I forgot to mention that you need to log out and log in again after the 'adduser' command.

**Comment by Germar** [comment]
(by emak)
No problems - added group and user to it. Works by now and thanks a lot!
