### ISSUE TITLE
don't crash if sshfs is not found

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#125]
By updating from Ubuntu 13.10 t0 14.04 sshfs somehow got de-installed, which I did not notice.

Starting bit being configured taking snapshots to a ssh-destination showed the gui for some seconds and then crashed. On the cl bit gave me following backtrace:

simon@laptop:~$ gksudo backintime-gnome 

Back In Time
Version: 1.0.34

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1294, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 340, in __init__
    hash_id = mnt.mount()
  File "/usr/share/backintime/common/mount.py", line 79, in mount
    return tools.mount(check = check)
  File "/usr/share/backintime/common/mount.py", line 200, in mount
    self._mount()
  File "/usr/share/backintime/common/sshtools.py", line 104, in _mount
    subprocess.check_call(sshfs, env = env)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden
simon@laptop:~$ 

After "sudo apt-get install sshfs" bit now works.
For the user it would be better to not crash, but show a notice that sshfs could not be found and suggest to install it (or to change the config to a local destination).

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-05-05T19:38:38Z
 * owner: simon-harhues
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1316288

**Comment by Germar** [comment]
(by germar)
BIT does already check if sshfs is installed. But only after pressing OK in Settingsdialog. I'll change this to run every time sshfs will be called.
