### ISSUE TITLE
Error in v1.2.1 on Ubuntu 22.04 LTS: `AttributeError: module 'collections' has no attribute 'MutableSet'`

### ISSUE THREAD

**Issue by jdrch** [bit-team/backintime#1259]
I'm getting the above error on [this machine](https://github.com/jdrch/Hardware/blob/master/HP%20ProBook%204530s.md). Full error text:

```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 1802, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

Any ideas?

**Comment by gsker** [comment]
Duplicate of #1245
