### ISSUE TITLE
Backintime-qt snapshots fail with path errors

### ISSUE THREAD

**Issue by casanovg** [bit-team/backintime#1262]
Backintime stopped working on Fedora 36 as of June 5th, it worked smoothly before. The backup storage I am using is remote, mounting sshfs folders. 

The error it returns when launching a snapshot is from rsync (see below). However, I've tried copying directories by hand to remote sshfs folders with several different rsync options and it works fine.

This initially rules out login and connection problems with the backup server. It would give the impression that backintime is "building" the routes wrong before launching the rsync command:

> WARNING: Command "rsync -a --delete --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/home/netbackup/.ssh/id_rsa -p 22 /tmp/tmpawvpdq4q/ netbackup@10.6.17.70:"/mnt/hta-nasvol01/hta-backup/backintime/hta-fileserver.htarg.lan/netbackup/10/20220628-091035-792"" returns 3 | rsync: change_dir#3 "/mnt/hta-nasvol01/home/netbackup//"/mnt/hta-nasvol01/hta-backup/backintime/hta-fileserver.htarg.lan/netbackup/10" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(703) [Receiver=3.1.3]

> Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 739, in backup
    ret = takeSnapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
    ret = snapshots.Snapshots(cfg).backup(force)
  File "/usr/share/backintime/common/snapshots.py", line 701, in backup
    self.remove(sid)
  File "/usr/share/backintime/common/snapshots.py", line 583, in remove
    shutil.rmtree(sid.path())
  File "/usr/lib64/python3.10/shutil.py", line 714, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib64/python3.10/shutil.py", line 712, in rmtree
    orig_st = os.lstat(path)

> FileNotFoundError: [Errno 2] No such file or directory: '/home/netbackup/.local/share/backintime/mnt/8_15082/backintime/hta-fileserver.htarg.lan/netbackup/10/20220628-091035-792'

**Comment by gsker** [comment]
Could you include your version of backintime and the version of rsync?

**Comment by casanovg** [comment]
Sure ...
[netbackup@hta-fileserver ~]$ backintime --version
**backintime 1.3.2**
[netbackup@hta-fileserver ~]$ rsync --version
**rsync  version 3.2.4  protocol version 31**

**Comment by gsker** [comment]
Is this a duplicate of #1247 ?

**Comment by casanovg** [comment]
Apparently yes, it's the same. Adding "--old-args" as suggested in that thread works again, Thanks!
Sorry to open a new issue, I didn't link it by title because I normally use the BackInTime version packed by Fedora "out-of-the-box". I never update its components (rsync, QT, etc.) individually.
