### ISSUE TITLE
Problem with keep min free space

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#138]
After the backup with smart-remove my command window looks like:
INFO: Keep min free disk space: 199680 Mb
INFO: Keep min 2% free inodes
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 436, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 191, in start_app
    ret = take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 52, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 931, in take_snapshot
    self._free_space( now )
  File "/usr/share/backintime/common/snapshots.py", line 1568, in _free_space
    if last_snapshot is not snapshots[-1]:
UnboundLocalError: local variable 'last_snapshot' referenced before assignment
INFO: [qt4systrayicon] end loop

What's the problem?

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

ii  backintime-common       1.1.4~trusty     all              Simple backup system (common)
ii  backintime-gnome        1.1.4~trusty     all              Virtual package
ii  backintime-qt4          1.1.4~trusty     all              Simple backup system

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-03-28T13:36:37Z
 * owner: dbet1
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1437623

**Comment by Germar** [comment]
(by germar)
You've deactivated 'Remove snapshots older than', right? Until next version you could 'fix' this by activating this again. Just set e.g. 20 years and nothing will be deleted.

Problem is me adding new features short before releasing new versions >:|

**Comment by Germar** [comment]
(by dbet1)
Yes, you are right! I have activated this option now and the error is gone. Thank you.
