### ISSUE TITLE
WARNING: A backup is already running.  The pid of the already running backup is in file /home/<user>/.local/share/backintime/worker.lock.  Maybe delete it

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#1387]
Any suggestion on how to end this backup? 

```
$ backintime backup

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

WARNING: A backup is already running.  The pid of the already running backup is in file /home/<user>/.local/share/backintime/worker.lock.  Maybe delete it
```

How did I got stuck with the above? 

A few hours ago I tried to `umount` the external drive where I back up /home/, in vain. These are the details:

```
$ umount /media/<user>/backup 
Error unmounting block device 8:17: GDBus.Error:org.freedesktop.UDisks2.Error.DeviceBusy: Error unmounting /dev/sdb1: target is busy
```

I ran `backintime backup` to check whether BiT was actually running a backup: 

```
$ backintime backup

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Found leftover 'new_snapshot' which can be continued.
INFO: Call rsync to take the snapshot
ERROR: Failed to set 'save_to_continue' flag: [Errno 13] Permission denied: '/media/<user>/backup/<computer>/<user>/1/new_snapshot/save_to_continue'
notify-send Back In Time () : Main profile Error: rsync: failed to set times on "/media/<user>/backup/<computer>/<computer>/<user>/1/new_snapshot/backup/.": Operation not permitted (1)
notify-send Back In Time () : Main profile Error: rsync: failed to set times on "/media/<user>/backup/<computer>/<computer>/<user>/1/new_snapshot/backup/home": Operation not permitted (1)
^CERROR: Failed to remove 'save_to_continue' flag: [Errno 13] Permission denied: '/media/<user>/backup/backintime/<computer>/<user>/1/new_snapshot/save_to_continue'
Traceback (most recent call last):
  File "/usr/share/backintime/common/snapshots.py", line 692, in backup
    ret_val, ret_error = self.takeSnapshot(sid, now, include_folders)
  File "/usr/share/backintime/common/snapshots.py", line 1036, in takeSnapshot
    proc.run()
  File "/usr/share/backintime/common/tools.py", line 1972, in run
    for line in self.currentProc.stdout:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 739, in backup
    ret = takeSnapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
    ret = snapshots.Snapshots(cfg).backup(force)
  File "/usr/share/backintime/common/snapshots.py", line 697, in backup
    new.failed = True
  File "/usr/share/backintime/common/snapshots.py", line 2246, in failed
    self.makeWritable()
  File "/usr/share/backintime/common/snapshots.py", line 2385, in makeWritable
    return os.chmod(path, rw)
PermissionError: [Errno 1] Operation not permitted: '/media/<user>/backup/backintime/<computer>/<user>/1/new_snapshot'

$ Traceback (most recent call last):
  File "/usr/share/backintime/qt/qtsystrayicon.py", line 145, in updateInfo
    def updateInfo(self):
KeyboardInterrupt
^C
$ backintime backup

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

WARNING: A backup is already running.  The pid of the already running backup is in file /home/<user>/.local/share/backintime/worker.lock.  Maybe delete it
```

I don't understand why deleting `worker.lock` would end the backup in progress.

**Comment by aryoda** [comment]
> I don't understand why deleting worker.lock would end the backup in progress.

It doesn't.

BiT uses signal files like this `worker.lock` to avoid starting the same backup twice.
Normally it is deleted if the backup finishes.

In your case something went wrong BiT was forcefully stopped without having the chance to delete
this signal file.

Since BiT does only start a new backup job (for the same profile) if the signal file does **not** exist,
you have to delete it first.

Before that please make sure that BiT is not running anymore via

```
ps aux | grep -i backintime
```

If the output shows a running BiT instance you could either wait until it finishes or kill it via `kill <process id>` where the process id is shown in above output.

**Comment by aryoda** [comment]
**Internal note:**

> WARNING: A backup is already running.  The pid of the already running backup is in file /home/<user>/.local/share/backintime/worker.lock.  Maybe delete it

I think above message is misleading and should say instead that "**it looks like** a backup is already running."

Perhaps a new BiT argument "reset lock files" could be implemented to make this easier for users (and to check if really no instance is still running)...
