### ISSUE TITLE
solved: backintime returns error 5888 and is not saving all folders

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#153]
Hi,
I always get the rsync error 5888 if I do a snapshot.
OS: openSUSE 11.1 64Bit KDE 4.2.3-3.1
Python: Python 2.6 (r26:66714, Feb  3 2009, 20:49:49)
rsync: rsync  version 3.0.4  protocol version 30

Back In Time
Version: 0.9.16.1

Back In Time comes with ABSOLUTELY NO WARRANTY; for details type `backintime --license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: [KDE4TakeSnapshotCallback.run]
INFO: Compare with old snapshot: 20090428-211502
INFO: [KDE4TakeSnapshotCallback.run] no X server
WARNING: Command "rsync -a -i --dry-run --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --include="/etc/" --include="/var/spool/cron/" --include="/var/spool/" --include="/var/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --include="/home/benjamin/**" --include="/etc/**" --include="/var/spool/cron/**" --exclude="*" / "/backup_home/backintime/backintime/20090428-211502/backup/"" returns 5888
INFO: Create hard-links
INFO: Command "mkdir -p "/backup_home/backintime/backintime/20090429-211502/backup/"" returns 0
INFO: Command "cp -al "/backup_home/backintime/backintime/20090428-211502/backup//"* "/backup_home/backintime/backintime/20090429-211502/backup/"" returns 0
INFO: Command "chmod -R a+w "/backup_home/backintime/backintime/20090429-211502"" returns 0
INFO: Call rsync to take the snapshot
WARNING: Command "rsync -a -v --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --include="/etc/" --include="/var/spool/cron/" --include="/var/spool/" --include="/var/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --include="/home/benjamin/**" --include="/etc/**" --include="/var/spool/cron/**" --exclude="*" / "/backup_home/backintime/backintime/20090429-211502/backup/"" returns 5888
INFO: Command "chmod -R a-w "/backup_home/backintime/backintime/20090429-211502"" returns 0
INFO: Remove backups older then: 20090425-000000
INFO: Command "chmod -R a+w "/backup_home/backintime/backintime/20090423-230844"" returns 0
INFO: Command "rm -rf "/backup_home/backintime/backintime/20090423-230844"" returns 0
INFO: Unlock

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-05-26T19:50:56Z
 * owner: mr-booter
 * assignee: danleweb
 * the launchpad url was https://bugs.launchpad.net/bugs/380728

**Comment by Germar** [comment]
(by danleweb)
Can you tell me what is your destination drive file system ? (local: ntfs/fat/ext3..., remote: samba ...)

Please make a small test:
1. create a directory on your destination drive: /backup_home/backintime/abc
2. from a console run rsync command:
rsync -a -v --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --include="/etc/" --include="/var/spool/cron/" --include="/var/spool/" --include="/var/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --include="/home/benjamin/**" --include="/etc/**" --include="/var/spool/cron/**" --exclude="*" / "/backup_home/backintime/abc/"
3. attach the output of rsync command to this bug

**Comment by Germar** [comment]
(by mr-booter)
1. I make backup to a attached usb disk with ext3.
2. Seems to work well.
3. Output:
rsync -a -v --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --include="/etc/" --include="/var/spool/cron/" --include="/var/spool/" --include="/var/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --include="/home/benjamin/**" --include="/etc/**" --include="/var/spool/cron/**" --exclude="*" / "/backup_home/backintime/backintime/abc/" > output.log
rsync: readlink_stat("/home/benjamin/.gvfs") failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1040) [sender=3.0.4]

**Comment by Germar** [comment]
(by mr-booter)
Seems so that rsync cannot handle that long command line. I have seen that there are several folders were missing.

My backintime configfile:

kde4.main_window.second_splitter_left_w=249
snapshots.include_folders=/home/benjamin:/usr/local/RootTamex/var/spool/fax/etc:/usr/local/RootTamex/var/spool/cron:/usr/local/RootTamex/var/spool/mail/Maildir:/usr/local/RootTamex/etc:/usr/local/RootTamex/usr/local/bin:/etc:/var/spool/cron
snapshots.path=/backup_home/backintime
snapshots.min_free_space.value=1
snapshots.exclude_patterns=*.backup*:*~:dosdevices/*
kde4.last_path=/
kde4.main_window.x=314
kde4.main_window.height=502
snapshots.remove_old_snapshots.enabled=true
kde4.main_window.files_view.sort.column=0
kde4.main_window.files_view.date_width=175
snapshots.automatic_backup_mode=0
snapshots.remove_old_snapshots.value=4
kde4.main_window.y=335
kde4.main_window.files_view.sort.ascending=true
kde4.main_window.width=800
kde4.main_window.main_splitter_right_w=296
snapshots.min_free_space.enabled=false
kde4.main_window.files_view.name_width=148
kde4.main_window.second_splitter_right_w=249
kde4.main_window.files_view.size_width=100
kde4.main_window.main_splitter_left_w=501
snapshots.remove_old_snapshots.unit=20
kde4.show_hidden_files=true
snapshots.min_free_space.unit=20

**Comment by Germar** [comment]
(by danleweb)
The command line seems ok since the destination (the last parameter) is there. Maybe at the moment you saw the error you had less folders. Can you please try again ?

About error 5888: the probleme seems to be:
rsync: readlink_stat("/home/benjamin/.gvfs") failed: Permission denied (13)

/home/<user>/.gvfs is a special place used by gnome/nautilus to mount some devices (samba, ...). 
Please exclude it and try again.

**Comment by Germar** [comment]
(by mr-booter)
Hi Dan,
I tried again. The error 5888 seems to be fixed with excluding .gvfs.
At this backup again several folders were not snapshoted.


This is the Output:
Autodetect GUI mode: kde4
CMD: /usr/bin/backintime-kde4
Back In Time
Version: 0.9.16.1

Back In Time comes with ABSOLUTELY NO WARRANTY; for details type `backintime --license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: [KDE4TakeSnapshotCallback.run]
INFO: Lock
INFO: Compare with old snapshot: 20090505-211503
INFO: [KDE4TakeSnapshotCallback.run] begin loop
WARNING: QApplication was not created in the main() thread.
INFO: Command "rsync -a -i --dry-run --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --exclude="/home/benjamin/.gvfs" --include="/home/benjamin/**" --exclude="*" / "/backup_home/backintime/backintime/20090505-211503/backup/"" returns 0
INFO: Create hard-links
INFO: Command "mkdir -p "/backup_home/backintime/backintime/20090528-211034/backup/"" returns 0
INFO: Command "cp -al "/backup_home/backintime/backintime/20090505-211503/backup//"* "/backup_home/backintime/backintime/20090528-211034/backup/"" returns 0
INFO: Command "chmod -R a+w "/backup_home/backintime/backintime/20090528-211034"" returns 0
INFO: Call rsync to take the snapshot
INFO: Command "rsync -a -v --safe-links --whole-file --delete --delete-excluded --include="/home/benjamin/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --exclude="/home/benjamin/.gvfs" --include="/home/benjamin/**" --exclude="*" / "/backup_home/backintime/backintime/20090528-211034/backup/"" returns 0
INFO: Command "chmod -R a-w "/backup_home/backintime/backintime/20090528-211034"" returns 0
INFO: Remove backups older then: 20090524-000000
INFO: Command "chmod -R a+w "/backup_home/backintime/backintime/20090504-211503"" returns 0
INFO: Command "rm -rf "/backup_home/backintime/backintime/20090504-211503"" returns 0


But there are missing several folders:
only /home/benjamin is backup up.

Whats wrong here?

**Comment by Germar** [comment]
(by danleweb)
Can you update it (from sources) to version 0.9.26 ?

**Comment by Germar** [comment]
(by mr-booter)
The update also seems not to work.
Only /home/benjamin is backup up.


Back In Time
Version: 0.9.26

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Include folders: ['/home/benjamin']
INFO: Ignore folders: []
INFO: Last snapshots: {}
INFO: [KDE4Plugin.Systray.run]
INFO: Command "chmod -R a+rwx "/backup_home/backintime/backintime/new_snapshot"" returns 0
INFO: Command "rm -rf "/backup_home/backintime/backintime/new_snapshot"" returns 0
INFO: Compare with old snapshot: 20090601-211501
INFO: Command "rsync -aEAX  -i --dry-run  --chmod=Fa-w,D+w --whole-file --delete  --exclude="/backup_home/backintime" --exclude="/root/.local/share/backintime" --include="/home/benjamin/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --exclude="/home/benjamin/.gvfs" --include="/home/benjamin/**" --exclude="*" / "/backup_home/backintime/backintime/20090601-211501/backup/"" returns 0
INFO: Create hard-links
INFO: Command "cp -al "/backup_home/backintime/backintime/20090601-211501/backup/"* "/backup_home/backintime/backintime/new_snapshot/backup/"" returns 0
INFO: Call rsync to take the snapshot
INFO: Command "rsync -aEAX  -v --delete-excluded  --chmod=Fa-w,D+w --whole-file --delete  --exclude="/backup_home/backintime" --exclude="/root/.local/share/backintime" --include="/home/benjamin/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="dosdevices/*" --exclude="/home/benjamin/.gvfs" --include="/home/benjamin/**" --exclude="*" / "/backup_home/backintime/backintime/new_snapshot/backup/"" returns 0
INFO: Save permissions
INFO: Remove backups older than: 20090528-000000



Config:
config.version=2
kde4.last_path=/usr/local/RootTamex/var/spool/fax/etc
kde4.main_window.files_view.date_width=241
kde4.main_window.files_view.name_width=148
kde4.main_window.files_view.size_width=100
kde4.main_window.files_view.sort.ascending=true
kde4.main_window.files_view.sort.column=0
kde4.main_window.height=965
kde4.main_window.main_splitter_left_w=266
kde4.main_window.main_splitter_right_w=1011
kde4.main_window.second_splitter_left_w=495
kde4.main_window.second_splitter_right_w=495
kde4.main_window.width=1280
kde4.main_window.x=-4
kde4.main_window.y=-4
kde4.show_hidden_files=true
snapshots.automatic_backup_mode=0
snapshots.cron.nice=true
snapshots.dont_remove_named_snapshots=true
snapshots.exclude_patterns=*.backup*:*~:dosdevices/*:/home/benjamin/.gvfs
snapshots.expert.per_directory_schedule=false
snapshots.include_folders=/home/benjamin|0:/usr/local/RootTamex/var/spool/fax/etc|0:/usr/local/RootTamex/var/spool/cron|0:/usr/local/RootTamex/var/spool/mail/Maildir|0:/usr/local/RootTamex/etc|0:/usr/local/RootTamex/usr/local/bin|0
snapshots.min_free_space.enabled=false
snapshots.min_free_space.unit=20
snapshots.min_free_space.value=1
snapshots.notify.enabled=true
snapshots.path=/backup_home/backintime
snapshots.remove_old_snapshots.enabled=true
snapshots.remove_old_snapshots.unit=20
snapshots.remove_old_snapshots.value=4
snapshots.smart_remove=false
~

**Comment by Germar** [comment]
(by danleweb)
Is it possible that you run the application as root but you configure it as user ?

**Comment by Germar** [comment]
(by mr-booter)
Thats what I actually do.

**Comment by Germar** [comment]
(by danleweb)
Ok, so there should be 2 config files. One for your user (~/.config/backintime/config) and one for the root (/root/.config/backintime/config). Please check them both. If you want to share the config you can make a symbolic link from ~/.config/backintime/config to /root/.config/backintime/config.

**Comment by Germar** [comment]
(by mr-booter)
I have copied the user config to the root.
But same problem. I think backintime only uses the first path at the variable snapshots.include_folders.

**Comment by Germar** [comment]
(by mr-booter)
I found out that the problem is in this function at snapshots.py:
def _get_backup_folders( self, now, force ):
                include_folders = []
                ignore_folders = []
                dict = self._get_last_snapshot_info()
                dict2 = {}

                all_include_folders = self.config.get_include_folders()

                for item in all_include_folders:
                        path = item[0]
                        path = os.path.expanduser( path )
                        path = os.path.abspath( path )

                        if path in dict:
                                dict2[ path ] = dict[ path ]

                        if not os.path.isdir( path ):
                                continue

                        if not force and path in dict:
                                if not self._is_auto_backup_needed( now, dict[path], item[1] ):
                                        ignore_folders.append( path )
                                        continue

                        include_folders.append( path )
        
                logger.info( "Include folders: %s" % include_folders )
                logger.info( "Ignore folders: %s" % ignore_folders )
                logger.info( "Last snapshots: %s" % dict2 )

                return ( include_folders, ignore_folders, dict2 )


The if statement:
if not os.path.isdir( path ):
It filters all entrys out execpt of the first one.

Could you explain me what this if statement does?

Thank you.

**Comment by Germar** [comment]
(by mr-booter)
I think the not in "if not os.path.isdir( path ); should be if os.path.isdir (path);  --> The not must be false

**Comment by Germar** [comment]
(by mr-booter)
After some further testing I found the problem.
I uses sshfs for mounting a remote folder to backup.
The problem is if the folder is mounted with a different user than the backup is made the folder shows something like this
d?????????  ? ?        ?        ?             ? RootTamex
So you can't access it anymore and backintime ignores it.
Perhaps somebody with the same problem will help this

The bugreport can be closed.

**Comment by Germar** [comment]
(by rmjb)
User fixed

**Comment by Germar** [comment]
(by g-launchpad-iiegn-de)
related to this and #534829 (but might also be filed as new bug): i get error 5888 unless i ignore ~/.Private (a user's encrypted folder - where the decrypted one is mounted as ~/Private).

so, there are two things with this:
1. the folder might also be put on the ignore list from the very start
2. in my case it seemed a bit unfortunate that the process first copies some 180GB to fail and then delete /all/ of the backup, i.e. nothing of a new backup was left. i'd rather have a long list of errors... and a partial backup.

additional info:
 - backup is done as root (via sudo)

**Comment by Germar** [comment]
(by dominik-mayer)
I have the same problem:

-----------
dominik ~  $  backintime -b

Back In Time
Version: 1.0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

** Message: pygobject_register_sinkfunc is deprecated (GtkWindow)
** Message: pygobject_register_sinkfunc is deprecated (GtkInvisible)
** Message: pygobject_register_sinkfunc is deprecated (GtkObject)
Gtk-Message: Failed to load module "globalmenu-gnome": libglobalmenu-gnome.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
INFO: Lock
INFO: [GnomePlugin.Systray.run]
INFO: on process begins
INFO: [GnomePlugin.Systray.run] begin loop
INFO: Profile_id: 1
INFO: Compare with old snapshot: 20100912-044356
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/media/WD/Backup" --exclude="/home/dominik/.local/share/backintime" --include="/home/dominik/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="/home/dominik/Bilder" --exclude="/home/dominik/.gvfs" --exclude="/home/dominik/lost+found" --exclude="/home/dominik/.dbus" --include="/home/dominik/**" --exclude="*" / "/media/WD/Backup/backintime/thinkpad/dominik/1/20100912-044356/backup/"" returns 0
INFO: Create hard-links
INFO: Command "find "/media/WD/Backup/backintime/thinkpad/dominik/1/20100912-044356/backup/" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "cp -aRl "/media/WD/Backup/backintime/thinkpad/dominik/1/20100912-044356/backup/"* "/media/WD/Backup/backintime/thinkpad/dominik/1/new_snapshot/backup/"" returns 0
INFO: Command "find "/media/WD/Backup/backintime/thinkpad/dominik/1/20100912-044356/backup/" -type d -exec chmod a-w {} \;" returns 0
INFO: Command "chmod -R a+w "/media/WD/Backup/backintime/thinkpad/dominik/1/new_snapshot"" returns 0
INFO: Call rsync to take the snapshot
WARNING: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/media/WD/Backup" --exclude="/home/dominik/.local/share/backintime" --include="/home/dominik/" --include="/home/" --exclude="*.backup*" --exclude="*~" --exclude="/home/dominik/Bilder" --exclude="/home/dominik/.gvfs" --exclude="/home/dominik/lost+found" --exclude="/home/dominik/.dbus" --include="/home/dominik/**" --exclude="*" / "/media/WD/Backup/backintime/thinkpad/dominik/1/new_snapshot/backup/" 2>&1" returns 5888
INFO: Command "find "/media/WD/Backup/backintime/thinkpad/dominik/1/new_snapshot" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "rm -rf "/media/WD/Backup/backintime/thinkpad/dominik/1/new_snapshot"" returns 0
INFO: Command "chmod -R a-w "/media/WD/Backup/backintime/thinkpad/dominik/1/20100912-044356/backup/"" returns 0
INFO: Command "rm -rf "/media/WD/Backup/backintime/thinkpad/dominik/1/20100918-010714-950"" returns 0
-----------

If I don't exclude .gvfs, lost+found, .dbus, the first rsync also returns 5888. I've tried the process four times and backintime copied about 25 GB and then finally deleted the whole backup. I have no idea why.

Backup drive is formatted ext4 and backing up has been working before but I only backed up subfolders of /home/dominik at that time (and it was before updating to version 1.0).

**Comment by Germar** [comment]
(by danleweb)
This is because rsync can't copy or set user/rights on some special files. Maybe the log view (BIT >= 1.0) can help you detect this files. This is all I can do.

**Comment by Germar** [comment]
(by dominik-mayer)
Can you at least make sure that the user knows about this? Or gets some kind of note. Back In Time shouldn't delete 25 GB without even prompting or asking. Does it have any negative effects if the snapshot is marked as "failed"?

**Comment by Germar** [comment]
(by 0m3g4)
hi, i have this error on ubuntu maverick:


backintime -b

Back In Time
Version: 1.0.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: on process begins
INFO: Profile_id: 1
INFO: Call rsync to take the snapshot
INFO: [kde4systrayicon] begin loop
WARNING: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/media/BOX" --exclude="/home/omega/.local/share/backintime" --include="/home/omega/" --include="/home/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/omega/Ubuntu One" --exclude=".dropbox*" --include="/home/omega/**" --exclude="*" / "/media/BOX/backintime/omg-lin/omega/1/new_snapshot/backup/" 2>&1" returns 5888
INFO: Command "find "/media/BOX/backintime/omg-lin/omega/1/new_snapshot" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "rm -rf "/media/BOX/backintime/omg-lin/omega/1/new_snapshot"" returns 0
INFO: Command "rm -rf "/media/BOX/backintime/omg-lin/omega/1/20101020-223139-135"" returns 0
ERROR: Failed to take snapshot !!!
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 128, in update_info
    self.show_popup()
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 106, in show_popup
    self.popup = KPassivePopup.message( self.config.APP_NAME, QString.fromUtf8( self.last_message[1] ), self.status_icon )
NameError: global name 'KPassivePopup' is not defined
INFO: Unlock
INFO: [kde4systrayicon] end loop

**Comment by Germar** [comment]
(by 0m3g4)
EDIT comment #20

problem fixed removing  or changing permission of file .viminfo

**Comment by Germar** [comment]
(by danleweb)
Since you have BIT >= 1.0 you can check log view (main toolbar). Maybe you will get more information there.
