### ISSUE TITLE
backintime -b gets python exception - FC11

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#155]
python version is 2.6-9fc11

harry@crow:~/Desktop]$ backintime -b
Back In Time
Version: 0.9.26

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Include folders: ['/home/harry']
INFO: Ignore folders: []
INFO: Last snapshots: {}
INFO: [GnomePlugin.Systray.run]
INFO: [GnomePlugin.Systray.run] begin loop
INFO: Compare with old snapshot: 20090830-000001
INFO: Command "rsync -aEAX  -i --dry-run  --chmod=Fa-w,D+w --whole-file --delete  --exclude="/mnt/pelican" --exclude="/home/harry/.local/share/backintime" --include="/home/harry/" --include="/home/" --exclude=".*" --exclude="*.backup*" --exclude="*~" --include="/home/harry/**" --exclude="*" / "/mnt/pelican/backintime/20090830-000001/backup/"" returns 0
INFO: Nothing changed, no back needed
WARNING: No new snapshot (not needed or error)
INFO: Remove backups older than: 19990905-000000
INFO: Keep min free disk space: 1024 Mb
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/usr/share/backintime/plugins/gnomeplugin.py", line 145, in run
    self.notification.close()
GError: 0 is not a valid notification ID

INFO: Unlock

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-09-06T00:37:27Z
 * owner: harry
 * the launchpad url was https://bugs.launchpad.net/bugs/425033

**Comment by Germar** [comment]
(by bratdaking)
A known error message. However it does not interfere with the other processes. It should be fixed though.

**Comment by Germar** [comment]
(by danleweb)
Plugins have been changed. Does this problem persists in BIT 1.0 ?

**Comment by Germar** [comment]
(by harry)
  On 10/3/10 7:14 AM, Dan wrote:
> Plugins have been changed. Does this problem persists in BIT 1.0 ?
>
Sorry, I no longer have FC11.  I upgraded to FC13 quite a while ago.  
I'm currently running backintime on FC13 and Ubuntu 10.04.1 with no 
problems.  Saved me last week when I accidentally did a "sudo rm -rf *" 
on Ubuntu.

I did try to use a CIFS share for backup and saw they aren't supported.  
So if you could put that in for a feature request it would be great.

Thanks for your efforts.

Harry

**Comment by Germar** [comment]
(by danleweb)
OK, so I'll pass this to fixed.

For remote backups: 
1. use "user-callback" script (you can mount, unmount the remote drive)
2. use shared folder that is always mounted

Or you can use an external drive.

I started to think about basic mount capabilities, but the work didn't start yet.

Regards,
Dan
