### ISSUE TITLE
ProcessLookupError with rare combination of start/stop/pause buttons on a slow system

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1604]
# Introduction
Welcome to the project, if you pick up this Issue because of the
"GOOD FIRST USE" label. You will be mentored through the process if you
want. First the Issue is explained. At the end you will find some
guidance for first contributors. Please do not hesitate to ask questions.
Your solution don't need to be perfect.

Participation or contribution is not recommended unless you are familiar with Back In Time and are an active user. This project is not intended for learning basic Python skills or enhancing your GitHub profile.

# Description of the problem
While manual testing the qt6 migration and clicking wild around in the GUI I discovered an Issue.

It seems to happen only in a rare (unusual) combination of the buttons to start, pause and stop a snapshot. My hypothesis is that I can trigger the problem because I am (as the user) are to fast and my system (a RaspberryPi4) is to slow. I assume this is not critical and not urgent.

That is the relevant error message.
```
DEBUG: [common/pluginmanager.py:249 PluginManager.load] Probing plugin systrayiconplugin.py
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 469, in <lambda>
    lambda: os.kill(self.snapshots.pid(), signal.SIGSTOP), None,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] Kein passender Prozess gefunden
Aborted

```

## Steps to reproduce

Reproduce it with the following steps:
1. Press take snapshot button.
2. Press the stop button some seconds later. On my Pi4 2-3 seconds. You will observe in the terminal window behind that there are still some log lines produced.
4. Press take snapshot button again.
5. Press pause button quit quickly. The GUI crash with a `ProcessLookupError` but in the terminal window you do see that there is still activity in the background.

This screencast illustrate how to reproduce it.
![Peek 2024-01-08 14-53](https://github.com/bit-team/backintime/assets/11861496/3524b39f-242f-43eb-8026-5fdebcca471a)

## Diagnostic output
```
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.2-dev",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.1.0-13-arm64-aarch64-with-glibc2.36",
        "system": "Linux #1 SMP Debian 6.1.55-1 (2023-09-29)",
        "OS": {
            "/etc/os-release": "Debian GNU/Linux 12 (bookworm)",
            "/etc/debian_version": "12.4\n"
        },
        "display-system": "x11",
        "locale": "de_DE, UTF-8",
        "PATH": "/home/UsernameReplaced/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.local/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.11.2 main Mar 13 2023 12:18:29 CPython GCC 12.2.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.11",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/share/backintime/qt",
            "/usr/lib/python311.zip",
            "/usr/lib/python3.11",
            "/usr/lib/python3.11/lib-dynload",
            "/usr/local/lib/python3.11/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.11/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 6.4.2 / Qt 6.4.2",
            "Theme": "Tango",
            "Theme Search Paths": [
                "/usr/local/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.2.7",
            "protocol": "31.0",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": false,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ]
        },
        "ssh": "OpenSSH_9.2p1 Debian-2+deb12u1, OpenSSL 3.0.11 19 Sep 2023",
        "sshfs": "3.7.3",
        "encfs": "(no encfs)",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.15(1)-release (aarch64-unknown-linux-gnu)"
    }
}

```

# Your next steps
1. If this is your first contribution in this project please introduce
   your self and tell us about your skills, wishes and plans. Also let us
   know how you found the issue and the project.
2. Read the existing [contributors documentation](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md).
3. We can develop the next steps in the further discussion. Don't hesitate to ask.

# What need to be done?
Try to reproduce the problem and investigate it. Describe the reason why this happens. After discussing a solution this could also be implemented by a contributor.

**Comment by GauranshMathur** [comment]
Hi, I would like to be assigned to this issue.

I am a fresh grad and I'm looking at opportunities that can help me better learn coding in linux systems and also be able to work on my python skills. I found this issue via good first issues tag on github.

I also saw that I can be mentored for this project which would be helpful.

I have read the contributions.md but am currently having a problem running the created qt4 deb file to be able to test the system, I have been able to complete the steps before that

**Comment by aryoda** [comment]
> Hi, I would like to be assigned to this issue.

Welcome @GauranshMathur - we can need your help and there is still so much work to do :-)

> I have read the contributions.md but am currently having a problem running the created qt4 deb file 

Could you please describe in which of the steps described in [CONTRIBUTING.md](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md) you are creating a qt4 deb file since seems outdated by far (we are using Qt6 now and do no longer support building a `deb` file anymore - this is done by distro maintainers only now).

Normally you just have to create run config in your prefered IDE (in my case: PyCharm Community Edition) and execute the file `backintime/qt/app.py` to start the GUI via the IDE - there is no need to install the dev version during development, an installed older version of BiT is enough (to have a running D-Bus service required for some operations - mainly cron-related)...

**Comment by GauranshMathur** [comment]
Hi @aryoda the part in the readme where to be able to contribute it asks to build a Deb file before testing is where this issue stems. So I was following those steps to be able to recreate the issue.

As you say you are on qt6, I may believe these instructions are old so I may need some assistance with the current method of building and testing.

**Comment by aryoda** [comment]
> Hi @aryoda the part in the readme where to be able to contribute it asks to build a Deb file before testing is where this issue stems. So I was following those steps to be able to recreate the issue.

THX, now I have discovered [this part too](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build-own-deb-file) and yes, it is outdated - we need to remove it (it even was not generic enough since other distros may require other installation packages than `deb`).

> As you say you are on qt6, I may believe these instructions are old so I may need some assistance with the current method of building and testing.

Basically you need to
- install BiT from your distro to get most of the dependencies installed on your system
- install all missing further dependencies (as described in the [`contributing.md`](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#dependencies))
- build via `make` as [described in this section](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build-and-install-via-make-system-recommended) - but do **not** execute the `sudo make install` commands since you already have an installed version
- if the unit tests (`make test`) did succeed without errors (skips are allowed due to missing infrastructure like `ssh`) you can use your Python IDE of choice to start debugging by executing `backintime/qt/app.py` (add `--debug` as argument if you want to see more logging details in the console while running BiT in the IDE.)

If some unit tests fail it is most probably due to missing dependencies (Python packages etc.) and I will help you if this happens (I need your distro name + version and the error message of the unit test for this)...

**Comment by aryoda** [comment]
@GauranshMathur BTW: If `PyQt6` is not yet available as distro package you can manually install it following [these instructions](https://github.com/bit-team/backintime/pull/1632#issuecomment-1953131378) (possible with some modifications if you are not using Ubuntu 22.04).

**Comment by GauranshMathur** [comment]
Hi, @aryoda ,

I was able to use your method via the PR work and am able to now run the program in debug mode in qt6, thanks for the tip. But i am having an issue with trying to recreate the problem. 

I believe the steps to recreate the problem would be :

1. Run app.py in qt folder via the --debug tag
2. Create a local snapshot that you load 
3. Do the following stated steps above to quickly create a snapshot stop restart and pause to see the issue

But I am having an issue on step 2 where this is the debug message I was getting:

`DEBUG: [common/config.py:1689 Config._cron_line] Profile: test | Automatic backup: 0
cron_lines=['@reboot /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /home/arkhaya/work/backintime/common/backintime --debug backup-job >/dev/null', '']
Traceback (most recent call last):
  File "/home/arkhaya/work/backintime/qt/settingsdialog.py", line 2355, in accept
    if self.validate():
  File "/home/arkhaya/work/backintime/qt/settingsdialog.py", line 2001, in validate
    if not self.config.setupCron():
  File "/home/arkhaya/work/backintime/common/config.py", line 1629, in setupCron
    crontab_lines = schedule.append_bit_to_crontab(
TypeError: append_bit_to_crontab() missing 1 required positional argument: 'bit_lines'
 `

**Comment by buhtz** [comment]
That was a Bug introduced by me. But is fixes by a PR I merged yesterday. So just get the latest state from this upstream repo.

*EDIT*: And be aware that it need to be a slow machine, like a RasperryPi. I am assuming that the bug is not reproducible on a machine with regular performance.

**Comment by GauranshMathur** [comment]
Thanks @buhtz I was able to successfully run the app.py in debug mode.

And yes from what i have checked, I am unable to recreate the bug on my system. But based on the given images provided I believe the issue stems from the problem that because the raspberry pi is much slower when pressing the snapshot button again and pausing it, it leads to a crash as it will try to run another process while the prior one is still running.

**Comment by Ajeem-git** [comment]
I am taking a look at this issue.

The crash path appears to be the pause/resume/stop actions calling `os.kill(self.snapshots.pid(), ...)` after the snapshot process has already disappeared on slower systems. I am testing a small defensive fix that routes those signals through one guarded helper so the GUI refreshes state instead of crashing with `ProcessLookupError`.

**Comment by Ajeem-git** [comment]
I opened a PR for this here: #2457

The change routes pause / resume / stop through a guarded helper and refreshes the GUI state if the snapshot PID has already disappeared, which avoids the `ProcessLookupError` crash on slower systems.

**Comment by MasterOfFeelingFish** [comment]
I've been looking into this. The race condition is between the stop button sending SIGSTOP to a process that may have already exited. The fix should guard os.kill(self.snapshots.pid(), signal.SIGSTOP) with a try/except for ProcessLookupError. Happy to submit a patch.

**Comment by buhtz** [comment]
Hello @MasterOfFeelingFish ,
I wonder why you open a PR #2469 to fix this issue. Didn't you read the whole thread before and saw that Ajeem-git still opened a PR #2457. You disrespect his work and efforts. Didn't your AI-imitating claws-bot told you that?

Give me a good reason why I should prefer your solution in PR #2469 of the PR #2457?

**Comment by buhtz** [comment]
> I've been looking into this.

No you have not.

Reported you to the MS abuse team because of several violations, not only regarding this issue.
