### ISSUE TITLE
Backintime CLI: blocked by systrayiconplugin.py (run via sudo at headless server)

### ISSUE THREAD

**Issue by diwaffm** [bit-team/backintime#1677]
Hi!
I'm using BackInTime V1.4.1-3.2 (openSuSe).

Since I'm not in front of the computer, I'm checking the Backup via SSH / console.
Finding, that the last backup happend back in mid february, I wanted to dive in deeper.
The last backup was successfully created and the log is showing this.
But that's all for this profile (as well as for the other 2)

```
[I] Schnappschuss erstellen (rsync: sent 94,65G bytes  received 40,05K bytes  105,93M bytes/sec)
[I] Schnappschuss erstellen (rsync: total size is 1,22T  speedup is 12,94)
[I] 'rsync' beendet mit Code 0: Erfolgreich
[I] Konfigurationsdatei wird gespeichert …
[I] Zugriffsrechte werden gespeichert …
[I] Intelligentes Löschen
[I] Das Minimum an freiem Speicher wird freigehalten
[I] Finalisierung läuft
```

So I wanted to start BackInTime manually:
` sudo backintime --profile EMKGHEU01 backup --debug`

This gives me
```
DEBUG: [common/backintime.py:589 argParse] Arguments: {'debug': True, 'profile': 'EMKGHEU01', 'command': 'backup', 'func': <function backup at 0x7f1eeb5e07c0>} | unknownArgs: []

Back In Time
Version: 1.4.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Hauptprofil
DEBUG: [common/tools.py:174 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/backintime.py:677 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:678 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:679 getConfig] profiles: 1=Hauptprofil, 2=Ext_HDD, 3=EMKGHEU01
DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 3=EMKGHEU01
DEBUG: [common/pluginmanager.py:245 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin notifyplugin.py
```

Since nothin happens here any further, I  wanted to cancel the backup and 2 more lines were shown:
```
^CERROR: [common/pluginmanager.py:271 PluginManager.load] Failed to load plugin systrayiconplugin.py: 
INFO: [common/snapshots.py:729 Snapshots.backup] Lock
```

Assuming, the backup process is starting now (since a lot of phython processes were running), I left the programm running over night - but nothing happens.
No further infos her nor at syslog.

Any Ideas?

Thanks

dirk

```
backintime --diagnostics
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1190, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 507, in startApp
    args = argParse(None)
           ^^^^^^^^^^^^^^
  File "/usr/share/backintime/common/backintime.py", line 568, in argParse
    args, unknownArgs = mainParser.parse_known_args(args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/share/backintime/common/backintime.py", line 742, in __call__
    diagnostics = collect_diagnostics()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/common/diagnostics.py", line 74, in collect_diagnostics
    'OS': _get_os_release()
          ^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/common/diagnostics.py", line 398, in _get_os_release
    return osrelease['os-release']
           ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'os-release'
```

**Comment by buhtz** [comment]
Hello diwaffm,
Thanks for your report.

The `KeyError` triggered by `--diagnostics` is a known error that should be fixed in the latest version. Just ignore it.

To your primary problem: I assume that the `systrayiconplugin.py` is involved here. But I am not to much into its details. Other team mates (aryoda) are and they will answer here as soon as they can. It will take some time because we are in a holiday period.

I would suggest to update to the latest version 1.4.3 and try again. In the [changlog](https://github.com/bit-team/backintime/releases/tag/v1.4.3) of that version you can see that there are some modifications related to that component.

Best,
Christian

**Comment by diwaffm** [comment]
Hi buhtz,

thanks for you answer.
Then, I have to wait, until the new version is included by Suse...

Ciao
Dirk

**Comment by ptilopteri** [comment]
backintime-1.4.1-91.1.noarch
from Productivity/Archiving/Backup
   https://download.opensuse.org/repositories/Archiving:/Backup/openSUSE_Tumbleweed/noarch/backintime-1.4.1-91.2.noarch.rpm

works for me on Tumbleweed
should also work on leap 15.4,15.5

**Comment by buhtz** [comment]
> backintime-1.4.1-91.1.noarch from Productivity/Archiving/Backup 
> [..]
> works for me on Tumbleweed should also work on leap 15.4,15.5

Thanks for reporting. Then it seems to be a more complex problem. "aryoda" will jump in but not so soon I guess.

**Comment by diwaffm** [comment]
> backintime-1.4.1-91.1.noarch from Productivity/Archiving/Backup https://download.opensuse.org/repositories/Archiving:/Backup/openSUSE_Tumbleweed/noarch/backintime-1.4.1-91.2.noarch.rpm
> 
> works for me on Tumbleweed should also work on leap 15.4,15.5

Thanks for the link and the info!
I installed this now, and I still have to skip 
`DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin notifyplugin.py`
by pressing CTRL-C.
But now, the backup seems to be running, rsync is called.

I will see, if it finishes successfully - but so far, it seems to be working.

Ciao
Dirk

**Comment by buhtz** [comment]
Thanks for checking out.
Please do not hesitate to remind us of this bug if you do not receive any further response within the next few weeks.

**Comment by diwaffm** [comment]
The manually initiated backup has now been successfully completed.

However, I made the observation - which I do not know whether it is specifically related to this - that the phython process remained active after the backup.
After several tasks (displaying the snapshots / deleting a snapshot / etc), over 10 of these processes were listed - and BIT only performed new tasks after all python3 processes were terminated.
Is it possible to display the currently running tasks via the console?

Ciao

Dirk

**Comment by buhtz** [comment]
Sounds serious. Something is hanging or blocking in the back.
You could use `htop` or `ps -A | grep python` to see what is going on maybe.

**Comment by diwaffm** [comment]
This is, where I found the open processes, but I don't know, why this happens - and my knowledge at Linux may not be good enough to dig in deeper...

```
ServerOF:~/.local/share/backintime # ps -A |grep python
 3086 ?        00:24:31 python3
 6029 ?        00:06:40 python3
 6030 ?        00:18:49 python3
 6041 pts/7    00:18:05 python3
 6076 pts/7    00:00:00 python3
 6079 pts/7    00:17:44 python3
15118 ?        00:13:44 python3
31724 ?        00:00:00 python3
```
```
top - 11:42:07 up 47 days,  1:13,  5 users,  load average: 5,32, 5,03, 5,04
Tasks: 349 total,   2 running, 346 sleeping,   0 stopped,   1 zombie
%CPU(s): 12,0 us, 11,4 sy,  2,1 ni, 63,9 id, 10,7 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Spch: 31902,66+total,  257,840 free, 29166,13+used, 2969,922 buff/cache
MiB Swap: 3779,000 total,    0,000 free, 3779,000 used. 2736,527 avail Spch

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     ZEIT+ BEFEHL                                                                                                                                                                                                                 
 6079 root      20   0  190872  29568  14848 S 18,54 0,091  18:20.78 python3                                                                                                                                                                                                                
 6030 root      39  19  190856  30560  13920 S 18,21 0,094  19:27.10 python3                                                                                                                                                                                                                
 6041 root      20   0  190872  26880  14080 S 17,55 0,082  18:42.03 python3                                                                                                                                                                                                                
 6029 root      39  19 5243292 4,975g   3328 S 5,960 15,97   6:53.56 python3                                                                                                                                                                                                                
 3086 root      39  19 14,741g 0,013t   3712 S 0,000 43,47  24:31.85 python3                                                                                                                                                                                                                
 6076 root      20   0   36928  25020   7296 S 0,000 0,077   0:00.52 python3                                                                                                                                                                                                                
15118 root      39  19 8468028 7,146g   3456 S 0,000 22,94  13:44.76 python3                                                                                                                                                                                                                
31724 root      20   0   73808  17504   8064 S 0,000 0,054   0:00.06 python3    
```

**Comment by buhtz** [comment]
I discovered in your initial post how you start BIT:

    sudo backintime --profile EMKGHEU01 backup --debug

BIT is not intended to be started via sudo. We have another related issue to this #1683 and think about how to improve the error message in case BIT is started via "sudo".

But I am not sure if "sudo" is the reason for your problem.

Please tell us more about your snapshot profile `EMKGHEU01`. Does it backup user files or root files?
Assuming you configured `EMKGHEU01` via the GUI, how did you start that GUI?

**Comment by buhtz** [comment]
Hello diwaffm,
is this issue still relevant for you?

1. Can you reproduce the error in newer versions?
2. Can you reproduce the error **without using** `sudo`? Maybe run it as real root.

**Comment by buhtz** [comment]
Without any feedback I have no other choice to close the issue.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian
