### ISSUE TITLE
`backintime --diagnostics` not working

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1716]
To help us diagnose the problem quickly, please provide the output of the console command `backintime --diagnostics`.

I was trying to find the cause why BiT stopped working three days ago and the manual backups result in a brief `Working ...`, then `Done` (no issue created yet for this) with `--diagnostics`, but it throws an error: 

```
localhost# backintime --diagnostics
Traceback (most recent call last):
File "/usr/share/backintime/common/backintime.py", line 1190, in <module>
startApp()
File "/usr/share/backintime/common/backintime.py", line 507, in startApp
args = argParse(None)
^^^^^^^^^^^^^^
File "/usr/share/backintime/common/backintime.py", line 568, in argParse
args, unknownArgs = mainParser.parse_known_args(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 1907, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 2128, in _parse_known_args
start_index = consume_optional(start_index)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 2068, in consume_optional
take_action(action, args, option_string)
File "/usr/lib64/python3.11/argparse.py", line 1983, in take_action
action(self, namespace, argument_values, option_string)
File "/usr/share/backintime/common/backintime.py", line 742, in __call__
diagnostics = collect_diagnostics()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/backintime/common/diagnostics.py", line 74, in collect_diagnostics
'OS': _get_os_release()
^^^^^^^^^^^^^^^^^
File "/usr/share/backintime/common/diagnostics.py", line 398, in _get_os_release
return osrelease['os-release']
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'os-release'
```

**Comment by buhtz** [comment]
Hello noyannus,

Thank you for taking the time to report the bug. This is fixed via #1703 and available in `dev`  branch. It is not released yet.

Closing this ticket based on the comment above. Feel free to reopen if I am mistaken.

Please also feel free to open a new issue with your original problem. Just mention your system details (backintime version, OS, etc pp).

Best regards,
Chrsitian

**Comment by noyannus** [comment]
Wow, that was fast! Thank you. 

Installed the curren version and had to change the owner of `/run/user/1002 ` to `root`, and now `--diagnostics` runs without error.

**Comment by buhtz** [comment]
What is /run/user/1002 ? I am confused.

**Comment by noyannus** [comment]
`running backintime --diagnostics` complained with an error that this directory had the wrong group. It was set to my regular user (aiui that is how it usually should be --?). I changed it to `root:root`; maybe the problem came from running as sudo-?  Anyway, BiT (1.4.3) is doing backups now, started from Konsole.

All I know about these `/run/user/` directories is from [here](https://unix.stackexchange.com/a/162911).
