### ISSUE TITLE
ModuleNotFoundError: No module named 'schedule'

### ISSUE THREAD

**Issue by fallingrock** [bit-team/backintime#1763]
After a recent update, I'm getting this error when bit is run from chron.

```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 32, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 55, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'
```

Appears to be related to #1747 

Ran `apt install python3-schedule` and error appears to have been fixed.

Running version 1.4.4-dev.ba1ff787

**Comment by fallingrock** [comment]
Did not run configure.
