### ISSUE TITLE
AttributeError: module 'tools' has no attribute 'set_lc_time_by_language_code'

### ISSUE THREAD

**Issue by fallingrock** [bit-team/backintime#1764]
After resolving #1763, I tried running `backintime-qt` and got the following error:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 2039, in <module>
    translator = qttools.initiate_translator(cfg.language())
  File "/usr/share/backintime/qt/qttools.py", line 370, in initiate_translator
    tools.set_lc_time_by_language_code(language_code)
AttributeError: module 'tools' has no attribute 'set_lc_time_by_language_code'
```

Appears to be related to #1730

**Comment by fallingrock** [comment]
Forgot to run configure before installing
