### ISSUE TITLE
TypeError: append_bit_to_crontab() missing 1 required positional argument: 'bit_lines'

### ISSUE THREAD

**Issue by fallingrock** [bit-team/backintime#1765]
When launching, or changing settings, the following error appears:

```
profile_ids=['1']
cron_lines=['']
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 2016, in run
    self.config.setupCron()
  File "/usr/share/backintime/common/config.py", line 1629, in setupCron
    crontab_lines = schedule.append_bit_to_crontab(
TypeError: append_bit_to_crontab() missing 1 required positional argument: 'bit_lines'
```

Appears to be related to #1747

**Comment by buhtz** [comment]
Yeah, this was my fault. Fixed in pending PR #1761.
