### ISSUE TITLE
Release tarball misses files - backintime 1.5.0

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#1812]
I was trying to build the most recent backintime, but I think there are files missing from the tarball.

```
install --mode=644 po/ar.mo /builddir/build/BUILDROOT/backintime-1.5.0-1.fc40.x86_64/usr/share/locale/ar/LC_MESSAGES/backintime.mo
# Inject version string into source files
(cd .. && ./updateversion.sh)
/bin/sh: line 1: ./updateversion.sh: No such file or directory
make: *** [Makefile:20: install] Error 127
make: Leaving directory '/builddir/build/BUILD/backintime-1.5.0/common'
error: Bad exit status from /var/tmp/rpm-tmp.NCneks (%install)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.NCneks (%install)
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 53e110f3728c4388aad6341e0561daa5 -D /var/lib/mock/fedora-40-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv._9efyb9c:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin \'--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"\' \'--setenv=PS1=<mock-chroot> \\s-\\v\\$ \' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c \'/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/backintime.spec\'\n', 1)]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mockbuild/util.py", line 612, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (cmd_pretty(command, env), output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 53e110f3728c4388aad6341e0561daa5 -D /var/lib/mock/fedora-40-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv._9efyb9c:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/backintime.spec'
```

However, when checking the tarball it's missing all the sh and py files in the root directory. Are they created by configure? Then I would probably need to adjust the flags.
![image](https://github.com/user-attachments/assets/78ed50ec-e7c3-4630-923d-fe79ca66dbf3)

**Comment by buhtz** [comment]
A crowdstrike moment... Have not tested the tarball itself, just the git repo. I am on it

**Comment by hannes101** [comment]
Don't be too hard on yourself. I think it's just missing updateversion.sh with chmod +x :)

**Comment by buhtz** [comment]
Good morning Johannes,
thank you very much for reporting this.

I attached a new tarball to the release. Let me know how it goes.

**Comment by hannes101** [comment]
Yes, this one works now as expected. Just getting errors later during the tests.
