### ISSUE TITLE
Error when clicking on the backintime-qt as root configuration/profile button

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#1828]
Error when clicking on the backintime-qt 1.5.1 configuration/profile button:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1347, in btnSettingsClicked
    settingsdialog.SettingsDialog(self).show()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/settingsdialog.py", line 641, in __init__
    "unpredictable in this mode due to encryption by EncFS.").format(
                                                              ^^^^^^^
ValueError: Single '}' encountered in format string
/usr/bin/backintime-qt: línea 31: 13212 Abortado                (`core' generado) /usr/bin/python -Es ${APP_PATH}/app.py "$@"
```

I have also installed encfs but nothing works 

Manjaro Linux x86_64   Kernel: Linux 6.9.12-1

**Comment by buhtz** [comment]
Hello Caramelitosis,
Thank you very much for reporting.

I am not able to reproduce it yet. Can you give me more details about the steps to reproduce please.

- Please post the output of `backintime --debug`.
- What operating system and version is it?
- How and from where do you installed BIT?

Thanks
Christian

Currently I don't see what could have caused that error. The code looks fine to me and also works.

https://github.com/bit-team/backintime/blob/cd59ea13ae063a11b52e6a8892bb583e13a53136/qt/settingsdialog.py#L636-L651

**Comment by buhtz** [comment]
What language are you using here?
There might be a problem with one of the translated strings. I am checking.

EDIT:

Spanish I think. There are too many `}` in the translated string.
![image](https://github.com/user-attachments/assets/9caf2553-4d6b-4ebe-b06d-7ae57dbb26d3)

**Comment by emtiu** [comment]
Yes, my guess would have been 80% confidence for Spanish, otherwise Portuguese :)

**Comment by buhtz** [comment]
I am working on a fix and also improving the language script to detect problems like this.

**Comment by ghost** [comment]
For fear of corrupting my backups, I have installed on another computer backintime 1.5.1 in manjaro testing:

```
OS: Manjaro Linux x86_64 [testing]
Kernel: Linux 6.6.44-1-MANJARO
DE: KDE Plasma 6.0.5
WM: KWin (X11)
WM Theme: Brisa
Terminal: lxterminal 0.4.0
CPU: Intel(R) Core(TM)2 Quad Q9450 (4) @ 2,66 GHz
GPU: NVIDIA GeForce GT 1030 [Discrete]
Memory: 1,88 GiB / 7,76 GiB (24%)
Swap: Disabled
Locale: es_ES.UTF-8

`````
`````
backintime --debug     
DEBUG: [common/backintime.py:613 argParse] Used argument(s): {'debug': True, 'quiet': False}
DEBUG: [common/backintime.py:614 argParse] Unknown argument(s): []
DEBUG: [common/backintime.py:513 startApp] backintime: {'name': 'Back In Time', 'version': '1.5.1', 'running-as-root': False}
DEBUG: [common/backintime.py:513 startApp] host-setup: {'OS': {'/etc/os-release': 'Manjaro Linux', '/etc/lsb-release': 'DISTRIB_ID="ManjaroLinux"\nDISTRIB_RELEASE="24.0.5"\nDISTRIB_CODENAME="Wynsdey"\nDISTRIB_DESCRIPTION="Manjaro Linux"\n', '/etc/arch-release': 'Manjaro Linux\n', '/etc/manjaro-release': 'Manjaro Linux\n'}}

Back In Time
Version: 1.5.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Perfil principal
DEBUG: [common/tools.py:225 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/tools.py:274 set_lc_time_by_language_code] Try to set locale.LC_TIME to "es_ES.UTF-8" based on language code "es".
DEBUG: [common/backintime.py:696 getConfig] config file: /home/filtered/.config/backintime/config
DEBUG: [common/backintime.py:697 getConfig] share path: /home/filtered/.local/share/backintime
DEBUG: [common/backintime.py:698 getConfig] profiles: 1=Perfil principal

`````


`````
backintime-qt --debug  
DEBUG: [common/backintime.py:613 argParse] Used argument(s): {'debug': True, 'quiet': False}
DEBUG: [common/backintime.py:614 argParse] Unknown argument(s): []
DEBUG: [common/backintime.py:513 startApp] backintime: {'name': 'Back In Time', 'version': '1.5.1', 'running-as-root': False}
DEBUG: [common/backintime.py:513 startApp] host-setup: {'OS': {'/etc/os-release': 'Manjaro Linux', '/etc/lsb-release': 'DISTRIB_ID="ManjaroLinux"\nDISTRIB_RELEASE="24.0.5"\nDISTRIB_CODENAME="Wynsdey"\nDISTRIB_DESCRIPTION="Manjaro Linux"\n', '/etc/arch-release': 'Manjaro Linux\n', '/etc/manjaro-release': 'Manjaro Linux\n'}}

Back In Time
Version: 1.5.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Perfil principal
DEBUG: [common/tools.py:225 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/tools.py:274 set_lc_time_by_language_code] Try to set locale.LC_TIME to "es_ES.UTF-8" based on language code "es".
DEBUG: [common/backintime.py:696 getConfig] config file: /home/filtered/.config/backintime/config
DEBUG: [common/backintime.py:697 getConfig] share path: /home/filtered/.local/share/backintime
DEBUG: [common/backintime.py:698 getConfig] profiles: 1=Perfil principal
DEBUG: [common/pluginmanager.py:247 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:268 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin systrayiconplugin.py
DEBUG: [common/tools.py:853 is_Qt_working] Qt probing result: exit code 2
DEBUG: [common/tools.py:856 is_Qt_working] Qt probing stdout:

DEBUG: [common/tools.py:857 is_Qt_working] Qt probing errout:
DEBUG: [common/qt_probing.py:89 <module>] /usr/share/backintime/common/qt_probing.py started... Call args: ['/usr/share/backintime/common/qt_probing.py', '--debug']
DEBUG: [common/qt_probing.py:90 <module>] Display system: x11
DEBUG: [common/qt_probing.py:91 <module>] XDG_RUNTIME_DIR=/run/user/1000
DEBUG: [common/qt_probing.py:92 <module>] XAUTHORITY=($XAUTHORITY is not set)
DEBUG: [common/qt_probing.py:93 <module>] QT_QPA_PLATFORM=($QT_QPA_PLATFORM is not set)
DEBUG: [common/qt_probing.py:95 <module>] Current euid: 1000
QSettings::value: Empty key passed
DEBUG: [common/qt_probing.py:126 <module>] isSystemTrayAvailable for Qt: True
DEBUG: [common/qt_probing.py:131 <module>] /usr/share/backintime/common/qt_probing.py is terminating normally (exit code: 2)

DEBUG: [plugins/systrayiconplugin.py:74 init] System tray is available to show the BiT system tray icon
DEBUG: [common/pluginmanager.py:268 PluginManager.load] Add plugin systrayiconplugin.py
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin usercallbackplugin.py
DEBUG: [qt/qttools.py:284 createQApplication] QT QPA platform plugin: xcb
DEBUG: [qt/qttools.py:285 createQApplication] QT_QPA_PLATFORMTHEME=<not set>
DEBUG: [qt/qttools.py:290 createQApplication] QT_STYLE_OVERRIDE=<not set>
DEBUG: [qt/qttools.py:293 createQApplication] QT active style: breeze
DEBUG: [qt/qttools.py:294 createQApplication] QT fallback style: breeze
DEBUG: [qt/qttools.py:295 createQApplication] QT supported styles: ['qt5ct-style', 'qt6ct-style', 'Oxygen', 'kvantum-dark', 'kvantum', 'Breeze', 'Windows', 'Fusion']
DEBUG: [qt/qttools.py:296 createQApplication] themeSearchPaths: ['/home/filtered/.local/share/icons', '/var/lib/flatpak/exports/share/icons', '/usr/share/icons', '/home/filtered/.icons', ':/icons']
DEBUG: [qt/qttools.py:297 createQApplication] fallbackSearchPaths: []
DEBUG: [qt/qttools.py:302 createQApplication] Is SystemTray available: True
DEBUG: [qt/qttools.py:319 createQApplication] Trying to set App ID for non-privileged user
DEBUG: [qt/qttools.py:359 initiate_translator] No language code. Use systems current locale.
DEBUG: [common/tools.py:274 set_lc_time_by_language_code] Try to set locale.LC_TIME to "es_ES.UTF-8" based on language code "es_ES".
DEBUG: [qt/icon.py:20 <module>] Checking if the current theme contains the BiT icon...
DEBUG: [qt/icon.py:32 <module>] Found an installed theme: Fluent
DEBUG: [common/tools.py:1271 keyringSupported] Keyring config file folder: /home/filtered/.config/python_keyring
DEBUG: [common/tools.py:1285 keyringSupported] Available keyring backends:
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.chainer.ChainerBackend (priority: -1)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.kwallet.DBusKeyring (priority: 5.1)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.fail.Keyring (priority: 0)
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.Gnome.Keyring not found: AttributeError("module 'keyring.backends' has no attribute 'Gnome'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.kwallet.Keyring not found: AttributeError("module 'keyring.backends.kwallet' has no attribute 'Keyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.SecretServiceKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'SecretServiceKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.GnomeKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'GnomeKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.KDEWallet not found: AttributeError("module 'keyring.backend' has no attribute 'KDEWallet'")
DEBUG: [common/tools.py:1339 keyringSupported] Available supported backends: [<class 'keyring.backends.SecretService.Keyring'>, <class 'keyring.backends.kwallet.DBusKeyring'>, <class 'keyring.backends.chainer.ChainerBackend'>]
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.kwallet'
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 2076, in <module>
    mainWindow = MainWindow(cfg, appInstance, qapp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/app.py", line 354, in __init__
    settingsdialog.SettingsDialog(self).exec()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/settingsdialog.py", line 641, in __init__
    "unpredictable in this mode due to encryption by EncFS.").format(
                                                              ^^^^^^^
ValueError: Single '}' encountered in format string

`````

**Comment by ghost** [comment]
Indeed it seems to be the translation, the error does not occur:
```
LANG= LC_ALL= backintime-qt 

Back In Time
Version: 1.5.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

WARNING: PyQt was not able to install a translator for language code "C". Deactivate translation and falling back to the source language (English).
/sbin/backintime-qt: line 31: 10536 Segmentation fault      (core dumped) /usr/bin/python -Es ${APP_PATH}/app.py "$@"

```

* A different error occurs (core dumped) which does not prevent the application from running smoothly, shall I open another thread?

**Comment by buhtz** [comment]
> ```
> WARNING: PyQt was not able to install a translator for language code "C". Deactivate translation and falling back to the source language (English).
> /sbin/backintime-qt: line 31: 10536 Segmentation fault      (core dumped) /usr/bin/python -Es ${APP_PATH}/app.py "$@"
> ```
> 
> * A different error occurs (core dumped) which does not prevent the application from running smoothly, shall I open another thread?

The "WARNING" is not a problem but expected. But the "Segmentation fault" is interesting. Can you reproduce it?

**Comment by ghost** [comment]
In a new installation without any profile defined, when the window to create a new profile appears but you close it with the cancel button without creating any profile, it happens about 50% of the time:

```
OS: Manjaro Linux x86_64 [testing]
Kernel: Linux 6.6.44-1-MANJARO
DE: KDE Plasma 6.0.5
WM: KWin (X11)
WM Theme: Brisa
Terminal: lxterminal 0.4.0
CPU: Intel(R) Core(TM)2 Quad Q9450 (4) @ 2,66 GHz
GPU: NVIDIA GeForce GT 1030 [Discrete]
Memory: 1,88 GiB / 7,76 GiB (24%)
Swap: Disabled
Locale: es_ES.UTF-8

LANG=EN backintime-qt --debug                                                                  ✔ 
DEBUG: [common/backintime.py:613 argParse] Used argument(s): {'debug': True, 'quiet': False}
DEBUG: [common/backintime.py:614 argParse] Unknown argument(s): []
DEBUG: [common/backintime.py:513 startApp] backintime: {'name': 'Back In Time', 'version': '1.5.1', 'running-as-root': False}
DEBUG: [common/backintime.py:513 startApp] host-setup: {'OS': {'/etc/os-release': 'Manjaro Linux', '/etc/lsb-release': 'DISTRIB_ID="ManjaroLinux"\nDISTRIB_RELEASE="24.0.5"\nDISTRIB_CODENAME="Wynsdey"\nDISTRIB_DESCRIPTION="Manjaro Linux"\n', '/etc/arch-release': 'Manjaro Linux\n', '/etc/manjaro-release': 'Manjaro Linux\n'}}

Back In Time
Version: 1.5.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Main profile
DEBUG: [common/tools.py:225 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/tools.py:274 set_lc_time_by_language_code] Try to set locale.LC_TIME to "en_US.UTF-8" based on language code "en".
DEBUG: [common/backintime.py:696 getConfig] config file: /home/filtered/.config/backintime/config
DEBUG: [common/backintime.py:697 getConfig] share path: /home/filtered/.local/share/backintime
DEBUG: [common/backintime.py:698 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:247 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:268 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin systrayiconplugin.py
DEBUG: [common/tools.py:853 is_Qt_working] Qt probing result: exit code 2
DEBUG: [common/tools.py:856 is_Qt_working] Qt probing stdout:

DEBUG: [common/tools.py:857 is_Qt_working] Qt probing errout:
DEBUG: [common/qt_probing.py:89 <module>] /usr/share/backintime/common/qt_probing.py started... Call args: ['/usr/share/backintime/common/qt_probing.py', '--debug']
DEBUG: [common/qt_probing.py:90 <module>] Display system: x11
DEBUG: [common/qt_probing.py:91 <module>] XDG_RUNTIME_DIR=/run/user/1000
DEBUG: [common/qt_probing.py:92 <module>] XAUTHORITY=($XAUTHORITY is not set)
DEBUG: [common/qt_probing.py:93 <module>] QT_QPA_PLATFORM=($QT_QPA_PLATFORM is not set)
DEBUG: [common/qt_probing.py:95 <module>] Current euid: 1000
QSettings::value: Empty key passed
DEBUG: [common/qt_probing.py:126 <module>] isSystemTrayAvailable for Qt: True
DEBUG: [common/qt_probing.py:131 <module>] /usr/share/backintime/common/qt_probing.py is terminating normally (exit code: 2)

DEBUG: [plugins/systrayiconplugin.py:74 init] System tray is available to show the BiT system tray icon
DEBUG: [common/pluginmanager.py:268 PluginManager.load] Add plugin systrayiconplugin.py
DEBUG: [common/pluginmanager.py:253 PluginManager.load] Probing plugin usercallbackplugin.py
DEBUG: [qt/qttools.py:284 createQApplication] QT QPA platform plugin: xcb
DEBUG: [qt/qttools.py:285 createQApplication] QT_QPA_PLATFORMTHEME=<not set>
DEBUG: [qt/qttools.py:290 createQApplication] QT_STYLE_OVERRIDE=<not set>
DEBUG: [qt/qttools.py:293 createQApplication] QT active style: breeze
DEBUG: [qt/qttools.py:294 createQApplication] QT fallback style: breeze
DEBUG: [qt/qttools.py:295 createQApplication] QT supported styles: ['qt5ct-style', 'qt6ct-style', 'Oxygen', 'kvantum-dark', 'kvantum', 'Breeze', 'Windows', 'Fusion']
DEBUG: [qt/qttools.py:296 createQApplication] themeSearchPaths: ['/home/filtered/.local/share/icons', '/var/lib/flatpak/exports/share/icons', '/usr/share/icons', '/home/filtered/.icons', ':/icons']
DEBUG: [qt/qttools.py:297 createQApplication] fallbackSearchPaths: []
DEBUG: [qt/qttools.py:302 createQApplication] Is SystemTray available: True
DEBUG: [qt/qttools.py:319 createQApplication] Trying to set App ID for non-privileged user
DEBUG: [qt/qttools.py:359 initiate_translator] No language code. Use systems current locale.
DEBUG: [common/tools.py:274 set_lc_time_by_language_code] Try to set locale.LC_TIME to "en_US.UTF-8" based on language code "en_US".
DEBUG: [qt/icon.py:20 <module>] Checking if the current theme contains the BiT icon...
DEBUG: [qt/icon.py:32 <module>] Found an installed theme: Fluent
DEBUG: [common/tools.py:1271 keyringSupported] Keyring config file folder: /home/filtered/.config/python_keyring
DEBUG: [common/tools.py:1285 keyringSupported] Available keyring backends:
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.fail.Keyring (priority: 0)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.kwallet.DBusKeyring (priority: 5.1)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.chainer.ChainerBackend (priority: -1)
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.Gnome.Keyring not found: AttributeError("module 'keyring.backends' has no attribute 'Gnome'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.kwallet.Keyring not found: AttributeError("module 'keyring.backends.kwallet' has no attribute 'Keyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.SecretServiceKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'SecretServiceKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.GnomeKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'GnomeKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.KDEWallet not found: AttributeError("module 'keyring.backend' has no attribute 'KDEWallet'")
DEBUG: [common/tools.py:1339 keyringSupported] Available supported backends: [<class 'keyring.backends.SecretService.Keyring'>, <class 'keyring.backends.kwallet.DBusKeyring'>, <class 'keyring.backends.chainer.ChainerBackend'>]
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.kwallet'
DEBUG: [common/tools.py:1271 keyringSupported] Keyring config file folder: /home/filtered/.config/python_keyring
DEBUG: [common/tools.py:1285 keyringSupported] Available keyring backends:
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.fail.Keyring (priority: 0)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.kwallet.DBusKeyring (priority: 5.1)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.chainer.ChainerBackend (priority: -1)
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.Gnome.Keyring not found: AttributeError("module 'keyring.backends' has no attribute 'Gnome'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.kwallet.Keyring not found: AttributeError("module 'keyring.backends.kwallet' has no attribute 'Keyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.SecretServiceKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'SecretServiceKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.GnomeKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'GnomeKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.KDEWallet not found: AttributeError("module 'keyring.backend' has no attribute 'KDEWallet'")
DEBUG: [common/tools.py:1339 keyringSupported] Available supported backends: [<class 'keyring.backends.SecretService.Keyring'>, <class 'keyring.backends.kwallet.DBusKeyring'>, <class 'keyring.backends.chainer.ChainerBackend'>]
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.kwallet'
DEBUG: [common/tools.py:1271 keyringSupported] Keyring config file folder: /home/filtered/.config/python_keyring
DEBUG: [common/tools.py:1285 keyringSupported] Available keyring backends:
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.fail.Keyring (priority: 0)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.kwallet.DBusKeyring (priority: 5.1)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.chainer.ChainerBackend (priority: -1)
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.Gnome.Keyring not found: AttributeError("module 'keyring.backends' has no attribute 'Gnome'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.kwallet.Keyring not found: AttributeError("module 'keyring.backends.kwallet' has no attribute 'Keyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.SecretServiceKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'SecretServiceKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.GnomeKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'GnomeKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.KDEWallet not found: AttributeError("module 'keyring.backend' has no attribute 'KDEWallet'")
DEBUG: [common/tools.py:1339 keyringSupported] Available supported backends: [<class 'keyring.backends.SecretService.Keyring'>, <class 'keyring.backends.kwallet.DBusKeyring'>, <class 'keyring.backends.chainer.ChainerBackend'>]
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.kwallet'
DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Main profile
/sbin/backintime-qt: line 31: 11777 Segmentation fault      (core dumped) /usr/bin/python -Es ${APP_PATH}/app.py "$@"

```

**Comment by buhtz** [comment]
I can reproduce the problem, too. I reopen #1095 and report details there.
