### ISSUE TITLE
Bump numpy depedency

### ISSUE THREAD

**Issue by clin1234** [bit-team/backintime#1969]
Attempting to install from pip yields the following error:
```
Collecting numpy==1.22.2 (from backintime)
  Using cached numpy-1.22.2.zip (11.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/home/cc/venv/lib64/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/cc/venv/lib64/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cc/venv/lib64/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/home/cc/venv/lib64/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "/usr/lib64/python3.14t/importlib/__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1386, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1359, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1309, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1386, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1359, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1330, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 756, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-t8sg5wz9/overlay/lib/python3.14t/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-t8sg5wz9/overlay/lib/python3.14t/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-t8sg5wz9/overlay/lib/python3.14t/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Ideally, the numpy version should be bumped to the latest 1.x version (1.26.4) as a temporary step, then upgraded to the maintained 2.x branch

**Comment by buhtz** [comment]
Hello,

are you referring to this project?

https://pypi.org/project/backintime/

This is not related to the current upstream repo you reported to. "Back In Time" is not present at pypi.

Please contact the projects upstream maintainer: https://github.com/akim-mukhtarov

Regards,
Christian
