### ISSUE TITLE
failure to backup -> everything is sunshine

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#21]
1)
$ lsb_release -rd
Description:    Ubuntu 9.10
Release:        9.10

2)
$ dpkg -s backintime-kde | grep Version
Version: 0.9.26-3

3)
I expected that I see an error message when backintime fails to do a backup

4)
Instead due to me bumping into the external drive, the filesystem went read-only,
but no message in the GUI whatsoever though. No sign there that anything broke.

It looks like everything would be sunshine only. Even though the backup failed
and is broken.

On the command line this looks like this - however a click-to-start user will never
see that:

rsync: recv_generator: mkdir "/media/B/backup/backintime/new_snapshot/backup/mnt/mhddfs/home/tpo/tpo2_snapshot" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1057) [sender=3.0.6]
WARNING: Command "rsync -aEAX  -v --delete-excluded  --chmod=Fa-w,D+w --whole-file --delete  --exclude="/media/B/backup" --exclude="/home/tpo/.local/share/backintime" --include="/home/tpo/" --include="/home/" --include="/mnt/mhddfs/home/" --include="/mnt/mhddfs/" --include="/mnt/" --exclude=".*" --exclude="*.backup*" --exclude="*~" --exclude="/home/tpo/multimedia/25c3-2" --exclude="/home/tpo/panter/dental" --exclude="/mnt/mhddfs/home/tpo/multimedia/25c3-2" --include="/home/tpo/**" --include="/mnt/mhddfs/home/**" --exclude="*" / "/media/B/backup/backintime/new_snapshot/backup/"" returns 5888
INFO: Save permissions
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 174, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 86, in start_app
    take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 42, in take_snapshot
    snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 424, in take_snapshot
    ret_val = self._take_snapshot( snapshot_id, now, include_folders, ignore_folders, dict, force )
  File "/usr/share/backintime/common/snapshots.py", line 685, in _take_snapshot
    fileinfo = bz2.BZ2File( self.get_snapshot_fileinfo_path( new_snapshot_id ), 'w' )
IOError: [Errno 30] Read-only file system: '/media/B/backup/backintime/new_snapshot/fileinfo.bz2'

The GUI looked like the attached screenshot after the backup. Notice the lack of valid snapshots...

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-01-14T10:04:23Z
 * owner: jwiltshire
 * the launchpad url was https://bugs.launchpad.net/bugs/507246

**Comment by Germar** [comment]
(by tpo-deb)

**Comment by Germar** [comment]
(by tpo-deb)
forwarded upstream: #507250

**Comment by Germar** [comment]
(by jwiltshire)
Please use 'Also Affects...' instead of opening duplicate bugs. Merged.
