### ISSUE TITLE
can't find glib module under RHEL 5.5

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#232]
Installed version backintime-1.0.4, then found that backintime-gnome can't import the glib module, even though yum shows that I do have glib2, pygtk2, and pygobject2:

root: rpm -qa redhat-release
redhat-release-5Client-5.5.0.2
root: uname -a
Linux ******************* 2.6.18-194.26.1.el5 #1 SMP Fri Oct 29 14:21:16 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux
root: python -V
Python 2.4.3

jpdavis: sudo backintime-gnome
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 50, in ?
    import snapshotsdialog
  File "/usr/share/backintime/gnome/snapshotsdialog.py", line 34, in ?
    import gnometools
  File "/usr/share/backintime/gnome/gnometools.py", line 20, in ?
    import glib
ImportError: No module named glib
jpdavis: sudo backintime-gnome
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 50, in ?
    import snapshotsdialog
  File "/usr/share/backintime/gnome/snapshotsdialog.py", line 34, in ?
    import gnometools
  File "/usr/share/backintime/gnome/gnometools.py", line 20, in ?
    import glib
ImportError: No module named glib

jpdavis: sudo yum list installed 'glib2*' 'pygtk2*' 'pygobj*'
Loaded plugins: filter-data, keys, list-data, rhnplugin, security, versionlock
Reading version lock configuration
Installed Packages
glib2.i386                                               2.12.3-4.el5_3.1                                      installed
glib2.x86_64                                             2.12.3-4.el5_3.1                                      installed
glib2-devel.i386                                         2.12.3-4.el5_3.1                                      installed
glib2-devel.x86_64                                       2.12.3-4.el5_3.1                                      installed
pygobject2.x86_64                                        2.12.3-0.1.el5.test                                   installed
pygobject2-devel.x86_64                                  2.12.3-0.1.el5.test                                   installed
pygobject2-doc.x86_64                                    2.12.3-0.1.el5.test                                   installed
pygtk2.x86_64                                            2.10.1-12.el5                                         installed
pygtk2-codegen.x86_64                                    2.10.1-12.el5                                         installed
pygtk2-devel.i386                                        2.10.1-12.el5                                         installed
pygtk2-devel.x86_64                                      2.10.1-12.el5                                         installed
pygtk2-libglade.x86_64                                   2.10.1-12.el5                                         installed

Could this be due to not having a 32-bit pygobject2?

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-11-17T18:53:47Z
 * owner: jpdavis
 * the launchpad url was https://bugs.launchpad.net/bugs/676638

**Comment by Germar** [comment]
(by jpdavis)
I found glib.py in /usr/lib64/python2.4/site-packages/dbus ... manually adding this directory to the python path (why isn't it there by default???) inside gnometools.py prior to import glib gets me past that error, only to land on another gtk-related one;

jpdavis: sudo backintime-gnome

Back In Time
Version: 1.0.4

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

which: no gloobus-preview in (/usr/bin:/bin)
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1226, in ?
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 111, in __init__
    builder = gtk.Builder()
AttributeError: 'module' object has no attribute 'Builder'

**Comment by Germar** [comment]
(by danleweb)
GtkBuilder is the succesor or libglade: http://www.micahcarrick.com/gtk-builder-libglade-faq.html 
BIT < 1.0 used libglade and >= 1.0 ... 
SInce GtkBuilder is the succesor I prefer to stick with it.

Regards,
Dan

**Comment by Germar** [comment]
(by jpdavis)
It appears that RedHat 5.5 uses gtk2 version 2.10, and hence anything that has moved on to gtkbuilder will not be compatible.  Is it correct to say backintime >= 1.0 no longer supports RedHat 5?

So my choices are to use backintime 1.0 without the gui, or go back to version 0.9.  Feel free to convert this bug into a question.

**Comment by Germar** [comment]
(by danleweb)
It can rest as a bug, but I'm not sure I'll have time to move back to libglade.

Regads,
Dan

**Comment by Germar** [comment]
(by germar)
BIT doesn't use libglade/GtkBuilder anymore. It now uses Qt4
