### ISSUE TITLE
back in time 0.9.22 & 0.9.24 doesn't start

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#280]
KDE Version: 4.2.3
Python Version: 2.6.1

[sven@xob ~]$ backintime-kde4
Back In Time
Version: 0.9.22

Back In Time comes with ABSOLUTELY NO WARRANTY; for details type `backintime --license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/kde4backintime.py", line 1006, in <module>
    kapp, kaboutdata = create_kapplication( cfg )
  File "/usr/share/backintime/kde4backintime.py", line 962, in create_kapplication
    translation_text = cfg.get_translations() + extra_translations
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-05-11T20:39:46Z
 * owner: simonwesp
 * assignee: danleweb
 * the launchpad url was https://bugs.launchpad.net/bugs/375113

**Comment by Germar** [comment]
(by killefiz)
This happens when (the kde-flavor) cannot find the TRANSLATORS file.

backintime tries to open /usr/share/doc/backintime/TRANSLATORS and fails miserably when the file isn't there.

The fedora package (of which simon is the maintainer) installes the files into "/usr/share/doc/backintime-common-0.9.22/TRANSLATIONS".

(Similar issue with the gnome-flavor - there choosing "about" results in the very same TypeError - and no about window).

**Comment by Germar** [comment]
(by danleweb)
OK, I'll fix the "miserably" crash it the file is missing but the package is not done correctly.

**Comment by Germar** [comment]
(by simonwesp)
there flying question marks around my head, thousands of them.
Sven, i fixed it. Take a look in bodhi.
Requested for testing, so please test it :-)

good night and good luck

**Comment by Germar** [comment]
(by killefiz)
> OK, I'll fix the "miserably" crash it the file is missing but the package is not done correctly.

I don't think that the package is wrong - the package is split into multipe rpms (common, 
gnome, kde) and docs for common are installed into /usr/share/doc/backintime-common-version/.

Reading "stuff" from /usr/share/doc/* at runtime violates debian policy:

> Packages must not require the existence of any files in /usr/share/doc/ in order to function [90]. Any 
> files that are referenced by programs but are also useful as stand alone documentation should be 
> installed under /usr/share/package/ with symbolic links from /usr/share/doc/package. 
> ([90] The system administrator should be able to delete files in /usr/share/doc/ without causing 
> any programs to break.)

rpm policies also require that programs work when installed with --exclude-docs.

And then there is the fhs which recommends:

> Any program or package which contains or requires data that doesn't need to be modified should store that
> data in /usr/share (or /usr/local/share, if installed locally). It is recommended that a subdirectory be used
> in /usr/share for this purpose.

and fhs also states that /usr/share/doc is optional.

**Comment by Germar** [comment]
(by simonwesp)
not only in debian, in fedora, too...

MUST: If a package includes something as %doc, it must not affect the runtime of the application. To summarize: If it is in %doc, the program must run properly if it is not present.

**Comment by Germar** [comment]
(by danleweb)
Fixed in 0.9.26
