### ISSUE TITLE
[gnome] About Button does nothing

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#285]
If I click the "About"-button, it does just nothing.
Running Fedora 10 and gnome desktop environment.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-05-27T14:33:57Z
 * owner: moe.
 * the launchpad url was https://bugs.launchpad.net/bugs/380969

**Comment by Germar** [comment]
(by danleweb)
Try to run from a terminal/console (run the command: backintime-gnome).
Please attach the output.

**Comment by Germar** [comment]
(by moe.)

Output:

Back In Time
Version: 0.9.22

Back In Time comes with ABSOLUTELY NO WARRANTY; for details type `backintime --license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/gnomebackintime.py", line 826, in on_btn_about_clicked
    self.about_dialog = AboutDialog( self.config, self.glade )
  File "/usr/share/backintime/gnomebackintime.py", line 77, in __init__
    self.dialog.set_translator_credits( config.get_translations() + extra_translations  )
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I think this should be easy to fix, I'm a bit familiar to python.

**Comment by Germar** [comment]
(by danleweb)
This should be fixed in the latest version (0.9.26). But I don't know if there is a fedora package for this version.
