### ISSUE TITLE
Can't find snapshots folder

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#286]
I keep getting this error message:

Can't find snapshots folder.
If it is on a removable drive please plug it and then press OK

Where is the configuration file to reset the configuration of BackinTime?

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-06-01T22:10:48Z
 * owner: luke32j
 * the launchpad url was https://bugs.launchpad.net/bugs/382579

**Comment by Germar** [comment]
(by luke32j)
It was working for awhile, then it kept crashing with:
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1056, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 281, in __init__
    self.update_all( True )
  File "/usr/share/backintime/gnome/app.py", line 388, in update_all
    self.update_folder_view( 1, selected_file, show_snapshots )
  File "/usr/share/backintime/gnome/app.py", line 1000, in update_folder_view
    new_iter = self.store_folder_view.append( [ item[0], rel_path, item[3], item[5], item[1], item[2], item[4] ] )
TypeError: value is of wrong type for this column

After renaming the ~/.config/backintime/ config file, it now opens when I open backintime, but it still gives the Can't find snapshots folder err when backintime is run as root.

**Comment by Germar** [comment]
(by luke32j)
I found how to reset settings, by moving the config file in ~/.config/backintime, and in /root/.config/backintime directories.

I only have it set to backup home, and it seems it always crashes when the config file has this line:
gnome.last_path=/home/directory    If this is changed to /, it runs fine.

**Comment by Germar** [comment]
(by danleweb)
1. The easier way to share user config with root config you can make a symbolic link "/root/.config/backintime/config" to "~/.config/backintime/config".

2. "I only have it set to backup home, and it seems it always crashes when the config file has this line:
gnome.last_path=/home/directory If this is changed to /, it runs fine."
Do you take the backup as root and use the GUI as normal user ?

**Comment by Germar** [comment]
(by j-cottier)
I am still on Ubuntu 8.04 and this just happened to me on 0.9.26. Started backintime (user) to view some files and the GUI instantly flashed off. I then tried the backintime (root) and this worked ok at first, but then a second time flashed off just like the backintime (user). But deleting these entries in the config seems to have worked ok.

**Comment by Germar** [comment]
(by ubuntu-holmesfamily)
This happens in 10.10, frustratingly the GUI pops up but does not let you change any setting to correct the problem. I think this error should allow the GUI to run so that you can edit the settings.

**Comment by Germar** [comment]
(by danleweb)
If you want to reset setting; remove the file "~/.config/backintime/config".
but I recommend you to try the latest version (1.0) available in stable ppa.

**Comment by Germar** [comment]
(by peter-decampi)
Hi 

I'm getting the same error ""Can't find snapshots folder. If it is on a removable drive please plug it and then press OK"

I get this whenever I start back-in-time (the standard version - the the one with root privileges).

I have two hard disks and I back up just the /home folder from the first hard disk to the second hard disk.

However if I click on the second hard disk and open it (via nautilus) - starting back-in-time works fine.


It seems that I must initially mount the second hard disk in some way before I launch back-in-time but being some what new  to Ubuntu, I'm not sure how to do this

**Comment by Germar** [comment]
(by peter-decampi)
SOLVED - ofr me

Being an ex-Windows XP user I assumed that "hard Disk 2" was available at the start of my session. Just like it is in in windows.
Clicking on the drive, via Nautilus, mounted that hard drive for me, which is why Back-In-Time worked from then on.

The solution is to mount the drive via fstab. After a few goes (got bogged down with spaces which needed to be defined with "\040"). Everything works as expected.
