### ISSUE TITLE
backintime kde4 interface failed to launch

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#287]
backintime kde 4 interface failed to launch under kde 4.3 beta2 (mandriva cooker version)
kde4-config  -v
Qt: 4.5.1
KDE: 4.2.88 (KDE 4.2.88 (KDE 4.3 >= 20090527))
kde4-config: 1.0

Python is 2.6.1

Backintime is 0.9.26

mikala@cooker [~] % backintime-kde4
/usr/bin/backintime-kde4: line 26:  7984 Erreur de segmentation  python ${APP_PATH}/app.py $*

using python -v i have 
mikala@cooker [~] % LC_ALL=C python -v /usr/share/backintime/kde4/app.py 
# installing zipimport hook                                              
import zipimport # builtin                                               
# installed zipimport hook                                               
# /usr/lib64/python2.6/site.pyc matches /usr/lib64/python2.6/site.py     
import site # precompiled from /usr/lib64/python2.6/site.pyc             
# /usr/lib64/python2.6/os.pyc matches /usr/lib64/python2.6/os.py         
import os # precompiled from /usr/lib64/python2.6/os.pyc                 
import errno # builtin                                                   
import posix # builtin                                                   
# /usr/lib64/python2.6/posixpath.pyc matches /usr/lib64/python2.6/posixpath.py
import posixpath # precompiled from /usr/lib64/python2.6/posixpath.pyc        
# /usr/lib64/python2.6/stat.pyc matches /usr/lib64/python2.6/stat.py          
import stat # precompiled from /usr/lib64/python2.6/stat.pyc                  
# /usr/lib64/python2.6/genericpath.pyc matches /usr/lib64/python2.6/genericpath.py
import genericpath # precompiled from /usr/lib64/python2.6/genericpath.pyc        
# /usr/lib64/python2.6/warnings.pyc matches /usr/lib64/python2.6/warnings.py      
import warnings # precompiled from /usr/lib64/python2.6/warnings.pyc              
# /usr/lib64/python2.6/linecache.pyc matches /usr/lib64/python2.6/linecache.py    
import linecache # precompiled from /usr/lib64/python2.6/linecache.pyc            
# /usr/lib64/python2.6/types.pyc matches /usr/lib64/python2.6/types.py            
import types # precompiled from /usr/lib64/python2.6/types.pyc                    
# /usr/lib64/python2.6/UserDict.pyc matches /usr/lib64/python2.6/UserDict.py      
import UserDict # precompiled from /usr/lib64/python2.6/UserDict.pyc              
# /usr/lib64/python2.6/_abcoll.pyc matches /usr/lib64/python2.6/_abcoll.py        
import _abcoll # precompiled from /usr/lib64/python2.6/_abcoll.pyc                
# /usr/lib64/python2.6/abc.pyc matches /usr/lib64/python2.6/abc.py                
import abc # precompiled from /usr/lib64/python2.6/abc.pyc                        
# /usr/lib64/python2.6/copy_reg.pyc matches /usr/lib64/python2.6/copy_reg.py      
import copy_reg # precompiled from /usr/lib64/python2.6/copy_reg.pyc              
# /usr/lib64/python2.6/new.pyc matches /usr/lib64/python2.6/new.py                
import new # precompiled from /usr/lib64/python2.6/new.pyc                        
import encodings # directory /usr/lib64/python2.6/encodings                       
# /usr/lib64/python2.6/encodings/__init__.pyc matches /usr/lib64/python2.6/encodings/__init__.py
import encodings # precompiled from /usr/lib64/python2.6/encodings/__init__.pyc                 
# /usr/lib64/python2.6/codecs.pyc matches /usr/lib64/python2.6/codecs.py                        
import codecs # precompiled from /usr/lib64/python2.6/codecs.pyc                                
import _codecs # builtin                                                                        
# /usr/lib64/python2.6/encodings/aliases.pyc matches /usr/lib64/python2.6/encodings/aliases.py  
import encodings.aliases # precompiled from /usr/lib64/python2.6/encodings/aliases.pyc          
# /usr/lib64/python2.6/encodings/ascii.pyc matches /usr/lib64/python2.6/encodings/ascii.py      
import encodings.ascii # precompiled from /usr/lib64/python2.6/encodings/ascii.pyc              
Python 2.6.1 (r261:67515, Apr 12 2009, 04:14:16)                                                
[GCC 4.3.2] on linux2                                                                           
Type "help", "copyright", "credits" or "license" for more information.                          
/usr/share/backintime/kde4/app.py: inconsistent use of tabs and spaces in indentation           
dlopen("/usr/lib64/python2.6/lib-dynload/datetime.so", 2);                                      
import datetime # dynamically loaded from /usr/lib64/python2.6/lib-dynload/datetime.so          
# /usr/lib64/python2.6/gettext.pyc matches /usr/lib64/python2.6/gettext.py                      
import gettext # precompiled from /usr/lib64/python2.6/gettext.pyc                              
# /usr/lib64/python2.6/locale.pyc matches /usr/lib64/python2.6/locale.py                        
import locale # precompiled from /usr/lib64/python2.6/locale.pyc                                
# /usr/lib64/python2.6/functools.pyc matches /usr/lib64/python2.6/functools.py                  
import functools # precompiled from /usr/lib64/python2.6/functools.pyc                          
dlopen("/usr/lib64/python2.6/lib-dynload/_functools.so", 2);                                    
import _functools # dynamically loaded from /usr/lib64/python2.6/lib-dynload/_functools.so      
dlopen("/usr/lib64/python2.6/lib-dynload/_locale.so", 2);                                       
import _locale # dynamically loaded from /usr/lib64/python2.6/lib-dynload/_locale.so            
# /usr/lib64/python2.6/re.pyc matches /usr/lib64/python2.6/re.py                                
import re # precompiled from /usr/lib64/python2.6/re.pyc                                        
# /usr/lib64/python2.6/sre_compile.pyc matches /usr/lib64/python2.6/sre_compile.py              
import sre_compile # precompiled from /usr/lib64/python2.6/sre_compile.pyc                      
import _sre # builtin                                                                           
# /usr/lib64/python2.6/sre_parse.pyc matches /usr/lib64/python2.6/sre_parse.py                  
import sre_parse # precompiled from /usr/lib64/python2.6/sre_parse.pyc                          
# /usr/lib64/python2.6/sre_constants.pyc matches /usr/lib64/python2.6/sre_constants.py          
import sre_constants # precompiled from /usr/lib64/python2.6/sre_constants.pyc                  
dlopen("/usr/lib64/python2.6/lib-dynload/operator.so", 2);                                      
import operator # dynamically loaded from /usr/lib64/python2.6/lib-dynload/operator.so          
# /usr/lib64/python2.6/copy.pyc matches /usr/lib64/python2.6/copy.py                            
import copy # precompiled from /usr/lib64/python2.6/copy.pyc                                    
# /usr/lib64/python2.6/struct.pyc matches /usr/lib64/python2.6/struct.py                        
import struct # precompiled from /usr/lib64/python2.6/struct.pyc                                
dlopen("/usr/lib64/python2.6/lib-dynload/_struct.so", 2);                                       
import _struct # dynamically loaded from /usr/lib64/python2.6/lib-dynload/_struct.so            
dlopen("/usr/lib64/python2.6/lib-dynload/time.so", 2);                                          
import time # dynamically loaded from /usr/lib64/python2.6/lib-dynload/time.so                  
# /usr/lib64/python2.6/threading.pyc matches /usr/lib64/python2.6/threading.py                  
import threading # precompiled from /usr/lib64/python2.6/threading.pyc                          
import thread # builtin                                                                         
# /usr/lib64/python2.6/traceback.pyc matches /usr/lib64/python2.6/traceback.py                  
import traceback # precompiled from /usr/lib64/python2.6/traceback.pyc                          
# /usr/lib64/python2.6/collections.pyc matches /usr/lib64/python2.6/collections.py              
import collections # precompiled from /usr/lib64/python2.6/collections.pyc                      
dlopen("/usr/lib64/python2.6/lib-dynload/_collections.so", 2);                                  
import _collections # dynamically loaded from /usr/lib64/python2.6/lib-dynload/_collections.so  
# /usr/lib64/python2.6/keyword.pyc matches /usr/lib64/python2.6/keyword.py                      
import keyword # precompiled from /usr/lib64/python2.6/keyword.pyc                              
# /usr/share/backintime/common/backintime.pyc has bad mtime                                     
import backintime # from /usr/share/backintime/common/backintime.py                             
# /usr/share/backintime/common/config.pyc has bad mtime                                         
import config # from /usr/share/backintime/common/config.py                                     
# /usr/share/backintime/common/configfile.pyc has bad mtime                                     
import configfile # from /usr/share/backintime/common/configfile.py                             
# /usr/share/backintime/common/tools.pyc has bad mtime                                          
import tools # from /usr/share/backintime/common/tools.py                                       
dlopen("/usr/lib64/python2.6/lib-dynload/cStringIO.so", 2);                                     
import cStringIO # dynamically loaded from /usr/lib64/python2.6/lib-dynload/cStringIO.so        
# /usr/lib64/python2.6/token.pyc matches /usr/lib64/python2.6/token.py                          
import token # precompiled from /usr/lib64/python2.6/token.pyc                                  
# /usr/lib64/python2.6/tokenize.pyc matches /usr/lib64/python2.6/tokenize.py                    
import tokenize # precompiled from /usr/lib64/python2.6/tokenize.pyc                            
# /usr/lib64/python2.6/string.pyc matches /usr/lib64/python2.6/string.py                        
import string # precompiled from /usr/lib64/python2.6/string.pyc                                
dlopen("/usr/lib64/python2.6/lib-dynload/strop.so", 2);                                         
import strop # dynamically loaded from /usr/lib64/python2.6/lib-dynload/strop.so                
# /usr/lib64/python2.6/encodings/utf_8.pyc matches /usr/lib64/python2.6/encodings/utf_8.py      
import encodings.utf_8 # precompiled from /usr/lib64/python2.6/encodings/utf_8.pyc              
# /usr/share/backintime/common/logger.pyc has bad mtime                                         
import logger # from /usr/share/backintime/common/logger.py                                     
dlopen("/usr/lib64/python2.6/lib-dynload/syslog.so", 2);                                        
import syslog # dynamically loaded from /usr/lib64/python2.6/lib-dynload/syslog.so              
# /usr/share/backintime/common/snapshots.pyc has bad mtime                                      
import snapshots # from /usr/share/backintime/common/snapshots.py                               
# /usr/lib64/python2.6/statvfs.pyc matches /usr/lib64/python2.6/statvfs.py                      
import statvfs # precompiled from /usr/lib64/python2.6/statvfs.pyc                              
dlopen("/usr/lib64/python2.6/lib-dynload/bz2.so", 2);                                           
import bz2 # dynamically loaded from /usr/lib64/python2.6/lib-dynload/bz2.so                    
import pwd # builtin                                                                            
dlopen("/usr/lib64/python2.6/lib-dynload/grp.so", 2);                                           
import grp # dynamically loaded from /usr/lib64/python2.6/lib-dynload/grp.so                    
# /usr/share/backintime/common/applicationinstance.pyc has bad mtime                            
import applicationinstance # from /usr/share/backintime/common/applicationinstance.py           
# /usr/share/backintime/common/pluginmanager.pyc has bad mtime                                  
/usr/share/backintime/common/pluginmanager.py: inconsistent use of tabs and spaces in indentation
import pluginmanager # from /usr/share/backintime/common/pluginmanager.py                        
# /usr/share/backintime/common/guiapplicationinstance.pyc has bad mtime                          
import guiapplicationinstance # from /usr/share/backintime/common/guiapplicationinstance.py
import PyQt4 # directory /usr/lib64/python2.6/site-packages/PyQt4
# /usr/lib64/python2.6/site-packages/PyQt4/__init__.pyc matches /usr/lib64/python2.6/site-packages/PyQt4/__init__.py
import PyQt4 # precompiled from /usr/lib64/python2.6/site-packages/PyQt4/__init__.pyc
dlopen("/usr/lib64/python2.6/site-packages/PyQt4/QtGui.so", 2);
dlopen("/usr/lib64/python2.6/site-packages/sip.so", 2);
import sip # dynamically loaded from /usr/lib64/python2.6/site-packages/sip.so
dlopen("/usr/lib64/python2.6/site-packages/PyQt4/QtCore.so", 2);
import PyQt4.QtCore # dynamically loaded from /usr/lib64/python2.6/site-packages/PyQt4/QtCore.so
import PyQt4.QtGui # dynamically loaded from /usr/lib64/python2.6/site-packages/PyQt4/QtGui.so
import PyKDE4 # directory /usr/lib64/python2.6/site-packages/PyKDE4
# /usr/lib64/python2.6/site-packages/PyKDE4/__init__.pyc matches /usr/lib64/python2.6/site-packages/PyKDE4/__init__.py
import PyKDE4 # precompiled from /usr/lib64/python2.6/site-packages/PyKDE4/__init__.pyc
# /usr/lib64/python2.6/plat-linux2/DLFCN.pyc matches /usr/lib64/python2.6/plat-linux2/DLFCN.py
import DLFCN # precompiled from /usr/lib64/python2.6/plat-linux2/DLFCN.pyc
dlopen("/usr/lib64/python2.6/site-packages/PyKDE4/kdecore.so", 102);
dlopen("/usr/lib64/python2.6/site-packages/PyQt4/QtNetwork.so", 102);
import PyQt4.QtNetwork # dynamically loaded from /usr/lib64/python2.6/site-packages/PyQt4/QtNetwork.so
Segmentation fault

do you need any more information ?
(i'm not able to read python but i think verbose message can help)

Regards,

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-06-01T23:00:04Z
 * owner: balcaen-john
 * the launchpad url was https://bugs.launchpad.net/bugs/382587

**Comment by Germar** [comment]
(by balcaen-john)
If it can help to narrow the bug i launch it using gdb (thks to google for that) :


(gdb) r /usr/share/backintime/kde4/app.py
Starting program: /usr/bin/python /usr/share/backintime/kde4/app.py
Missing separate debug info for /usr/lib64/libz.so.1
Missing separate debug info for /usr/lib64/libpcre.so.0

Program received signal SIGSEGV, Segmentation fault.
0x00007f87e3c08f56 in ?? () from /usr/lib64/python2.6/site-packages/sip.so
(gdb) bt
#0  0x00007f87e3c08f56 in ?? () from /usr/lib64/python2.6/site-packages/sip.so
#1  0x00007f87e34f6e5b in initkdecore () at sipkdecorepart0.cpp:4811
#2  0x00007f87eaf30a46 in _PyImport_LoadDynamicModule (name=0x7fffc101f8e0 "PyKDE4.kdecore",
    pathname=0x7fffc101e810 "/usr/lib64/python2.6/site-packages/PyKDE4/kdecore.so", fp=<value optimized out>) at Python/importdl.c:53
#3  0x00007f87eaf2ec19 in import_submodule (mod=0x7f87ea211e88, subname=0x7fffc101f8e7 "kdecore", fullname=0x7fffc101f8e0 "PyKDE4.kdecore") at Python/import.c:2545
#4  0x00007f87eaf2eeb2 in load_next (mod=0x7f87ea211e88, altmod=0x7f87ea211e88, p_name=<value optimized out>, buf=0x7fffc101f8e0 "PyKDE4.kdecore",
    p_buflen=0x7fffc101f8d8) at Python/import.c:2365
#5  0x00007f87eaf2f558 in import_module_level (name=0x0, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f87eb3cdd10,
    level=<value optimized out>) at Python/import.c:2094
#6  0x00007f87eaf2faa5 in PyImport_ImportModuleLevel (name=0x7f87eb30b78c "PyKDE4.kdecore", globals=0x11769d0, locals=0x11769d0, fromlist=0x7f87eb3cdd10, level=-1)
    at Python/import.c:2138
#7  0x00007f87eaf1545d in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:48
#8  0x00007f87eae87268 in PyObject_Call (func=0x7f87eb3acea8, arg=0x7f87eb2fbec0, kw=0x0) at Objects/abstract.c:2487
#9  0x00007f87eaf15a26 in PyEval_CallObjectWithKeywords (func=0x7f87eb3acea8, arg=0x7f87eb2fbec0, kw=0x0) at Python/ceval.c:3548
#10 0x00007f87eaf18e55 in PyEval_EvalFrameEx (f=0x120c9c0, throwflag=<value optimized out>) at Python/ceval.c:2124
#11 0x00007f87eaf1d369 in PyEval_EvalCodeEx (co=0x7f87eb318468, globals=<value optimized out>, locals=<value optimized out>, args=0x0, argcount=0, kws=0x0,
    kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:2942
#12 0x00007f87eaf1d472 in PyEval_EvalCode (co=0x7f87e380a3a0, globals=0x7f87e3812c80, locals=0x1449260) at Python/ceval.c:515
#13 0x00007f87eaf38061 in run_mod (mod=<value optimized out>, filename=<value optimized out>, globals=0x11769d0, locals=0x11769d0, flags=<value optimized out>,
    arena=<value optimized out>) at Python/pythonrun.c:1330
#14 0x00007f87eaf38136 in PyRun_FileExFlags (fp=0x1176c10, filename=0x7fffc1022f82 "/usr/share/backintime/kde4/app.py", start=257, globals=0x11769d0,
    locals=0x11769d0, closeit=1, flags=0x7fffc1020e90) at Python/pythonrun.c:1316
#15 0x00007f87eaf396bd in PyRun_SimpleFileExFlags (fp=0x1176c10, filename=0x7fffc1022f82 "/usr/share/backintime/kde4/app.py", closeit=1, flags=0x7fffc1020e90)
    at Python/pythonrun.c:926
#16 0x00007f87eaf45ceb in Py_Main (argc=1, argv=0x7fffc1020fb8) at Modules/main.c:597
#17 0x00007f87ea8e691d in __libc_start_main (main=<value optimized out>, argc=<value optimized out>, ubp_av=<value optimized out>, init=<value optimized out>,
    fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7fffc1020fa8) at libc-start.c:220
#18 0x0000000000400639 in _start () at ../sysdeps/x86_64/elf/start.S:113

Regards,

**Comment by Germar** [comment]
(by balcaen-john)
ok, since kdebindings upgrade (to 4.90) it's now fixed .
