### ISSUE TITLE
kubuntu 0.9.99beta10 start problem

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#308]
Starting the latest beta in kubuntu 0910 does not work:

phil@ocean:~$ backintime-kde4
INFO: Update to config version 4: other snapshot locations
INFO: Random tag for profile 1: 311

Back In Time
Version: 0.9.99beta10

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-kde4 --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/kde4/app.py", line 1024, in <module>
    main_window = MainWindow( cfg, app_instance, kapp, kaboutdata )
  File "/usr/share/backintime/kde4/app.py", line 288, in __init__
    settingsdialog.SettingsDialog( self ).exec_()
  File "/usr/share/backintime/kde4/settingsdialog.py", line 242, in __init__
    self.cb_per_diretory_schedule.setChecked( self.config.get_per_directory_schedule() )
AttributeError: Config instance has no attribute 'get_per_directory_schedule'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-01-28T21:53:18Z
 * owner: phil-h
 * the launchpad url was https://bugs.launchpad.net/bugs/514019

**Comment by Germar** [comment]
(by danleweb)
Strange, mine settingsdialog.py line 242 does not look like yours.
Try to reinstall all backintime packages (backintime-common, backintime-kde4).

**Comment by Germar** [comment]
(by danleweb)
Since this looks more like an install problem I'll pass it to invalid.
