### ISSUE TITLE
NameError: global name '_' is not defined

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#31]
calling backintime -b issues the following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/share/backintime/plugins/gnomeplugin.py", line 115, in run
    message = ( 0, _('Working...') )
NameError: global name '_' is not defined

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-06-21T15:15:12Z
 * owner: jerico-dev
 * the launchpad url was https://bugs.launchpad.net/bugs/596919

**Comment by Germar** [comment]
(by jerico-dev)

**Comment by Germar** [comment]
(by danleweb)
The fix is already commited in beta version.
Thanks.
