### ISSUE TITLE
UnboundLocalError: local variable 'first_error' referenced before assignment

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#311]
My cronjob throws this exception:

Traceback (most recent call last):
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 126, in update_info
    if first_error:
UnboundLocalError: local variable 'first_error' referenced before assignment

The kde4 tray Icon give me this message:
Can't find snapshots folder. If it is on a removable drive please plug it. Waiting 30 seconds.

If updated from 0.9.26 because of some kde4 related problems to bzr 668 but still no luck with backups started by cron.
Manual backups just working.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-02-12T12:48:24Z
 * owner: trunneml
 * the launchpad url was https://bugs.launchpad.net/bugs/520956

**Comment by Germar** [comment]
(by trunneml)
After fixing the UnboundLocalError

I get this Error:
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 128, in update_info
    self.show_popup()
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 106, in show_popup
    self.popup = KPassivePopup.message( self.config.APP_NAME, QString.fromUtf8( self.last_message[1] ), self.status_
icon )
NameError: global name 'KPassivePopup' is not defined

and backintime thinks that the crond user is root!?

**Comment by Germar** [comment]
(by trunneml)
I found the right message from backintime

/var/backups/users/trunneml/backintime/zweistein/root/1 does not exist

/var/backups/users/trunneml/ is my backup directory
zweistein my hostname

but why he is using root here? trunneml would be right!

**Comment by Germar** [comment]
(by trunneml)
Hi,

here is the output of the os.environ dict, when backintime is started per cron.

{'USERNAME': 'root', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/sh', 'LANGUAGE': '', 'SUDO_COMMAND': '/e
tc/rc.d/crond start', 'SHLVL': '2', 'SUDO_UID': '1000', 'SUDO_GID': '100', 'PWD': '/home/trunneml', 'LOGNAME': 'root
', 'USER': 'trunneml', 'HOME': '/home/trunneml', 'PATH': '/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/perlbin/site:/usr/b
in/perlbin/vendor:/usr/bin/perlbin/core', 'SUDO_USER': 'trunneml', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;
33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01
;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z
=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01
;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg
=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:
*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg
=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*
.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35
:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=0
0;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.w
av=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'DISPLAY': ':0.0', '_': '/tmp/pytest.py'}

As you can see is LOGNAME root. Because cron is logged in as root and switches the user.
The entry USER is the right one.

I created a patch.

**Comment by Germar** [comment]
(by danleweb)
Patch applied. Thanks.

**Comment by Germar** [comment]
(by danleweb)
I just checked and according to cron man, LOGNAME should be set correctly.
In my tests LOGNAME is correct too, and USER is not defined.
What distribution are you using ?

**Comment by Germar** [comment]
(by danleweb)
Fixed: try both.

**Comment by Germar** [comment]
(by trunneml)
Yes you are right. The problem is dcron. This cron daemon doesn't behave like the old normal crond. What is really annoying. :-/
I created a bug report for dcron and attached a patch for his miss behaviour.

By the way dcron is the reason why back in time switched from @hourly to 0 * * * *.
The later version kills the anacron like features of some cron daemons for example dcron 4.4.

**Comment by Germar** [comment]
(by trunneml)
I mean I created a patch for dcron :-)
