### ISSUE TITLE
back int timne start and close immediately

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#336]
In non root mode: Back in time start and close immediately.
In root mode: Back in time start, ask the password, display error message:"Impossible de trouver le dossier des sauvegardes.
S'il se trouve sur un disque externe, veuillez connecter celui-ci puis faire OK"
--> impossible to find backup directory. If it is on an external drive, please connect it and press OK.

....after OK, it close immediately. The external HDD is connected and mounted.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-10-18T18:37:37Z
 * owner: thomas-dillinger77
 * the launchpad url was https://bugs.launchpad.net/bugs/662855

**Comment by Germar** [comment]
(by danleweb)
Open the GUI and check your settings.

**Comment by Germar** [comment]
(by thomas-dillinger77)
Thanks for your quick reply !
The GUI open and close directly (this is the bug) so that I cannot check the
settings.

Best Regards,
TD

2010/10/18 Dan <email address hidden>

> Open the GUI and check your settings.
>
> --
> back int timne start and close immediately
> https://bugs.launchpad.net/bugs/662855
> You received this bug notification because you are a direct subscriber
> of the bug.
>
> Status in Back In Time: New
>
> Bug description:
> In non root mode: Back in time start and close immediately.
> In root mode: Back in time start, ask the password, display error
> message:"Impossible de trouver le dossier des sauvegardes.
> S'il se trouve sur un disque externe, veuillez connecter celui-ci puis
> faire OK"
> --> impossible to find backup directory. If it is on an external drive,
> please connect it and press OK.
>
> ....after OK, it close immediately. The external HDD is connected and
> mounted.
>
> To unsubscribe from this bug, go to:
> https://bugs.launchpad.net/backintime/+bug/662855/+subscribe
>



-- 
Thomas Dillinger
Hoffnung 19,
42929 Wermelskirchen
Deutschland - Germany

**Comment by Germar** [comment]
(by danleweb)
Run it from command line:
     backintime-gnome
and checkout the output.

Regards,
Dan

**Comment by Germar** [comment]
(by thomas-dillinger77)
Hi Dan,
Was very busy the last days...
The issue is still actual. My Backintime do not work anymore.... :-(
This is the output of the asked command:

*dillinger@dillinger-laptop:~$ backintime-gnome
Back In Time
Version: 0.9.26

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1056, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 281, in __init__
    self.update_all( True )
  File "/usr/share/backintime/gnome/app.py", line 388, in update_all
    self.update_folder_view( 1, selected_file, show_snapshots )
  File "/usr/share/backintime/gnome/app.py", line 1000, in
update_folder_view
    new_iter = self.store_folder_view.append( [ item[0], rel_path, item[3],
item[5], item[1], item[2], item[4] ] )
TypeError: value is of wrong type for this column
dillinger@dillinger-laptop:~$*

Thanks in advance for your help

Best regards,
TD

2010/10/19 Dan <email address hidden>

> Run it from command line:
>     backintime-gnome
> and checkout the output.
>
> Regards,
> Dan
>
> --
> back int timne start and close immediately
> https://bugs.launchpad.net/bugs/662855
> You received this bug notification because you are a direct subscriber
> of the bug.
>
> Status in Back In Time: New
>
> Bug description:
> In non root mode: Back in time start and close immediately.
> In root mode: Back in time start, ask the password, display error
> message:"Impossible de trouver le dossier des sauvegardes.
> S'il se trouve sur un disque externe, veuillez connecter celui-ci puis
> faire OK"
> --> impossible to find backup directory. If it is on an external drive,
> please connect it and press OK.
>
> ....after OK, it close immediately. The external HDD is connected and
> mounted.
>
> To unsubscribe from this bug, go to:
> https://bugs.launchpad.net/backintime/+bug/662855/+subscribe
>



-- 
Thomas Dillinger
Hoffnung 19,
42929 Wermelskirchen
Deutschland - Germany

**Comment by Germar** [comment]
(by danleweb)
OK, this is a known bug. You should try BIT 1.0.2 from stable ppa repository.

**Comment by Germar** [comment]
(by thomas-dillinger77)
Hi Dan,
It works perfectly with the 1.0.2
Many thanks for your quick and efficient help !

Best regards,
TD

2010/10/23 Dan <email address hidden>

> OK, this is a known bug. You should try BIT 1.0.2 from stable ppa
> repository.
>
> --
> back int timne start and close immediately
> https://bugs.launchpad.net/bugs/662855
> You received this bug notification because you are a direct subscriber
> of the bug.
>
> Status in Back In Time: New
>
> Bug description:
> In non root mode: Back in time start and close immediately.
> In root mode: Back in time start, ask the password, display error
> message:"Impossible de trouver le dossier des sauvegardes.
> S'il se trouve sur un disque externe, veuillez connecter celui-ci puis
> faire OK"
> --> impossible to find backup directory. If it is on an external drive,
> please connect it and press OK.
>
> ....after OK, it close immediately. The external HDD is connected and
> mounted.
>
> To unsubscribe from this bug, go to:
> https://bugs.launchpad.net/backintime/+bug/662855/+subscribe
>



-- 
Thomas Dillinger
Hoffnung 19,
42929 Wermelskirchen
Deutschland - Germany

**Comment by Germar** [comment]
(by danleweb)
Perfect. I'll pass it to fix released.
