### ISSUE TITLE
Syntax error in tools.py under RHEL 5.5

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#34]
Downloaded and installed 1.0.4 (previously used 0.9.26).

root: rpm -qa redhat-release
redhat-release-5Client-5.5.0.2
root: uname -a
Linux ******************* 2.6.18-194.26.1.el5 #1 SMP Fri Oct 29 14:21:16 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux
root: python -V
Python 2.4.3
root: backintime -b
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 25, in ?
    import config
  File "/usr/share/backintime/common/config.py", line 27, in ?
    import tools
  File "/usr/share/backintime/common/tools.py", line 403
    class UniquenessSet():
                        ^
SyntaxError: invalid syntax

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-11-16T19:54:27Z
 * owner: jpdavis
 * the launchpad url was https://bugs.launchpad.net/bugs/676223

**Comment by Germar** [comment]
(by danleweb)
What version of python do you have ?

**Comment by Germar** [comment]
(by jpdavis)
As stated in the report, python 2.4.3 (standard RHEL 5.5).

Does the line "Status: New => Fix Committed" mean this is already fixed?  Is there a downloadable patch?

> -----Original Message-----
> From: <email address hidden> [mailto:<email address hidden>] On Behalf Of Dan
> Sent: Tuesday, November 16, 2010 1:28 PM
> To: Davis, Jean-Paul
> Subject: [Bug 676223] Re: Syntax error in tools.py under RHEL 5.5
> 
> What version of python do you have ?
> 
> ** Changed in: backintime
>        Status: New => Fix Committed
> 
> ** Changed in: backintime
>    Importance: Undecided => High
> 
> --
> Syntax error in tools.py under RHEL 5.5
> https://bugs.launchpad.net/bugs/676223
> You received this bug notification because you are a direct subscriber
> of the bug.
> 
> Status in Back In Time: Fix Committed
> 
> Bug description:
> Downloaded and installed 1.0.4 (previously used 0.9.26).
> 
> root: rpm -qa redhat-release
> redhat-release-5Client-5.5.0.2
> root: uname -a
> Linux ******************* 2.6.18-194.26.1.el5 #1 SMP Fri Oct 29 14:21:16
> EDT 2010 x86_64 x86_64 x86_64 GNU/Linux
> root: python -V
> Python 2.4.3
> root: backintime -b
> Traceback (most recent call last):
>   File "/usr/share/backintime/common/backintime.py", line 25, in ?
>     import config
>   File "/usr/share/backintime/common/config.py", line 27, in ?
>     import tools
>   File "/usr/share/backintime/common/tools.py", line 403
>     class UniquenessSet():
>                         ^
> SyntaxError: invalid syntax
> 
> To unsubscribe from this bug, go to:
> https://bugs.launchpad.net/backintime/+bug/676223/+subscribe

**Comment by Germar** [comment]
(by danleweb)
You are right, python version was already there.
Commited yes but not released :)

All you have to do is remove the brackets from "/usr/share/backintime/common/tools.py", line 403
    class UniquenessSet():
=>
   class UniquenessSet:

Regards,
Dan

**Comment by Germar** [comment]
(by jpdavis)
Thanks, a very simple fix.

But now it chokes trying to import module hashlib, which is apparently specific to Python 2.5+, see

http://stackoverflow.com/questions/1423861/hashlib-md5-compatibility-with-python-2-4
http://pypi.python.org/pypi/hashlib/20060408a

Installing python-hashlib.x86_64 from one of the RH-compatible repositories fixed this.

Then backintime works, but backintime-gnome can't import the glib module, even though I should have it:

jpdavis: sudo backintime-gnome
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 50, in ?
    import snapshotsdialog
  File "/usr/share/backintime/gnome/snapshotsdialog.py", line 34, in ?
    import gnometools
  File "/usr/share/backintime/gnome/gnometools.py", line 20, in ?
    import glib
ImportError: No module named glib
jpdavis: sudo yum list installed 'glib2*' 'pygtk2*'
Loaded plugins: filter-data, keys, list-data, rhnplugin, security, versionlock
Reading version lock configuration
Installed Packages
glib2.i386                                                2.12.3-4.el5_3.1                                     installed
glib2.x86_64                                              2.12.3-4.el5_3.1                                     installed
glib2-devel.i386                                          2.12.3-4.el5_3.1                                     installed
glib2-devel.x86_64                                        2.12.3-4.el5_3.1                                     installed
pygtk2.x86_64                                             2.10.1-12.el5                                        installed
pygtk2-codegen.x86_64                                     2.10.1-12.el5                                        installed
pygtk2-devel.i386                                         2.10.1-12.el5                                        installed
pygtk2-devel.x86_64                                       2.10.1-12.el5                                        installed
pygtk2-libglade.x86_64                                    2.10.1-12.el5                                        installed

Presumably this is another RHEL 5.5 issue?  (Need to change bug title, or start new bug reports for each issue?)

Jean-Paul

> -----Original Message-----
> From: <email address hidden> [mailto:<email address hidden>] On Behalf Of Dan
> Sent: Tuesday, November 16, 2010 2:41 PM
> To: Davis, Jean-Paul
> Subject: [Bug 676223] Re: Syntax error in tools.py under RHEL 5.5
> 
> You are right, python version was already there.
> Commited yes but not released :)
> 
> All you have to do is remove the brackets from
> "/usr/share/backintime/common/tools.py", line 403
>     class UniquenessSet():
> =>
>    class UniquenessSet:
> 
> Regards,
> Dan
> 
> --
> Syntax error in tools.py under RHEL 5.5
> https://bugs.launchpad.net/bugs/676223
> You received this bug notification because you are a direct subscriber
> of the bug.
> 
> Status in Back In Time: Fix Committed
> 
> Bug description:
> Downloaded and installed 1.0.4 (previously used 0.9.26).
> 
> root: rpm -qa redhat-release
> redhat-release-5Client-5.5.0.2
> root: uname -a
> Linux ******************* 2.6.18-194.26.1.el5 #1 SMP Fri Oct 29 14:21:16
> EDT 2010 x86_64 x86_64 x86_64 GNU/Linux
> root: python -V
> Python 2.4.3
> root: backintime -b
> Traceback (most recent call last):
>   File "/usr/share/backintime/common/backintime.py", line 25, in ?
>     import config
>   File "/usr/share/backintime/common/config.py", line 27, in ?
>     import tools
>   File "/usr/share/backintime/common/tools.py", line 403
>     class UniquenessSet():
>                         ^
> SyntaxError: invalid syntax
> 
> To unsubscribe from this bug, go to:
> https://bugs.launchpad.net/backintime/+bug/676223/+subscribe

**Comment by Germar** [comment]
(by danleweb)
Yes, please open another bug. It is easier to track them.

I'll have to check if glib is really necesserary.
How old is RHEL 5.5 ?

Regards,
Dan

**Comment by Germar** [comment]
(by bratdaking)
Not that old, quite recent actually, but still an update release of RHEL 5,
which is getting quite old now, and still using python 2.4.
Unfortunately there are a couple of syntax changes between 2.4 and 2.6 (e.g.
class () and the as statement), which are quite easy to fix, but bit
cumbersome to do by hand.
Guess the best thing is to wait till RHEL 6, which should be released in a
couple of months.

You need the glib python bindings to build the GUIs. I am not totally sure
but I guess the package is called python-gobject on ubuntu. Isn't the
RPM-package depending on something similar?

Cheers,
Bart

2010/11/17 Dan <email address hidden>

> Yes, please open another bug. It is easier to track them.
>
> I'll have to check if glib is really necesserary.
> How old is RHEL 5.5 ?
>
> Regards,
> Dan
>
> --
> Syntax error in tools.py under RHEL 5.5
> https://bugs.launchpad.net/bugs/676223
> You received this bug notification because you are a member of Back In
> Time Team, which is subscribed to Back In Time.
>
