### ISSUE TITLE
backintime-gnome crashes in python code

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#354]
When I call backintime with the following command
$ su-to-root -X -c backintime-gnome

It crashes with the message:
Back In Time
Version: 0.9.26

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Traceback (most recent call last):  File "/usr/share/backintime/gnome/app.py", line 1056, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 281, in __init__
    self.update_all( True )
  File "/usr/share/backintime/gnome/app.py", line 388, in update_all
    self.update_folder_view( 1, selected_file, show_snapshots )
  File "/usr/share/backintime/gnome/app.py", line 1000, in update_folder_view
    new_iter = self.store_folder_view.append( [ item[0], rel_path, item[3], item[5], item[1], item[2], item[4] ] )
TypeError: value is of wrong type for this column

ProblemType: Bug
DistroRelease: Ubuntu 10.04
Package: backintime-gnome 0.9.26-3ubuntu1
ProcVersionSignature: Ubuntu 2.6.32-29.58-generic 2.6.32.28+drm33.13
Uname: Linux 2.6.32-29-generic i686
Architecture: i386
Date: Tue Mar  8 22:29:07 2011
InstallationMedia: Ubuntu 10.04 LTS "Lucid Lynx" - Release i386 (20100429)
PackageArchitecture: all
ProcEnviron:
 PATH=(custom, no user)
 LANG=de_DE.utf8
 SHELL=/bin/bash
SourcePackage: backintime

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-08-15T22:48:39Z
 * owner: jwiltshire
 * the launchpad url was https://bugs.launchpad.net/bugs/731622

**Comment by Germar** [comment]
(by danielbystrov)
