### ISSUE TITLE
backintime-gnome fails to launch

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#376]
I am running BIT 1.08 on Arch Linux x86_64 with Gnome as the DE.  BIT fails to load reporting the following error:

# backintime-gnome 
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 33, in <module>
    import gnome
  File "/usr/lib/python2.7/site-packages/gtk-2.0/gnome/__init__.py", line 13, in <module>
    from _gnome import *
ImportError: /usr/lib/libgnomevfs-2.so.0: undefined symbol: gcry_control

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-07-21T20:16:33Z
 * owner: da-audiophile
 * the launchpad url was https://bugs.launchpad.net/bugs/814271

**Comment by Germar** [comment]
(by b-linax-1)
This is not an error in backintime. There's a libcrypt 1.5.0 related bug in the gnome-vfs package from Arch/extra-Repository. For more detail (and a patched version) see: https://bugs.archlinux.org/task/25225?project=1&string=gnome-vfs - and wait for an update in Arch/extra

**Comment by Germar** [comment]
(by b-linax-1)
extra/gnome-vfs has been updated to version 2.24.4-4 on 2011-07-26 

With this version the reported error should be gone ;)

**Comment by Germar** [comment]
(by da-audiophile)
Thanks for the info; works fine for me now!  Safe to close this ticket.
