### ISSUE TITLE
[abrt] backintime-kde-1.0.6-4.fc15: kde4systrayicon.py:106:show_popup:NameError: global name 'KPassivePopup' is not defined

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#391]
This bug was not found by me. It was reported by a Fedora user and is being passed upstream as advised by Dan.
Source (Fedora) bug: https://bugzilla.redhat.com/show_bug.cgi?id=730994
There is a backtrace attached to the Fedora bug.

"
abrt version: 2.0.3
architecture:   x86_64
cmdline:        /usr/bin/python /usr/share/backintime/kde4/kde4systrayicon.py 1
comment:        I was doing a backup when I had this problem
component:      backintime
executable:     /usr/share/backintime/kde4/kde4systrayicon.py
kernel:         2.6.40-4.fc15.x86_64
os_release:     Fedora release 15 (Lovelock)
package:        backintime-kde-1.0.6-4.fc15
reason:         kde4systrayicon.py:106:show_popup:NameError: global name
'KPassivePopup' is not defined
time:           Tue Aug 16 15:52:38 2011
uid:            500
username:       caterpillar

backtrace:
:kde4systrayicon.py:106:show_popup:NameError: global name 'KPassivePopup' is
not defined
:
:Traceback (most recent call last):
:  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 128, in
update_info
:    self.show_popup()
:  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 106, in
show_popup
:    self.popup = KPassivePopup.message( self.config.APP_NAME,
QString.fromUtf8( self.last_message[1] ), self.status_icon )
:NameError: global name 'KPassivePopup' is not defined
:
:Local variables in innermost frame:
:self: <__main__.KDE4SysTrayIcon instance at 0xe49d88>

"

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-10-09T20:32:23Z
 * owner: tim-timj
 * the launchpad url was https://bugs.launchpad.net/bugs/871475

**Comment by Germar** [comment]
(by caterpillar86)
any news?

**Comment by Germar** [comment]
(by germar)
I fixed this for next release. Till then you can use the attached patch
