### ISSUE TITLE
[abrt] backintime-gnome-1.0.6-2.fc14: snapshots.py:668:update_snapshots_location:AttributeError: Snapshots instance has no attribute 'get_snapshots_path'

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#392]
This bug was not found by me. It was reported by a Fedora user and is being passed upstream as advised by Dan.
Source (Fedora) bug: https://bugzilla.redhat.com/show_bug.cgi?id=694996
There is a backtrace attached to the Fedora bug.

"
abrt version: 1.1.17
architecture: x86_64
cmdline: python /usr/share/backintime/gnome/app.py
component: backintime
executable: /usr/share/backintime/gnome/app.py
kernel: 2.6.35.11-83.fc14.x86_64
package: backintime-gnome-1.0.6-2.fc14
reason: snapshots.py:668:update_snapshots_location:AttributeError: Snapshots
instance has no attribute 'get_snapshots_path'
release: Fedora release 14 (Laughlin)
time: 1302360022
uid: 500

backtrace
-----
snapshots.py:668:update_snapshots_location:AttributeError: Snapshots instance
has no attribute 'get_snapshots_path'

Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1226, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 311, in __init__
    settingsdialog.SettingsDialog( self.config, self.snapshots, self
).update_snapshots_location()
  File "/usr/share/backintime/gnome/settingsdialog.py", line 649, in
update_snapshots_location
    self.snapshots.update_snapshots_location()
  File "/usr/share/backintime/common/snapshots.py", line 668, in
update_snapshots_location
    logger.info( 'Folder of profile %s is set to %s' %( profile_id,
self.get_snapshots_path( profile_id ) ) )
AttributeError: Snapshots instance has no attribute 'get_snapshots_path'

Local variables in innermost frame:
old_folder: '/media/ba9bab6d-3e08-4898-98bd-7cc67baa4a18/openSUSE'
answer_change: False
self: <snapshots.Snapshots instance at 0x1e5cbd8>
profile_id: '1'
answer_continue: True
profiles: ['1']

How to reproduce
-----
1.Denied new format questions
2.Hit backup now
3.
"

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-10-09T20:35:06Z
 * owner: tim-timj
 * the launchpad url was https://bugs.launchpad.net/bugs/871477

**Comment by Germar** [comment]
(by germar)
This is fixed in current version
