### ISSUE TITLE
Backintime fails to get snapshot

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#407]
Here the messages I get by starting backntime from bash.
From about one week, everytime I try to get a snapshot it fails.

INFO: Lock
INFO: on process begins
INFO: Profile_id: 1
INFO: [kde4systrayicon] begin loop
INFO: Call rsync to take the snapshot
WARNING: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/media/backup" --exclude="/home/caterpillar/.local/share/backintime" --include="/media/removeda/removedM/" --include="/media/removeda/" --include="/media/" --include="/media/removeda/removedR/" --include="/home/caterpillar/" --include="/home/" --include="/home/caterpillar/.thunderbird/" --include="/home/caterpillar/.config/KVIrc/" --include="/home/caterpillar/.config/" --include="/home/caterpillar/.opera/"  --include="/media/removeda/removedM/**" --include="/media/removeda/removedR/**" --include="/home/caterpillar/**" --include="/home/caterpillar/.thunderbird/**" --include="/home/caterpillar/.config/KVIrc/**" --include="/home/caterpillar/.opera/bookmarks.adr" --exclude="*" / "/media/backup/backintime/Magic-4/caterpillar/1/new_snapshot/backup/" 2>&1" returns 5888
INFO: Command "find "/media/backup/backintime/Magic-4/caterpillar/1/new_snapshot" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "rm -rf "/media/backup/backintime/Magic-4/caterpillar/1/new_snapshot"" returns 0
INFO: Command "rm -rf "/media/backup/backintime/Magic-4/caterpillar/1/20120416-110345-642"" returns 0
ERROR: Failed to take snapshot !!!
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 128, in update_info
    self.show_popup()
  File "/usr/share/backintime/kde4/kde4systrayicon.py", line 106, in show_popup
    self.popup = KPassivePopup.message( self.config.APP_NAME, QString.fromUtf8( self.last_message[1] ), self.status_icon )
NameError: global name 'KPassivePopup' is not defined
INFO: Unlock
INFO: [kde4systrayicon] end loop

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-04-16T15:54:23Z
 * owner: caterpillar86
 * the launchpad url was https://bugs.launchpad.net/bugs/983192

**Comment by Germar** [comment]
(by caterpillar86)
At the moment I am without backups because of this bug... Any news?

**Comment by Germar** [comment]
(by caterpillar86)
Please close this bugreport. It was my fault, I had bad permissions on some files.
