### ISSUE TITLE
configuration window does not open when I click the button

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#423]
When I start backintime-gnome from the command line, and then click on the icon which should allow me to change the settings, nonthing happens (no new window opens). On the command line, I receive the following error messages:

Back In Time
Version: 1.0.22

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1017, in on_btn_settings_clicked
    settingsdialog.SettingsDialog( self.config, self.snapshots, self ).run()
  File "/usr/share/backintime/gnome/settingsdialog.py", line 57, in __init__
    builder.add_from_file(glade_file)
glib.GError: Unknown internal child: selection

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-04-18T17:36:49Z
 * owner: martin-eichner
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1170431

**Comment by Germar** [comment]
(by germar)
This is already fixed for the next version. For now you can use the attached patch.

**Comment by Germar** [comment]
(by martin-eichner)
Hi,

thanks for the quick help - unfortunately, it did not work. Maybe, I did 
something wrong:

I followed the link in your e-mail, opened the file 
"gnome/settingsdialog.glade" in the folder "/usr/share/backintime/" with 
an editor and compared the existing lines of code with the ones in the 
www page. I did not see any differences, but I replaced the old lines 
anyway by the lines in the www page. I started backintime, but the 
window still did not pop up when I clicked on the "settings" button. I 
restarted the computer and tried backintime again; same problem.

Did I do something wrong?

With kind regards,
Martin


Am 18.04.2013 20:01, schrieb Germar:
> This is already fixed for the next version. For now you can use the
> attached patch.
>
> ** Patch added: "settingsdialog.glade.diff"
>     https://bugs.launchpad.net/backintime/+bug/1170431/+attachment/3647765/+files/settingsdialog.glade.diff
>
> ** Changed in: backintime
>         Status: New => Fix Committed
>
> ** Changed in: backintime
>       Assignee: (unassigned) => Germar (germar)
>


-- 

Prof. Dr. Martin Eichner
Institut für Klinische Epidemiologie und angewandte Biometrie
Silcherstr. 5
72076 Tübingen

*Hinweis*
Wir sind im Sommer 2012 umgezogen (siehe Adresse oben)
Sie finden mich auf Ebene 7 in Raum 307

Büro:        07071 29-75905
Sekretariat: 07071 29-78253
Fax:         07071 29-5075

http://www.uni-tuebingen.de/modeling/
<email address hidden>

**Comment by Germar** [comment]
(by martin-eichner)
Hi,

sorry for the previous e-mail. I am still learning. I figured that the 
"-" sign in some lines meant to delete the lines of code. Now, it works 
fine. The lines in the www page look like I could automatically perform 
the changes using some program. If that is the case, I would like to 
learn how to execute the bug fix automatically.

Thanks again for your help!
Martin

-- 

Prof. Dr. Martin Eichner
Institut für Klinische Epidemiologie und angewandte Biometrie
Silcherstr. 5
72076 Tübingen

*Hinweis*
Wir sind im Sommer 2012 umgezogen (siehe Adresse oben)
Sie finden mich auf Ebene 7 in Raum 307

Büro:        07071 29-75905
Sekretariat: 07071 29-78253
Fax:         07071 29-5075

http://www.uni-tuebingen.de/modeling/
<email address hidden>

**Comment by Germar** [comment]
(by germar)
Hi Martin,

no worries. That diff file is indeed a file-format which will allow you to automatically apply changes to your local file. This is done by running 'patch <original-file> <diff-file>' in terminal. Take a look at 'man patch' and 'man diff' for further informations.

Regards,
Germar

**Comment by Germar** [comment]
(by martin-eichner)
Am 18.04.2013 23:16, schrieb Germar:
> That diff file is indeed a file-format which will allow you
> to automatically apply changes to your local file. This is done by
> running 'patch <original-file> <diff-file>' in terminal. Take a look at
> 'man patch' and 'man diff' for further informations.

Hi Germar,

thank you very much for coaching; I have tried it and it worked fine. 
This may come handy in other situations, too.

With kind regards,
Martin

-- 

Prof. Dr. Martin Eichner
Institut für Klinische Epidemiologie und angewandte Biometrie
Silcherstr. 5
72076 Tübingen

Büro:        07071 29-75905
Sekretariat: 07071 29-78253
Fax:         07071 29-5075

http://www.uni-tuebingen.de/modeling/
<email address hidden>
