### ISSUE TITLE
Backintime-kde4 not running

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#43]
OS is Kubuntu 13.10 latest udate from 2013-10-28, Backintime-kde4 is not running. 
In the terminal:
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/app.py", line 1136, in <module>
    main_window = MainWindow( cfg, app_instance, kapp, kaboutdata )
  File "/usr/share/backintime/kde4/app.py", line 237, in __init__
    self.list_files_view_model.removeColumns( 3, 2 )
TypeError: KDirModel.removeColumns() is a private method

greeting

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-09-29T09:49:17Z
 * owner: info-rothert
 * the launchpad url was https://bugs.launchpad.net/bugs/1232694

**Comment by Germar** [comment]
(by germar)
I already fixed this for next version. Until 1.0.28 is released you can use the attached patch with 'sudo patch /usr/share/backintime/kde4/app.py < app.patch'

**Comment by Germar** [comment]
(by info-rothert)
Good Morning,

set a #on the line and is running OK -> Thanks!

Greeting

**Comment by Germar** [comment]
(by lumks)
Will 1.0.28 get an SRU for Kubuntu 13.10? because we only have 1.0.10 in our repository (see https://bugs.launchpad.net/ubuntu/+source/backintime/+bug/1225486 ) and so without a backport or SRU it will be broken for this next release

and thank you for the fix (:

**Comment by Germar** [comment]
(by germar)
I don't think so. DebianImportFreeze for 13.10 was already in July and till now there is no new Debian version (BIT Ubuntu packages will be created from Debian packages).
But I recently had a chat with Jonathan Wiltshire, the Debian Maintainer for Backintime. We found the problem why Debian didn't pick up new versions. He will fix it soon. So 14.04 will have a more recent version, I guess.

For now you can use the PPA 'apt-add-repository ppa:bit-team/stable'. And I'll ask Jonathan if he could patch 1.0.10

**Comment by Germar** [comment]
(by lumks)
Hi
sorry for the late response. im just now back on saucy

the patch dont work here:

sudo patch /usr/share/backintime/kde4/app.py < app.patch
patching file /usr/share/backintime/kde4/app.py
Hunk #1 FAILED at 256.
1 out of 1 hunk FAILED -- saving rejects to file /usr/share/backintime/kde4/app.py.rej

tried with 1.0.10 and with 1.0.26

**Comment by Germar** [comment]
(by germar)
Hi Sandra,

You can also manually comment out the faulty line. Just add a # at the start of the line 'self.list_files_view_model.removeColumns( 3, 2 )'. For 1.0.10 it is line 237 and for 1.0.26 it is line 259

Next release (which will include the patch) will come at the end of next week.

Regards,
Germar

**Comment by Germar** [comment]
(by richard-rideandclimb)
I can confirm the # edit works.

Hopefully the Debian version will be updated/patched and BIT can then work in both directions effectively.

Peace.

**Comment by Germar** [comment]
(by thomi)
Hey @germar

Thanks for patch and info to manually patch...
GUI is back working... 

Hope KDE package will be also soon build after 1.0.28 release..

regards
thomi

**Comment by Germar** [comment]
(by atalanttore)
The # edit does work on my machine too.

**Comment by Germar** [comment]
(by cquickstad)
It looks like this commit changed the KDirModel.removeColumns() method by making it private instead of public
http://lists.kde.org/?l=kde-commits&m=137892823824128&w=4

It appears that the KDirModel.removeColumn() method (no 's' -- singular) was not affected by that commit.

To replicate the functionality, rather than commenting out the line, it appears removing column 3 twice would have the same effect:

Change this (app.py, line 237):
self.list_files_view_model.removeColumns( 3, 2 )

To this
self.list_files_view_model.removeColumn( 3 )
self.list_files_view_model.removeColumn( 3 )

**Comment by Germar** [comment]
(by germar)
Thanks Chad for pointing this out. It is all correct. But it doesn't make any difference. The columns that should be deleted in here will not disappear. Neither with the old KDirModel.removeColumns() nor with  single removeColumn(). These are standard columns from QTreeView which contain owner and permission. BIT hide them couple lines later anyways:

for column_index in xrange( 3, self.list_files_view_model.columnCount() ):
    self.list_files_view.hideColumn( column_index )

**Comment by Germar** [comment]
(by germar)
This is released by now. But I'll leave this bug open as 'Fix commited' because Debian and Ubuntus official repositories still have 1.0.10. So it is easier to find for people who have trouble to start BIT.

**Comment by Germar** [comment]
(by futurepilot)
I have 1.0.28 from the BIT stable PPA and it still doesn't work

Back In Time
Version: 1.0.28

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-kde4 --license' for details.

Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated.
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/app.py", line 1136, in <module>
    main_window = MainWindow( cfg, app_instance, kapp, kaboutdata )
  File "/usr/share/backintime/kde4/app.py", line 237, in __init__
    self.list_files_view_model.removeColumns( 3, 2 )
TypeError: KDirModel.removeColumns() is a private method

**Comment by Germar** [comment]
(by germar)
From line numbering I'd say your kde4/app.py is still from 1.0.10. Please remove Backintime completely 'sudo apt-get remove backintime-common backintime-kde4' and make sure '/usr/share/backintime' is empty. Than reinstall it again.

**Comment by Germar** [comment]
(by futurepilot)
I seem to have missed that the backintime-kde package was renamed to 
backintime-kde4 in the PPA and that the broken version from the 13.10 repos 
was getting installed alongside the backintime-common package from the PPA.

 sudo apt-get install backintime-kde
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer 
required:
  python-requests python-urllib3 ssh-import-id
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  backintime-common
The following NEW packages will be installed:
  backintime-common backintime-kde
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 25.6 kB/295 kB of archives.
After this operation, 1,589 kB of additional disk space will be used.
Do you want to continue [Y/n]? Y
Get:1 http://mirror.anl.gov/pub/ubuntu/ saucy/universe backintime-kde all 
1.0.10-1 [25.6 kB]
Fetched 25.6 kB in 0s (100 kB/s)            
Selecting previously unselected package backintime-common.
(Reading database ... 167495 files and directories currently installed.)
Unpacking backintime-common (from .../backintime-common_1.0.28~saucy_all.deb) 
...
Selecting previously unselected package backintime-kde.
Unpacking backintime-kde (from .../backintime-kde_1.0.10-1_all.deb) ...
Processing triggers for man-db ...
Processing triggers for desktop-file-utils ...
Processing triggers for mime-support ...
Setting up backintime-common (1.0.28~saucy) ...
Setting up backintime-kde (1.0.10-1) ...

Should there be some kind of conflict between these packages to prevent this 
from happening?

**Comment by Germar** [comment]
(by germar)
The PPA package wasn't renamed. It was always backintime-kde4. But you're right. I added 'Provides' field to kde4/DEBIAN/control. Hope this will help. If not we'll have to make a virtual package.

**Comment by Germar** [comment]
(by germar)
@Nick the 'Provides' field didn't help. I created a virtual package 'backintime-kde'.

**Comment by Germar** [comment]
(by m-busico)
Hi all,
I still have the problem on
Kubuntu 13.10 64 bit fresh install

backintime-kde 1.0.10-1
backintime-common 1.0.10-1

Have i to wait for a new package?

**Comment by Germar** [comment]
(by germar)
Hi Mirto,
1.0.10 from official repositories is still the old, broken version. You can either use 1.0.28 from ppa:bit-team/stable or you can patch 1.0.10 with the patch I provided in comment #1.
Regards,
Germar

**Comment by Germar** [comment]
(by m-busico)
Hi Germar,
it works 
Thanks
mirto

**Comment by Germar** [comment]
(by monsta-mint)
> But I recently had a chat with Jonathan Wiltshire, the Debian Maintainer for Backintime. We found the problem why Debian didn't pick up new versions.

Wow. And what is the cause? I'm asking because this maintainer doesn't answer the users who file the bug reports on Debian bug tracker.

**Comment by Germar** [comment]
(by germar)
Release tar-balls had been uploaded to a different folder in http://backintime.le-web.org/ and so his upstream-version-check script couldn't pick up those files anymore.

**Comment by Germar** [comment]
(by monsta-mint)
Well, if the script doesn't work, why not do it manually? Anyway, looks like it didn't change anything. There's still 1.0.10 in Debian.

**Comment by Germar** [comment]
(by germar)
Monsta, please keep in mind that we all (including Jonathan) volunteer in doing this. I assume he is to busy at the moment to upgrade the package. No offence, but if this isn't going fast enough for you, you should rather offer to take over maintenance for BIT Debian package by your self.
BTW there is an alternative with ppa:bit-team/stable which is maintained by Dan. Sure this is not for Debian. But while reading your name I assume you're on Mint which is based on Ubuntu. So you can use the PPA.

Kind regards,
Germar

**Comment by Germar** [comment]
(by migaxmoitax)
Thank you for the quick fix, support and dedication.
Commenting the line seems to get it going.
The patch did not work, had to do it manually.

**Comment by Germar** [comment]
(by meikamona)
OKay I got through this to comment out line 237 in Version: 1.0.10 , however I had to uninstall and re-install because the line number(s) did not correspond when I searched for the text string. (from memory it was like 28x when using Kate, command line returned 1.0.10 when i type backintime at this stage)  And then they did correspond on 237, so if patching to comment out by line number out doesn't work then try a reinstall.

**Comment by Germar** [comment]
(by monsta-mint)
Since 1.0.34 is in the repos, maybe mark this as "Fix Released"?
