### ISSUE TITLE
Won't start in Fedora 20 Alpha-4

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#430]
I'm trying out Fedora 20 Alpha 4. When I start Back In Time, it appears briefly and than refuses to run. Fedora then produces an error message saying: "A problem in the backintime-gnome-1.0.28-1.fc20 package has been detected".

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-10-27T16:49:17Z
 * owner: sackwort
 * the launchpad url was https://bugs.launchpad.net/bugs/1245222

**Comment by Germar** [comment]
(by germar)
Please run 'backintime-gnome' from command line and post the output.

**Comment by Germar** [comment]
(by sackwort)
Thank you for your repsonse. Please find below the output of backintime-gnome.

Back In Time
Version: 1.0.28

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

which: no gloobus-preview in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/neil/.local/bin:/home/neil/bin)
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1280, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 321, in __init__
    settingsdialog.SettingsDialog( self.config, self.snapshots, self ).run()
  File "/usr/share/backintime/gnome/settingsdialog.py", line 192, in __init__
    self.keyring_supported = tools.keyring_supported()
  File "/usr/share/backintime/common/tools.py", line 511, in keyring_supported
    backends = (keyring.backend.SecretServiceKeyring,
AttributeError: 'module' object has no attribute 'SecretServiceKeyring'

**Comment by Germar** [comment]
(by germar)
This is a dependencies problem of the current Fedora package. 'python-secretstorage' is missing in dependencies. As far as I know the package maintainer is aware of this and will post an updated package soon. Take a look at https://bugzilla.redhat.com/show_bug.cgi?id=1014976#c7

Till then you can either install 'python-secretstorage' manually (don't know the correct name in Fedora and can't help with installing as I don't use Fedora) or you can use the patch I provided in Bug #1243911

**Comment by Germar** [comment]
(by sackwort)
OK. Thank you very much for your replies.

Regards.

**Comment by Germar** [comment]
(by sackwort)
Hi Germar

Just to let you know that I applied your patch and it works fine now.

Thank you very much.

Neil
