### ISSUE TITLE
Ubuntu Lucid dosn't provide SecretServiceKeyring

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#45]
Realized that my BIT was not updating today so I corrected this and upgraded to version 10.0.28 on an Unbuntu 10.04 LTS system.  Error is as follows:

# backintime-gnome 

Back In Time
Version: 1.0.28

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime-gnome --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 1280, in <module>
    main_window = MainWindow( cfg, app_instance )
  File "/usr/share/backintime/gnome/app.py", line 333, in __init__
    mnt = mount.Mount(cfg = self.config, profile_id = profile_id, parent = self.window)
  File "/usr/share/backintime/common/mount.py", line 52, in __init__
    pw_cache = password.Password_Cache(self.config)
  File "/usr/share/backintime/common/password.py", line 252, in __init__
    self.keyring_supported = tools.keyring_supported()
  File "/usr/share/backintime/common/tools.py", line 511, in keyring_supported
    backends = (keyring.backend.SecretServiceKeyring,
AttributeError: 'module' object has no attribute 'SecretServiceKeyring'

I have tried running BIT as root and as a reg user.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-10-23T20:39:04Z
 * owner: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1243911

**Comment by Germar** [comment]
(by germar)
Seems like the old python-keyring version in lucid doesn't provide SecretServiceKeyring. Until next release you can use the attached patch with:

sudo patch /user/share/backintime/common/tools.py < secretservicekeyring.patch

**Comment by Germar** [comment]
(by rprine)
Super response time and it worked perfectly.

Thanks!!!!!!

**Comment by Germar** [comment]
(by phil-lxnet)
Thanks Germar, just sorted my Mums backup out with that patch.  Cheers.
Others cutting and pasting above command note typo: /user should be /usr so corrected command line is:-

sudo patch /usr/share/backintime/common/tools.py < secretservicekeyring.patch

Or if you are not in the directory where you downloaded the above patch and happened to download it into your default "Downloads" directory then the following should work from where ever.

sudo patch /usr/share/backintime/common/tools.py < ~/Downloads/secretservicekeyring.patch

Thanks again Germar.
