### ISSUE TITLE
GUI shows wrongly "no backup needed"

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#452]
Since some days (I think I saw BiT getting updated to 1.1.0~beta03), it fails to take a snapshot.
I checked the flag in the settings (only backup when needed) is disabled.

In the terminal, I see the following Python error when running it as root (as usual):
------------------------------
Back In Time
Version: 1.1.0~beta03

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 436, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 191, in start_app
    ret = take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 53, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 865, in take_snapshot
    self.config.inhibitCookie = tools.inhibitSuspend(toplevel_xid = self.config.xWindowId)
  File "/usr/share/backintime/common/tools.py", line 713, in inhibitSuspend
    bus = dbus.bus.BusConnection(os.environ['DBUS_SESSION_BUS_ADDRESS'])
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
------------------------------

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-01-13T20:17:15Z
 * owner: caco3
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1410496

**Comment by Germar** [comment]
(by germar)
Thanks for reporting! I was about to create the final release but now I'll make a beta04 and go on with testing :-)

**Comment by Germar** [comment]
(by caco3)
If I run BiT as normal user, the same backup runs fine.

**Comment by Germar** [comment]
(by caco3)
cool, thank you very much!
