### ISSUE TITLE
ssh problem with conflicting keys in .ssh/config

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#460]
Private key specified in configuration will not override an existing key defined in ~/.ssh/config or /etc/ssh/ssh_config.

I don't think this behavior is expected since a key is explicitly defined in the profile's configuration.

Update: Removed original description since problem is better understood thanks to Germar's help.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-03-18T16:12:24Z
 * owner: plaxx
 * the launchpad url was https://bugs.launchpad.net/bugs/1433682

**Comment by Germar** [comment]
(by germar)
As far as I can see there is not -i <FILE> option for sshfs. So this wouldn't help over there.

But I don't think this is your problem. We use an own ssh-agent instance for BackInTime (due to bug #841672). And this ssh-agent should only contain those keys which where added by BIT it self. So (IMHO) there can't be to much keys.

There is a problem with password handling (bug #1431305) on which I'm currently working on. I'll push a new version which should hopefully fix this in a few minutes to our testing PPA. Would be great if you could test this (sudo add-apt-repository ppa:bit-team/testing && sudo apt-get update && sudo apt-get upgrade) and report back if problems still exist.

**Comment by Germar** [comment]
(by germar)
Okay, for sshfs this could be done through sshfs -o ssh_command='ssh -i ~/.ssh/KEY'

**Comment by Germar** [comment]
(by plaxx)
Thanks for the quick response!

I don't have a passphrase on my key. I tried at first but created a new one instead (since I was having issues). So I didn't tried your latest version.

I tried on a different server (at home) and I'm getting the same results but I was successful with a direct sshfs mount (using -o  ssh_command to setup my key).

I realize now that I have a rather fancy .ssh/config file with strict default ciphers, host aliases and per-entry keys. If BIP is trying to ping the host first based on the name I've given in the config this will never work (its an alias to an .ssh/config entry). 

> Ping <hostname> failed. Host is down or wrong address.

If I give the full hostname or the IP of the machine it won't work either because of very strict default cipher list. I add exceptions overrides in my .ssh/config for old servers (which my backup servers happen to be).

With the latest version, I added in my .ssh/config an alias to an hardcoded IP address and used that address in the BIP config and I got further. It requested the passphrase specified by my .ssh/config entry for this host. Not being overridden by the one I specified in BIP.

I would have no problem with setuping a specific .ssh/config entry only with the right passwordless key and ssh cipher options for BIP but if it needs to be `pingable` then it definitely limits my options.

Step by step instructions on how to reproduce the ssh-agent/sshfs environment that BIP is setuping would be awesome and I would be willing to spend some time crafting some ssh troubleshooting FAQ entry with your input. This would help users figure problems by themselves I think.

Ultimately shouldn't you specify the exact key provided by the user using the "-o ssh_command=..." or lookup if there is an entry in .ssh/config before trying to ping it and if so trust the user, ssh and sshfs to do the right thing.

**Comment by Germar** [comment]
(by plaxx)
I found a workaround.

Create a new hostname in your /etc/hosts pointing to your server IP. Setting this hostname in BIP will satisfy the "server must be pingable requirement".

Connect to this host with ssh. This will make sure that an entry is created in your .ssh/known_hosts for this new hostname. (If you skip this test BIP will complain about a lack of entry of that server in ssh_known_host.)

Add a new entry in your .ssh/config under that hostname and set whatever cipher and/or key requirement you have.

Configure BIP to use this new hostname for ssh backups.

Profit!

I think I wouldn't have to do any of this if BIP would:
* specify a "-o ssh_command='ssh -i ~/.ssh/KEY'" when calling sshfs. My .ssh/config would be honored and the key overridden.
* doesn't have a 'host must be pingable' requirement

I'll check if this would be easily done.

**Comment by Germar** [comment]
(by germar)
Good to hear that you was able to fix this. I wrote this before your last post and will post it anyways ;-)

I'll consider the '-i <KEY>' option. But it won't make it into next release anymore.

------------------------------------------------------

Okay, with passphrase-less keys the other bug shouldn't matter.

Host must be a regular domain or IP Address. Aliases would only work if you define them in /etc/hosts.

A strict cipher list shouldn't matter as long as you leave cipher in BIT to default. This will let ssh negotiate the cipher. If you choose one in BIT this will add '-o Ciphers=<SELECTED_CIPHER>' so only this one is allowed.

Here is what BIT does for SSH after pressing OK in Settings:
1. unlock_ssh_agent:
   - check if 'ssh-add -l' contains privat key's fingerprint
   - if not set environ SSH_ASKPASS=backintime-askpass and
     run 'ssh-add <KEY_FILE>'
   - check again if 'ssh-add -l' contains fingerprint and raise error if not

2. check_ping_host:
   this is actually no ping anymore as some people deactivate ICMP.
   instead this does a port check with trying 5 times to connect to
   configured Host/Port with 2sec timeout.

3. check_fuse:
   - check if sshfs is installed (same like 'which sshfs')
   - check if current user is in group 'fuse'
   - if group 'fuse' does not exist just pass as it is most probaply not
     used on this distri

4. check_known_hosts:
   - run 'ssh-keygen -F <HOST>' and check if this returns 'Host <HOST> found'
   - this is done twice. First with configured host
     and second with [<HOST>]:<PORT>

5. check_login:
   - try to run 'ssh -o PreferredAuthentications=publickey -p <PORT>
     -o ServerAliveInterval=240 <USER>@<HOST> echo "Hello"' (all one line)

6. check_cipher:
   - if cipher is 'default' just pass this test
   - try to run 'ssh -o Ciphers=<CIPHER> -p <PORT>
     -o ServerAliveInterval=240 <USER>@<HOST> echo "Hello"'

7. check_remote_folder:
   this will run a script on remote to check if snapshot folder exist
   and is rwx. If it doesn't exist it will create it.

   script (all one line):
   d=0; test -e <PATH> || d=1; test $d -eq 1 && mkdir <PATH>; err=$?;
   test $d -eq 1 && exit $err; test -d <PATH> || exit 11;
   test -w <PATH> || exit 12; test -x <PATH> || exit 13; exit 20

   run with 'ssh -p <PORT> -o ServerAliveInterval=240 <USER>@<HOST> <SCRIPT>'

8. check_remote_commands
   this will try to sync a temp file with rsync and then run a script which
   should check if all used commands with their options are supported by remote

   rsync command (all one line):
   rsync -rtDHh --links --no-p --no-g --no-o --dry-run --chmod=Du+wx
   <TEMP_FILE> --rsh="ssh -p <PORT> -c <CIPHER>" <USER>@<HOST>:<PATH>

   script (all one line):
   tmp=<REMOTE_TEMP_PATH> ; 
   #first define a function to clean up and exit
   cleanup(){ 
   test -e $tmp/a && rm $tmp/a >/dev/null 2>&1; 
   test -e $tmp/b && rm $tmp/b >/dev/null 2>&1; 
   test -e $tmp && rmdir $tmp >/dev/null 2>&1; 
   exit $1; };
   #create tmp_RANDOM dir and file a
   test -e $tmp || mkdir $tmp; touch $tmp/a; 
   #try to create hardlink b from a
   echo \"cp -aRl SOURCE DEST\"; cp -aRl $tmp/a $tmp/b >/dev/null; err_cp=$?; 
   test $err_cp -ne 0 && cleanup $err_cp; 
   #list inodes of a and b
   ls -i $tmp/a; ls -i $tmp/b;
   #try to chmod
   echo \"chmod u+rw FILE\"; chmod u+rw $tmp/a >/dev/null; err_chmod=$?;
   test $err_chmod -ne 0 && cleanup $err_chmod;
   #try to find and chmod
   echo \"find PATH -type f -exec chmod u-wx \"{}\" \\;\";
   find $tmp -type f -exec chmod u-wx \"{}\" \\; >/dev/null; err_find=$?;
   test $err_find -ne 0 && cleanup $err_find;
   #try find suffix '+'
   find $tmp -type f -exec chmod u-wx \"{}\" + >/dev/null; err_gnu_find=$?;
   #try to rm -rf
   echo \"rm -rf PATH\"; rm -rf $tmp >/dev/null; err_rm=$?;
   test $err_rm -ne 0 && cleanup $err_rm; 
   #report not supported gnu find suffix
   test $err_gnu_find -ne 0 && echo \"gnu_find not supported\" && exit $err_gnu_find;
   #if we end up here, everything should be fine
   echo \"done\"

   run with 'ssh -p <PORT> -o ServerAliveInterval=240 <USER>@<HOST> <SCRIPT>'

   output of this will be analysed for matching inodes and errors from commands


Before mounting BIT will run a light version of this tests. 
Only 1. - 3., 5. and 7. is used.

To mount the remote path BIT will run:
sshfs -p <PORT> -o ServerAliveInterval=240 -o Ciphers=<CIPHER> -o idmap=user 
<USER>@<HOST>:<PATH> <MOUNTPOINT>

To unmount it will run:
fusermount -u <MOUNTPOINT>

During taking a new snapshot BIT will run several commands with:
ssh -p <PORT> -c <CIPHER> -o ServerAliveInterval=240 <USER>@<HOST> <COMMAND>

rsync will run with:
rsync -rtDHh --links --no-p --no-g --no-o --rsh="ssh -p <PORT> -c <CIPHER>"
--delete --delete-excluded -i --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx
--exclude=<FORCE_EXCLUDES> --include=<INCLUDE>
--include=<ALL_SINGLE_FOLDER_DOWN_TO_ROOT> --exclude=<EXCLUDE>
--include="<INCLUDE>/**" --exclude="*" / '<USER>@<HOST>:"<PATH>"'

**Comment by Germar** [comment]
(by plaxx)
At first I tried this:

=== modified file 'common/sshtools.py'
--- common/sshtools.py	2015-02-19 17:13:26 +0000
+++ common/sshtools.py	2015-03-20 00:56:30 +0000
@@ -104,6 +104,8 @@
         sshfs = ['sshfs'] + self.ssh_options
         if not self.cipher == 'default':
             sshfs.extend(['-o', 'Ciphers=%s' % self.cipher])
+        # specifying key file here allows to override conflicting .ssh/config key entry
+        sshfs.extend(['-o', "ssh_command='ssh -i %s'" % self.private_key_file])
         sshfs.extend(['-o', 'idmap=user'])
         sshfs.extend([self.user_host_path, self.mountpoint])
         #bugfix: sshfs doesn't mount if locale in LC_ALL is not available on remote host

Doesn't get me any further. Turns out its check_login() that requests for my conflicting key to be unlocked. So I thought using -o IdentityFile=<keyfile> instead would get me further:

=== modified file 'common/sshtools.py'
--- common/sshtools.py	2015-02-19 17:13:26 +0000
+++ common/sshtools.py	2015-03-20 01:28:04 +0000
@@ -97,6 +97,11 @@
                            'But this can make troubles with passphrase-less keys.' 
                            %{'path': self.private_key_file})
             self.private_key_fingerprint = self.private_key_file
+
+        # specifying key file here allows to override for potentially 
+        # conflicting .ssh/config key entry
+        self.ssh_options += ['-o', 'IdentityFile=%s' % self.private_key_file]
+
         self.unlock_ssh_agent()
 
     def _mount(self):

It does but I get stuck further along. Passphrase is requested for an unrelated key (the one in ssh/config for that host). Here's the stacktrace if I Ctrl-C instead of input passphrase:

$ backintime --profile-id 2 --backup

Back In Time
Version: 1.1.3-4

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Inhibit Suspend started. Reason: take snapshot
INFO: mount ssh: user@server:backups on [...]
INFO: on process begins
INFO: Profile_id: 2
Gtk-Message: Failed to load module "overlay-scrollbar"
"sni-qt/8981" WARN  21:29:28.845 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
INFO: [qt4systrayicon] begin loop
INFO: Call rsync to take the snapshot
Enter passphrase for key '[...]/.ssh/[unrelated]': 
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 436, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 191, in start_app
    ret = take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 52, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 916, in take_snapshot
    ret_val, ret_error = self._take_snapshot( snapshot_id, now, include_folders )
  File "/usr/share/backintime/common/snapshots.py", line 1237, in _take_snapshot
    self._execute( cmd + ' 2>&1', self._exec_rsync_callback, params, filters = (self._filter_rsync_progress, ))
  File "/usr/share/backintime/common/snapshots.py", line 1604, in _execute
    line = tools.temp_failure_retry( pipe.readline )
  File "/usr/share/backintime/common/tools.py", line 419, in temp_failure_retry
    return func(*args, **kwargs)
KeyboardInterrupt

**Comment by Germar** [comment]
(by plaxx)
The patch in the branch I just linked allows me to authenticate and backup w/o the hostname hack.

**Comment by Germar** [comment]
(by plaxx)
Forget the patch. After 30Gb of transfer something failed (network-wise I think). Then I got a password prompt for the wrong key with a status of "fixing permissions" or something. Patch is thus incomplete.

I'm reverting to the /etc/hosts hack.

At least I tried ;)

**Comment by Germar** [comment]
(by germar)
Thanks for the branch! I'll test it soon.

If you are still not able to take snapshots this could be because you need to add the same to Snapshots.cmd_ssh() in snapshots.py

Maybe I should gather all this ssh options in one single place in config.py. Would make it easier to maintain.

**Comment by Germar** [comment]
(by germar)
Oh, coincidence :D

That's caused by the missing option in cmd_ssh in snapshots.py. Just give it a last try ;-)

**Comment by Germar** [comment]
(by plaxx)
I've updated my patch with a fix in snapshots.py's cmd_ssh() like you said.

Re-running a backup right now. It's going to take a while.

**Comment by Germar** [comment]
(by plaxx)
It worked! I took two snapshots with it. I tried to restore a small file and it worked also.

**Comment by Germar** [comment]
(by plaxx)
Fix available here: https://code.launchpad.net/~plaxx/backintime/explicit-ssh-private-key/+merge/253773
