### ISSUE TITLE
Backintime fails to start with DBusException

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#467]
Under Fedora 22 using trunk revision backintime:1102 I get the following

backintime
WARNING: import keyring failed
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.4/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 437, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 156, in start_app
    cfg = config.Config(config_path)
  File "/usr/share/backintime/common/config.py", line 268, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1036, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib64/python3.4/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.4/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.4/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.4/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

Attempting to run

backintime-qt4
WARNING: import keyring failed
Traceback (most recent call last):
  File "./app.py", line 40, in <module>
    from PyQt4.QtGui import *
ImportError: No module named 'PyQt4'

But checking ... : rpm -q PyQt4 shows it installed with version PyQt4-4.11.3-5.fc22.x86_64

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-06-26T12:37:42Z
 * owner: 3g-ubuntu
 * the launchpad url was https://bugs.launchpad.net/bugs/1469151

**Comment by Germar** [comment]
(by germar)
I've no knowledge of Fedora but for me https://apps.fedoraproject.org/packages/PyQt4/contents looks like this is only for Python2. You need to install PyQt4 for Python3.

To verify you can run:
python3 -c "from PyQt4.QtGui import *; import dbus.mainloop.qt"

**Comment by Germar** [comment]
(by 3g-ubuntu)
Thanks for the reply. Installing python3-PyQt4 (which also bought in  python3-sip) fixed the backintime-qt4 and the stacktrace from backintime !

The only remaining thing is I get "WARNING: import keyring failed" - any ideas on that please?

I will fully test it when I get into work with my external backup drive.

**Comment by Germar** [comment]
(by germar)
Please install python3-keyring
https://apps.fedoraproject.org/packages/python3-keyring/overview/

**Comment by Germar** [comment]
(by 3g-ubuntu)
And that completely solves it :-) Brilliant!

Could a note on these packages being required be added to the documentation? That would be really helpful for people building from source.

**Comment by Germar** [comment]
(by 3g-ubuntu)
Sigh. My mistake; it is in the documentation - so chalk this down to user error and not reading properly. Apologies....

**Comment by Germar** [comment]
(by germar)
No worries. I'll close this as this is not a bug
