### ISSUE TITLE
Smart remove bug - positional argument

### ISSUE THREAD

**Issue by dinoboy197** [bit-team/backintime#538]
Note to @dinoboy197 - just found this tonight. Note to myself to fix.

Smart remove fails:
```
Traceback (most recent call last):
  File "/home/traack/Programming/github/dinoboy197/backintime/common/backintime.py", line 1026, in <module>
    start_app()
  File "/home/traack/Programming/github/dinoboy197/backintime/common/backintime.py", line 469, in start_app
    args.func(args)
  File "/home/traack/Programming/github/dinoboy197/backintime/common/backintime.py", line 685, in backup
    ret = take_snapshot(cfg, force)
  File "/home/traack/Programming/github/dinoboy197/backintime/common/backintime.py", line 78, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/home/traack/Programming/github/dinoboy197/backintime/common/snapshots.py", line 791, in take_snapshot
    self._free_space( now )
  File "/home/traack/Programming/github/dinoboy197/backintime/common/snapshots.py", line 1526, in _free_space
    self.smart_remove( now, keep_all, keep_one_per_day, keep_one_per_week, keep_one_per_month )
  File "/home/traack/Programming/github/dinoboy197/backintime/common/snapshots.py", line 1379, in smart_remove
    keep_snapshots = self._smart_remove_keep_all_( snapshots, keep_snapshots, now - datetime.timedelta( days=keep_all-1), now + datetime.timedelta(days=1) )
  File "/home/traack/Programming/github/dinoboy197/backintime/common/snapshots.py", line 1259, in _smart_remove_keep_all_
    min_id = SID(min_date)
TypeError: __init__() missing 1 required positional argument: 'cfg'
```

**Comment by Germar** [comment]
Fixed it. Was the same in settingsdialog. Good thing is, that this wasn't published yet. But it shows again, how important unittests are.

**Comment by dinoboy197** [comment]
Thanks Germar!
