### ISSUE TITLE
%configure macro of fedora not working

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#547]
Hi all,

I am currently reviving the backintime package in fedora. I stumbled across the problem, that the configure script of bit does not work with the %configure macro we usually are advised to use in fedora.
I attach the result, when using both the ./configure call and the %configure macro and I would like to ask if it would be possible to fix this or give me some arguments to convince fellow packagers, why it's better to use ./configure directly.

Cheers,
Johannes

```
Mock Version: 1.2.14
Mock Version: 1.2.14
ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target noarch --nodeps /builddir/build/SPECS/backintime.spec'], user='mockbuild'shell=Falseenv={'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOSTNAME': 'mock', 'TERM': 'vt100', 'LANG': 'en_US.UTF-8', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'}logger=<mockbuild.trace_decorator.getLog object at 0x7f8fd2165c18>gid=425timeout=172800printOutput=Falseuid=1000chrootPath='/var/lib/mock/f23-build-5060677-582146/root')
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target noarch --nodeps /builddir/build/SPECS/backintime.spec'] with env {'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOSTNAME': 'mock', 'TERM': 'vt100', 'LANG': 'en_US.UTF-8', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'} and shell False
warning: Could not canonicalize hostname: buildvm-02-nfs.phx2.fedoraproject.org
Building target platforms: noarch
Building for target noarch
Wrote: /builddir/build/SRPMS/backintime-1.1.12-1.fc23.src.rpm
Child return code was: 0
LEAVE do --> 

ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/backintime.spec '], user='mockbuild'shell=Falseenv={'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOSTNAME': 'mock', 'TERM': 'vt100', 'LANG': 'en_US.UTF-8', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'}private_network=Truelogger=<mockbuild.trace_decorator.getLog object at 0x7f8fd2165c18>gid=425timeout=172800printOutput=Falseuid=1000chrootPath='/var/lib/mock/f23-build-5060677-582146/root')
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/backintime.spec '] with env {'SHELL': '/bin/bash', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOSTNAME': 'mock', 'TERM': 'vt100', 'LANG': 'en_US.UTF-8', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'} and shell False
Building target platforms: noarch
Building for target noarch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.zwbXKb
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf backintime-1.1.12
+ /usr/bin/gzip -dc /builddir/build/SOURCES/backintime-1.1.12.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd backintime-1.1.12
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.aAROc3
+ umask 022
+ cd /builddir/build/BUILD
+ cd backintime-1.1.12
+ sed -i s/Icon=document-save/Icon=backintime/g qt4/backintime-qt4.desktop
+ sed -i s/Icon=document-save/Icon=backintime/g qt4/backintime-qt4-root.desktop
+ pushd common
~/build/BUILD/backintime-1.1.12/common ~/build/BUILD/backintime-1.1.12
+ ./configure --no-fuse-group --python3
which: no py.test-3 in (/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin)
which: no coverage in (/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin)
All OK. Now run:
    make
    sudo make install
+ make -j4
msgfmt -o po/zh_TW.mo po/zh_TW.po
msgfmt -o po/zh_CN.mo po/zh_CN.po
msgfmt -o po/uk.mo po/uk.po
msgfmt -o po/tr.mo po/tr.po
msgfmt -o po/th.mo po/th.po
msgfmt -o po/sv.mo po/sv.po
msgfmt -o po/sr.mo po/sr.po
msgfmt -o po/sl.mo po/sl.po
msgfmt -o po/sk.mo po/sk.po
msgfmt -o po/ru.mo po/ru.po
msgfmt -o po/ro.mo po/ro.po
msgfmt -o po/pt_BR.mo po/pt_BR.po
msgfmt -o po/pt.mo po/pt.po
msgfmt -o po/pl.mo po/pl.po
msgfmt -o po/nn.mo po/nn.po
msgfmt -o po/nl.mo po/nl.po
msgfmt -o po/nb.mo po/nb.po
msgfmt -o po/lt.mo po/lt.po
msgfmt -o po/ko.mo po/ko.po
msgfmt -o po/jv.mo po/jv.po
msgfmt -o po/ja.mo po/ja.po
msgfmt -o po/it.mo po/it.po
msgfmt -o po/is.mo po/is.po
msgfmt -o po/id.mo po/id.po
msgfmt -o po/hu.mo po/hu.po
msgfmt -o po/hr.mo po/hr.po
msgfmt -o po/he.mo po/he.po
msgfmt -o po/gl.mo po/gl.po
msgfmt -o po/fr.mo po/fr.po
msgfmt -o po/fo.mo po/fo.po
msgfmt -o po/fi.mo po/fi.po
msgfmt -o po/eu.mo po/eu.po
msgfmt -o po/et.mo po/et.po
msgfmt -o po/es.mo po/es.po
msgfmt -o po/eo.mo po/eo.po
msgfmt -o po/en_GB.mo po/en_GB.po
msgfmt -o po/en_CA.mo po/en_CA.po
msgfmt -o po/el.mo po/el.po
msgfmt -o po/de.mo po/de.po
msgfmt -o po/da.mo po/da.po
msgfmt -o po/cs.mo po/cs.po
msgfmt -o po/ca.mo po/ca.po
msgfmt -o po/bs.mo po/bs.po
msgfmt -o po/bg.mo po/bg.po
msgfmt -o po/ar.mo po/ar.po
#man pages
for i in $(ls -1 man/C/); do case $i in *.gz|*~) continue;; *) gzip -n --best -c man/C/$i > man/C/${i}.gz;; esac; done
#config-examples
gzip -n --best -c config-example-local > config-example-local.gz
gzip -n --best -c config-example-ssh > config-example-ssh.gz
+ popd
~/build/BUILD/backintime-1.1.12
~/build/BUILD/backintime-1.1.12/qt4 ~/build/BUILD/backintime-1.1.12
+ pushd qt4
+ CFLAGS='-O2 -g -march=pentium3'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -march=pentium3'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -march=pentium3 -I/usr/lib/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -march=pentium3 -I/usr/lib/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ export LDFLAGS
+ '[' 1 = 1 ']'
+++ dirname ./configure
++ find . -name config.guess -o -name config.sub
+ '[' 1 = 1 ']'
+ '[' x '!=' x-specs=/usr/lib/rpm/redhat/redhat-hardened-ld ']'
++ find . -name ltmain.sh
+ ./configure --build=i386-redhat-linux-gnu --host=i386-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --python3
Usage:
./configure [--python | --python3]
--python
\tuse 'python' to start Python3
--python3
\tuse 'python3' to start Python3
+ make -j4
make: *** No targets specified and no makefile found.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.aAROc3 (%build)
    Bad exit status from /var/tmp/rpm-tmp.aAROc3 (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/backintime.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 526, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps  /builddir/build/SPECS/backintime.spec 
LEAVE do --> EXCEPTION RAISED
`

```

**Comment by Germar** [comment]
Could you please show me your build script? The build in `common` is fine. But in `qt4` there are lots of args that our `configure` script doesn't handle. Can you remove them? Or are they added by a wrapper script?

We could change `configure` to just ignore unknown args. At the moment it will error out on unknown args and show `usage`

**Comment by hannes101** [comment]
Thanks for the quick reply and the help! The args are expanded from the %configure macro we are using. I don't know if ignoring them is the best way, perhaps they might be useful?
I uploaded the spec, which is used to build the rpm. https://hannes.fedorapeople.org/backintime.spec

Thanks again,
Johannes

**Comment by buhtzz** [comment]
@hannes101 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

@emtiu Distro-specific (Fedora), Infrastructure (build script)

**Comment by hannes101** [comment]
No, that can be safely closed.
