### ISSUE TITLE
BIT cannot recover partial snapshot on cifs mounted drive

### ISSUE THREAD

**Issue by simgunz** [bit-team/backintime#583]
I usually perform beckups on a cifs mounted drive and it works fine. 
The drive is mounted via fstab with the following options:
users,noauto,credentials=/credentialfiles

When backintime tries to recover a failed snapshot I get the following errors

A lot of:
`chmod: changing permissions of '/myfile' Permission denied`

and finally

```
WARNING: [common/snapshots.py:1192 Snapshots._take_snapshot] Command "find "/media/.../3/new_snapshot" -type d -exec chmod u+wx "{}" +" returns 256
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 567, in aliasParser
    newArgs.func(newArgs)
  File "/usr/share/backintime/common/backintime.py", line 626, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 1044, in take_snapshot
    ret_val, ret_error = self._take_snapshot( snapshot_id, now, include_folders )
  File "/usr/share/backintime/common/snapshots.py", line 1196, in _take_snapshot
    os.chmod(file, mode | stat.S_IWUSR)
PermissionError: [Errno 13] Permission denied: '/media/.../simone/3/new_snapshot/backup'
```

Indeed I cannot change permission of those folders manually, but I can create and remove files and folder from the  drive.

backintime-qt4 shows: "Found leftover 'new_snapshot' which can be continued. " which is not very informative.

How can I solve this?

**Comment by Germar** [comment]
Please manually remove the file `/media/.../simone/3/new_snapshot/save_to_continue`. Bit should delete the broken snapshot and start new from scratch.

**Comment by simgunz** [comment]
Yes that worked. Shouldn't this be done automatically, if the snapshot cannot be continued?

**Comment by Germar** [comment]
I'll add a fallback for this...
