### ISSUE TITLE
Backintime fails to run with dbus errors

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#609]
In the last few days, backintime stopped working for me, with the error below. Around the same time, I updated from `1.1.12.r226.gd26d259-1` to `1.1.12.r243.gdf13c19-1`, using Arch Linux's AUR package. I tried updating to the latest `1.1.12.r246.g684211d-1`, but this produces the same error as below.

I'm also running dbus 1.10.8-1, but it hasn't been updated for a while (nor has any other package with `dbus` in its name).

I just tried installing the previous working version, `d26d259`, and this works fine. I'm happy to troubleshoot more if necessary, although I'm not sure if `git bisect` will work if backintime is not installed?

```
$ sudo nice -n 19 ionice -c2 -n7 backintime backup
Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1052, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 485, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 619, in aliasParser
    newArgs.func(newArgs)
  File "/usr/share/backintime/common/backintime.py", line 704, in backup
    cfg = getConfig(args)
  File "/usr/share/backintime/common/backintime.py", line 637, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 239, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1658, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
```

**Comment by Germar** [comment]
I ported BIT to Qt5 recently. I already left a note for the AUR Package Maintainer to update the backintime-git package to `python-pyqt5`. For now you can manually install `python-pyqt5`.

**Comment by protist** [comment]
Thank you for the quick response! (Also, tangentially related, is there a plan to tag a new release soon, or should we continue using the -git version for the next little while?) Thanks again!

**Comment by Germar** [comment]
I'm planing to make a new major release 1.2.0 but there is still some work to do. So it will take some month until next release.

**Comment by Germar** [comment]
AUR package is up-to-date

**Comment by protist** [comment]
I just updated, but now I'm getting the following error (I'm happy to open a new issue if you'd prefer).

```
$ backintime-qt4_polkit

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Mountpoint /root/.local/share/backintime/mnt/6A5D466C/mountpoint is already mounted
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 1539, in <module>
    mainWindow = MainWindow(cfg, appInstance, qapp)
  File "/usr/share/backintime/qt4/app.py", line 501, in __init__
    self.updateProfiles()
  File "/usr/share/backintime/qt4/app.py", line 596, in updateProfiles
    self.updateProfile()
  File "/usr/share/backintime/qt4/app.py", line 601, in updateProfile
    self.updateTimeLine()
  File "/usr/share/backintime/qt4/app.py", line 864, in updateTimeLine
    thread.addSnapshot.connect(self.timeLine.addSnapshot)
TypeError: decorated slot has no signature compatible with FillTimeLineThread.addSnapshot[SID]
```

**Comment by Germar** [comment]
Please try again with current master

**Comment by protist** [comment]
I don't get any errors on the command line now, but after the `type 'backintime --license' for details` line, no window appeared. I got bored after a few minutes and killed backintime, then tried again. This time there was an immediate error about not being able to ping my server, as I'm not on the same network at the moment. Backintime then crashed.
```
$ backintime-qt4_polkit

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

ERROR: /root/.local/share/backintime/mnt/1_15426/backintime/protist-XPS-17/root/1 does not exist
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 1509, in run
    for sid in snapshots.iterSnapshots(self.config):
  File "/usr/share/backintime/common/snapshots.py", line 2486, in iterSnapshots
    for item in os.listdir(cfg.snapshotsFullPath()):
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/backintime/mnt/1_15426/backintime/protist-XPS-17/root/1'
/usr/bin/backintime-qt4: line 35: 15426 Aborted                 (core dumped) ssh-agent python3 ${APP_PATH}/app.py "$@"
```
