### ISSUE TITLE
Can't launch BIT (dbus issue?) - Ubuntu 16.10

### ISSUE THREAD

**Issue by bleutner** [bit-team/backintime#677]
Hi. 

I'm somewhat lost in fixing this issue. I'm trying to get backintime to launch on a fresh Ubuntu Gnome 16.10 install. I tried the stable release (1.1.2) and testing (1.2) from your ppas but it always fails as outlined below.

I tried with:
* reinstalling python-pyqt5 as you suggested in #609 
* reinstalling python-dbus and python3-dbus

but nothing helped. Any ideas or pointers?

Thanks,
Benjamin

```
Back In Time
Version: 1.2.0~alpha12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/local/lib/python3.5/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/local/lib/python3.5/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1164, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 520, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 668, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 280, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1670, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/local/lib/python3.5/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/local/lib/python3.5/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/local/lib/python3.5/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/local/lib/python3.5/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/local/lib/python3.5/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
```

**Comment by Germar** [comment]
I wasn't able to reproduce this on a fresh Ubuntu Gnome 16.10 VM.

Does the `serviceHelper` run after reboot? `ps aux | grep [b]ackintime` should print something like this:

```
root  2261  0.5  1.0 120704 22200 ?    S  22:19   0:00 /usr/bin/python3 /usr/share/backintime/qt/serviceHelper.py
```

If not, please try to run it in Terminal and post the output:
```
sudo python3 /usr/share/backintime/qt/serviceHelper.py
```

**Comment by bleutner** [comment]
I can't reproduce it either on other machines, all of which run Ubuntu Gnome 16.10.
Only this one is broken.

`ps aux | grep [b]ackintime` returns nothing. 

Starting the serviceHelper gives me:
```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/serviceHelper.py", line 74, in <module>
    import dbus.mainloop.pyqt5
ImportError: No module named 'dbus.mainloop.pyqt5'
```

However, the dbus.mainloop.pyqt5 package is installed (purge + reinstall also doesn't change anything)

```
dpkg -l | grep '^ii' | grep dbus
ii  at-spi2-core                                2.20.2-1ubuntu1                             amd64        Assistive Technology Service Provider Interface (dbus core)
ii  dbus                                        1.10.10-1ubuntu1.1                          amd64        simple interprocess messaging system (daemon and utilities)
ii  dbus-user-session                           1.10.10-1ubuntu1.1                          all          simple interprocess messaging system (systemd --user integration)
ii  dbus-x11                                    1.10.10-1ubuntu1.1                          amd64        simple interprocess messaging system (X11 deps)
ii  gir1.2-dbusmenu-glib-0.4:amd64              16.04.1+16.10.20160927.2-0ubuntu1           amd64        typelib file for libdbusmenu-glib4
ii  libdbus-1-3:amd64                           1.10.10-1ubuntu1.1                          amd64        simple interprocess messaging system (library)
ii  libdbus-1-3:i386                            1.10.10-1ubuntu1.1                          i386         simple interprocess messaging system (library)
ii  libdbus-1-dev:amd64                         1.10.10-1ubuntu1.1                          amd64        simple interprocess messaging system (development headers)
ii  libdbus-glib-1-2:amd64                      0.108-1                                     amd64        simple interprocess messaging system (GLib-based shared library)
ii  libdbus-glib-1-dev                          0.108-1                                     amd64        simple interprocess messaging system (GLib interface)
ii  libdbusmenu-glib4:amd64                     16.04.1+16.10.20160927.2-0ubuntu1           amd64        library for passing menus over DBus
ii  libdbusmenu-gtk3-4:amd64                    16.04.1+16.10.20160927.2-0ubuntu1           amd64        library for passing menus over DBus - GTK+ version
ii  libdbusmenu-gtk4:amd64                      16.04.1+16.10.20160927.2-0ubuntu1           amd64        library for passing menus over DBus - GTK+ version
ii  libdbusmenu-qt2:amd64                       0.9.3+16.04.20160218-0ubuntu1               amd64        Qt implementation of the DBusMenu protocol
ii  libdleyna-connector-dbus-1.0-1:amd64        0.2.0-1                                     amd64        DBus connector module for the dLeyna services
ii  libnet-dbus-perl                            1.1.0-4                                     amd64        Perl extension for the DBus bindings
ii  libqt4-dbus:amd64                           4:4.8.7+dfsg-7ubuntu1                       amd64        Qt 4 D-Bus module
ii  libqt5dbus5:amd64                           5.6.1+dfsg-3ubuntu6~4                       amd64        Qt 5 D-Bus module
ii  libqtdbus4:amd64                            4:4.8.7+dfsg-7ubuntu1                       amd64        Qt 4 D-Bus module library
ii  python-dbus                                 1.2.4-1                                     amd64        simple interprocess messaging system (Python interface)
ii  python-dbus-dbg                             1.2.4-1                                     amd64        debug build of the D-Bus Python 2 interface
ii  python3-dbus                                1.2.4-1                                     amd64        simple interprocess messaging system (Python 3 interface)
ii  python3-dbus-dbg                            1.2.4-1                                     amd64        debug build of the D-Bus Python 3 interface
ii  python3-dbus.mainloop.pyqt5                 5.7+dfsg-2                                  amd64        D-Bus Qt main loop support for Python 3
```
I'm not familiar with how python handles its modules. Here are all python mainloop related files:
```
locate "*python*mainloop*"
/usr/lib/python2.7/dist-packages/dbus/mainloop
/usr/lib/python2.7/dist-packages/dbus/mainloop/__init__.py
/usr/lib/python2.7/dist-packages/dbus/mainloop/__init__.pyc
/usr/lib/python2.7/dist-packages/dbus/mainloop/glib.py
/usr/lib/python2.7/dist-packages/dbus/mainloop/glib.pyc
/usr/lib/python3/dist-packages/dbus/mainloop
/usr/lib/python3/dist-packages/dbus/mainloop/__init__.py
/usr/lib/python3/dist-packages/dbus/mainloop/__pycache__
/usr/lib/python3/dist-packages/dbus/mainloop/glib.py
/usr/lib/python3/dist-packages/dbus/mainloop/pyqt5.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/dbus/mainloop/__pycache__/__init__.cpython-35.pyc
/usr/lib/python3/dist-packages/dbus/mainloop/__pycache__/glib.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/dbus/mainloop
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__init__.py
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__pycache__
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/glib.py
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__pycache__/__init__.cpython-35.opt-1.pyc
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__pycache__/__init__.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__pycache__/glib.cpython-35.opt-1.pyc
/usr/local/lib/python3.5/dist-packages/dbus/mainloop/__pycache__/glib.cpython-35.pyc
/usr/share/doc/python3-dbus.mainloop.pyqt5
/usr/share/doc/python3-dbus.mainloop.pyqt5/changelog.Debian.gz
/usr/share/doc/python3-dbus.mainloop.pyqt5/copyright
/var/cache/apt/archives/python-dbus.mainloop.pyqt5-dbg_5.7+dfsg-2_amd64.deb
/var/cache/apt/archives/python-dbus.mainloop.pyqt5_5.7+dfsg-2_amd64.deb
/var/cache/apt/archives/python3-dbus.mainloop.pyqt5-dbg_5.7+dfsg-2_amd64.deb
/var/cache/apt/archives/python3-dbus.mainloop.qt-dbg_4.11.4+dfsg-2_amd64.deb
/var/lib/dpkg/info/python3-dbus.mainloop.pyqt5.list
/var/lib/dpkg/info/python3-dbus.mainloop.pyqt5.md5sums
```

**Comment by Germar** [comment]
You have a custom Python3.5 version in `/usr/local/lib/python3.5` which doesn't has a `mainloop/pyqt5.[...].so`. Please either compile it for your custom Python installation or edit your `PATH` environ to use Ubuntus `/usr/bin/python3` by default.

**Comment by bleutner** [comment]
You are right, this was the issue (although I've got no clue how this came to be).
Thanks a lot for helping and sorry for wasting your time.
Keep up the great work!

**Comment by Germar** [comment]
No worries

**Comment by steadfasterX** [comment]
I'm not able to start BIT as well:

```
/usr/share/backintime/common/backintime.py

Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 874, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 463, in start_app
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 584, in getConfig
    cfg = config.Config(args.config)
  File "/usr/share/backintime/common/config.py", line 272, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1213, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
```

`locate "*python*mainloop*"` gives back:

```
/usr/lib/python2.7/site-packages/dbus/mainloop
/usr/lib/python2.7/site-packages/dbus/mainloop/__init__.py
/usr/lib/python2.7/site-packages/dbus/mainloop/__init__.pyc
/usr/lib/python2.7/site-packages/dbus/mainloop/__init__.pyo
/usr/lib/python2.7/site-packages/dbus/mainloop/glib.py
/usr/lib/python2.7/site-packages/dbus/mainloop/glib.pyc
/usr/lib/python2.7/site-packages/dbus/mainloop/glib.pyo
/usr/lib/python3.6/site-packages/dbus/mainloop
/usr/lib/python3.6/site-packages/dbus/mainloop/qt.so
/usr/lib/python3.7/site-packages/dbus/mainloop
/usr/lib/python3.7/site-packages/dbus/mainloop/__init__.py
/usr/lib/python3.7/site-packages/dbus/mainloop/__pycache__
/usr/lib/python3.7/site-packages/dbus/mainloop/glib.py
/usr/lib/python3.7/site-packages/dbus/mainloop/pyqt5.so
/usr/lib/python3.7/site-packages/dbus/mainloop/__pycache__/__init__.cpython-37.opt-1.pyc
/usr/lib/python3.7/site-packages/dbus/mainloop/__pycache__/__init__.cpython-37.pyc
/usr/lib/python3.7/site-packages/dbus/mainloop/__pycache__/glib.cpython-37.opt-1.pyc
/usr/lib/python3.7/site-packages/dbus/mainloop/__pycache__/glib.cpython-37.pyc
/usr/share/doc/dbus-python/dbus.mainloop.html
/usr/share/doc/dbus-python/_sources/dbus.mainloop.rst.txt
```

python -V
`Python 3.7.1`

I have removed sip and pyqt5 with pip3 and re-installed both from my distro repos.
I use Manjaro Linux. Any help highly appreciated!

**Comment by steadfasterX** [comment]
OK finally fixed it in 2 steps:

## Step 1: Remove pip installs

```
sudo pip3 uninstall pyqt4
sudo pip3 uninstall pyqt5
sudo pip3 uninstall sip
```

## Step 2: Force re-install distribution packages

I had python pyqt4 and 5 and sip installed besides the pip3 stuff so it still failed.
So I re-installed them (following is on Arch/Manjaro):

`trizen -S --noconfirm sip python-sip-pyqt5 python-sip python-pyqt4 python-pyqt5`

Now BIT starts again :) Thanks god.. 2 months my daily backup make me scared..
