### ISSUE TITLE
serviceHelper does not start with python3

### ISSUE THREAD

**Issue by jdm12989** [bit-team/backintime#763]
This may be a problem with my python installation, but when running the command `/usr/bin/python3 -Es /usr/share/backintime/qt/serviceHelper.py` I receive the following error.

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/serviceHelper.py", line 75, in <module>
    from PyQt5.QtCore import QCoreApplication
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so)`

```
BackInTime version 1.2.0~alpha16
OS: Linux Mint 18.1

Using /usr/bin/python serviceHelper launches fine.

**Comment by Germar** [comment]
You can't run `serviceHelper` manually. It will always fail with `DBusException`. What exactly do you try to achieve?

**Comment by jdm12989** [comment]
This error occurs whether I run it manually or it is in the net.launchpad.backintime.serviceHelper.service file.

```
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Sat 2017-05-20 13:26:47 EDT; 4h 1min ago
     Docs: man:dbus-daemon(1)
 Main PID: 1171 (dbus-daemon)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/dbus.service
           └─1171 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation

May 20 17:27:44 McMint dbus[1171]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
May 20 17:27:56 McMint dbus[1171]: [system] Activating service name='net.launchpad.backintime.serviceHelper' (using servicehelper)
May 20 17:27:58 McMint net.launchpad.backintime.serviceHelper[1171]: Traceback (most recent call last):
May 20 17:27:58 McMint net.launchpad.backintime.serviceHelper[1171]:   File "/usr/share/backintime/qt/serviceHelper.py", line 75, in <module>
May 20 17:27:58 McMint net.launchpad.backintime.serviceHelper[1171]:     from PyQt5.QtCore import QCoreApplication
May 20 17:27:58 McMint net.launchpad.backintime.serviceHelper[1171]: ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so)
May 20 17:27:58 McMint dbus[1171]: [system] Activated service 'net.launchpad.backintime.serviceHelper' failed: Launch helper exited with unknown return code 1
May 20 17:28:09 McMint dbus[1171]: [system] Failed to activate service 'org.bluez': timed out
May 20 17:28:34 McMint dbus[1171]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
May 20 17:28:34 McMint dbus[1171]: [system] Successfully activated service 'org.freedesktop.hostname1'
```

The only work around I have found thus far is to modify the net.launchpad.backintime.serviceHelper.service file to launch serviceHelper with python vs python3.

**Comment by Germar** [comment]
It shouldn't work with `python` at all because `python` is version 2 and BiT is written for Python >= 3.3

Please post the output of 

```
python --version
python3 --version
```

**Comment by jdm12989** [comment]
```
$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
```

**Comment by Germar** [comment]
Please remove `pyqt5` and `sip` from `pip3`. Only use dist packages
```
sudo -H pip3 uninstall sip pyqt5
```
