### ISSUE TITLE
Backintime does not start.

### ISSUE THREAD

**Issue by Dominik52** [bit-team/backintime#771]
I use ubuntu 16.04 LTS 64 Bit
The terminal gives out the following after the command "backintime":

```
Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1164, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 520, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 668, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1696, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process net.launchpad.backintime.serviceHelper received signal 11
```

**Comment by GabrielGirard** [comment]
I have exactly the same problem with backintime on Ubuntu16.04.

**Comment by colinl** [comment]
Is this a dup of #677

**Comment by Germar** [comment]
Please remove `pyqt5` and `sip` from `pip3`. Only use dist packages
```
sudo -H pip3 uninstall sip pyqt5
```

**Comment by CristianCantoro** [comment]
I am experiencing the same problem on Ubuntu 16.04 even if I have uninstalled `sip` and `pyqt5`. Any further info to troubleshoot the problem, please?

**Comment by Germar** [comment]
Please remove all python packages which where not installed from Ubuntu repositories. You can find them with:
```
find /usr/local/lib/python*/dist-packages -maxdepth 2 -name __init__.py | xargs realpath | LANG=en xargs dpkg -S 2>&1 | grep 'no path found'
```

Output will look like
```
dpkg-query: no path found matching pattern /usr/local/lib/python3.4/dist-packages/docutils/__init__.py
dpkg-query: no path found matching pattern /usr/local/lib/python3.4/dist-packages/coveralls/__init__.py
```
In this case remove them with `sudo pip3 uninstall docutils coveralls`

**Comment by CristianCantoro** [comment]
I am a little weary to do that because I fear that might break some other software that I am using. I have more than 50 packages installed via pip just for python 3.5.
