### ISSUE TITLE
another dbus issue when using pyqt5

### ISSUE THREAD

**Issue by TheoRet** [bit-team/backintime#790]
Hello, I am on Linux Mint MATE 18.2 with BIT v. 1.2.0~alpha16.

BIT does not start and gives the following error code (the same as in #758 btw):
```
Back In Time
Version: 1.2.0~alpha16

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1164, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 520, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 668, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 280, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1696, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
```

Similar to #763 I get a qt version error when running ` systemctl status dbus.service`:
```
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2017-07-09 20:02:41 CEST; 26s ago
     Docs: man:dbus-daemon(1)
 Main PID: 854 (dbus-daemon)
   CGroup: /system.slice/dbus.service
           ├─ 854 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
           └─1742 /usr/bin/msd-datetime-mechanism

Jul 09 20:02:45 d-Aspire-VN7-572G net.launchpad.backintime.serviceHelper[854]: Traceback (most recent call last):
Jul 09 20:02:45 d-Aspire-VN7-572G net.launchpad.backintime.serviceHelper[854]:   File "/usr/share/backintime/qt/serviceHelper.py", line 75, in <module>
Jul 09 20:02:45 d-Aspire-VN7-572G net.launchpad.backintime.serviceHelper[854]:     from PyQt5.QtCore import QCoreApplication
Jul 09 20:02:45 d-Aspire-VN7-572G net.launchpad.backintime.serviceHelper[854]: ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so)
Jul 09 20:02:45 d-Aspire-VN7-572G dbus[854]: [system] Activated service 'net.launchpad.backintime.serviceHelper' failed: Launch helper exited with unknown return code 1
Jul 09 20:02:46 d-Aspire-VN7-572G dbus[854]: [system] Successfully activated service 'org.freedesktop.RealtimeKit1'
Jul 09 20:02:46 d-Aspire-VN7-572G dbus[854]: [system] Activating service name='org.mate.SettingsDaemon.DateTimeMechanism' (using servicehelper)
Jul 09 20:02:46 d-Aspire-VN7-572G dbus[854]: [system] Successfully activated service 'org.mate.SettingsDaemon.DateTimeMechanism'
Jul 09 20:02:55 d-Aspire-VN7-572G dbus[854]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jul 09 20:02:55 d-Aspire-VN7-572G dbus[854]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
```

**Comment by TheoRet** [comment]
Maybe the problem is that I have two pyqt5 versions (one from the repositories in /usr/lib/..., and one manually installed with pip3 in /usr/local/lib/python3.5)?  
compare: https://stackoverflow.com/questions/39129615/pyqt5-not-finding-installed-qt5-library

So I ran `sudo pip3 uninstall pyqt5` and restarted the computer, to get new error messages:
```
backintime

Back In Time
Version: 1.2.0~alpha16

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1164, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 520, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 668, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 280, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1696, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process net.launchpad.backintime.serviceHelper received signal 11
```

and 

```
systemctl status dbus.service
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2017-07-09 20:24:44 CEST; 1min 9s ago
     Docs: man:dbus-daemon(1)
 Main PID: 868 (dbus-daemon)
   CGroup: /system.slice/dbus.service
           └─868 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation

Jul 09 20:24:47 d-Aspire-VN7-572G dbus[868]: [system] Successfully activated service 'org.freedesktop.UDisks2'
Jul 09 20:24:48 d-Aspire-VN7-572G dbus[868]: [system] Activating service name='net.launchpad.backintime.serviceHelper' (using servicehelper)
Jul 09 20:24:48 d-Aspire-VN7-572G dbus[868]: [system] Activated service 'net.launchpad.backintime.serviceHelper' failed: Process net.launchpad.backintime.serviceHelper received signal 11
Jul 09 20:24:49 d-Aspire-VN7-572G dbus[868]: [system] Successfully activated service 'org.freedesktop.RealtimeKit1'
Jul 09 20:24:49 d-Aspire-VN7-572G dbus[868]: [system] Activating service name='org.mate.SettingsDaemon.DateTimeMechanism' (using servicehelper)
Jul 09 20:24:49 d-Aspire-VN7-572G dbus[868]: [system] Successfully activated service 'org.mate.SettingsDaemon.DateTimeMechanism'
Jul 09 20:24:58 d-Aspire-VN7-572G dbus[868]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jul 09 20:24:58 d-Aspire-VN7-572G dbus[868]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 09 20:25:46 d-Aspire-VN7-572G dbus[868]: [system] Activating service name='net.launchpad.backintime.serviceHelper' (using servicehelper)
Jul 09 20:25:46 d-Aspire-VN7-572G dbus[868]: [system] Activated service 'net.launchpad.backintime.serviceHelper' failed: Process net.launchpad.backintime.serviceHelper received signal 11
```

At least the qt version issue seems to be resolved.

**Comment by Germar** [comment]
Took me three hours to figure this out :see_no_evil: 

Please remove `sip` with pip3
```
sudo -H pip3 uninstall sip
```

**Comment by TheoRet** [comment]
Thanks a lot!!
I removed and re-installed sip and BIT works now.
