### ISSUE TITLE
GUI doesn't inform about errors in callback-script

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#827]
I was wondering why the bit-gui told me there is no need for a new snapshot when I tried to start one manually. So restarted bit on the bash and found out that my callback-script had a simple `import` error (because my Debian GNU/Linux updated the python environment).

There should be a way that a GUI-only user is informed about things like that. Maybe this is related to the  IPC planed redesign?

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.
```

INFO: Lock
ERROR: user-callback returned 'Traceback (most recent call last):
  File "/home/user/.config/backintime/user-callback", line 17, in <module>
    from plyer import tts
ModuleNotFoundError: No module named 'plyer''
WARNING: user-callback returncode: 1
ERROR: Plugin usercallbackplugin mount failed: 
INFO: Mountpoint /home/user/.local/share/backintime/mnt/9AB43DFF/mountpoint is already mounted
ERROR: user-callback returned 'Traceback (most recent call last):
  File "/home/user/.config/backintime/user-callback", line 17, in <module>
    from plyer import tts
ModuleNotFoundError: No module named 'plyer''
WARNING: user-callback returncode: 1
INFO: A plugin prevented the backup
ERROR: user-callback returned 'Traceback (most recent call last):
  File "/home/user/.config/backintime/user-callback", line 17, in <module>
    from plyer import tts
ModuleNotFoundError: No module named 'plyer''
WARNING: user-callback returncode: 1
ERROR: Plugin usercallbackplugin unmount failed: 
INFO: Mountpoint /home/user/.local/share/backintime/mnt/9AB43DFF/mountpoint still in use. Keep mounted
INFO: Unlock

```

**Comment by Germar** [comment]
The current way of handling status messages in GUI is more like an educated guess. Can't fix this without the new IPC

**Comment by aryoda** [comment]
> found out that my callback-script had a simple import error (because my Debian GNU/Linux updated the python environment).
@buhtzz I am surprised that you are using python in the user-callback script. Do you still have a minimal user-callback script for me for reproducing this error?

Generally I think the existing error handling of user-callback calls in BiT looks very good and it would perhaps be a better solution to add `set -e` to the user-callback to fail on every error (non-zero exit code) so that the error immediately comes back to BiT and can be recognized (otherwise only the exit code of the last command is returned AFIR and this "shadow" the earlier error).

**Comment by aryoda** [comment]
## Indicative analysis

I have analyzed the the issue a little bit to understand how user-callback script errors are recognized and (re)thrown as exceptions at the moment but it will be not easy to find a simple way to inform the user about the exceptions.

The basic problem is **not** that user-callback script (runtime) errors are not recognized but that they are not directly and visible fed back to the user via GUI.

### Example with a synchronous call from GUI

If the last command of the script fails by returning a non-zero return code this is recognized by the plugin
and logged as warning and additionally an exception is thrown:

https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/plugins/usercallbackplugin.py#L95-L97

The exception is then handled by the pluginmanager and **only** logged but not fed back to the GUI:

https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/pluginmanager.py#L330-L340

The logger just writes to the console and the syslog:

https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/logger.py#L44-L46

```
WARNING: user-callback returncode: 33
ERROR: Plugin usercallbackplugin unmount failed: 
```

The call stack up to the GUI comprises eg. for an "unmount":

https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/mount.py#L157
https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/mount.py#L261
https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/qt/app.py#L642
https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/qt/app.py#L617
https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/qt/app.py#L1617

Here the exception handling could be changed to bubble-up to the GUI.

### Example of an async call ("take snapshot" button)

Clicking the "take snapshot" button calls

https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/qt/app.py#L873-L875
which then spaws a new process in `takeSnapshotAsync` with `backintime --profile-id 1 backup` as command in
https://github.com/bit-team/backintime/blob/4940192ff37482a0abf329838f25c4ee4c1b0ae5/common/backintime.py#L81

Here exception handling is not possible due to the async out-of-process call.

### Summary

Some user-callback script calls are sync, some async (out-of-process).

For a decent feed-back of (runtime) errors in the user-callback script
- a separate communication channel would be required (as @Germar indicated it above: Eg. via IPC)
- a general concept is required how to present messages to the user (eg. pop-up windows for fatal errors, a summary window after finishing long-running tasks and eg. a permanently visible "live" log output textbox)

Regarding IPC I see these options:
1. via defined text files (eg. implemented in `logger.py`)
2. monitoring and showing the relvant syslog (into which is written by the logger functions)
3. DBus communication
4. ... your proposal goes here ;-)
 
Text-based IPC would also require defined unique keywords and arguments to re-translate the output into feed-back that the user can interpret in the context of GUI...

### Next steps

Implementing this task is too much work for me ATM so I put it back into the box.
When a GUI-redesign is due this would be the right time to implement this task too...

**Comment by buhtz** [comment]
Before implementing a new IPC (#2260) there is the plan to remove/replace the plugin system (#2424). The user callback script is part of that plugin system. After #2424 is solved it might be easy to track and react on errors in user-callback scripts.
