### ISSUE TITLE
no indication that disk is full

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#83]
My disk filled up during a backup. I didn't really notice. I eventually clicked on the system tray icon, and all it did was raise a OK/Cancel dialog saying "save permissions" (that does nothing when either button is pressed).

I ran it again, via the command line. This is the output I got:

INFO: Call rsync to take the snapshot
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/media/Tim Machine/Backup/backintime/new_snapshot/backup/home/tim/Pictures/Photos/2010-04 Easter in Geelong/_IGP4516.JPG": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(302) [receiver=3.0.6]
rsync: connection unexpectedly closed (150885 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
WARNING: Command "rsync -aEAX  -v --delete-excluded  --chmod=Fa-w,D+w --whole-file --delete / "/media/Tim Machine/Backup/backintime/new_snapshot/backup/"" returns 3072
INFO: Save permissions
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 174, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 86, in start_app
    take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 42, in take_snapshot
    snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 424, in take_snapshot
    ret_val = self._take_snapshot( snapshot_id, now, include_folders, ignore_folders, dict, force )
  File "/usr/share/backintime/common/snapshots.py", line 724, in _take_snapshot
    fileinfo.close()
IOError: unknown IO error

Note that it doesn't die, it simply sits there after this. To fix this bug, I think
 - a (gui) alert should be shown, and
 - the process should exit

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-04-30T12:29:01Z
 * owner: gfxmonk
 * the launchpad url was https://bugs.launchpad.net/bugs/572277

**Comment by Germar** [comment]
(by danleweb)
It is not easy to detect disk full (since BIT use an external tool: rsync).
Beta version on the other side tries to detect errors so it won't consider OK a partial backup. For the moment this is all I can do.

**Comment by Germar** [comment]
(by gfxmonk)
Just to clarify, what would I see in the beta version? It sounds like there will be no alert that anything is wrong, but at least it won't claim to have succeeded. Is that correct?

**Comment by Germar** [comment]
(by danleweb)
Correct.

**Comment by Germar** [comment]
(by danleweb)
Errors like "IOError: unknown IO error" are fixed (at least in BIT 1.0).
BIT 1.0 also check in the snapshot really succed.

**Comment by Germar** [comment]
(by gfxmonk)
Great, thanks! :)
