### ISSUE TITLE
backintime finishes with errors: rsync, stat, mkdir...trying to use wrong folder?

### ISSUE THREAD

**Issue by sschwarzmann** [bit-team/backintime#845]
After running for a long time, backintime (1.0.34) stops with error:

```
[E] Error: rsync: readlink_stat("/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/home/<user>/<somepath>") failed: Input/output error (5)
[E] Error: rsync: recv_generator: mkdir "/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/home/<user>/<somepath>" failed: Input/output error (5)
[E] Error: rsync: recv_generator: mkdir "/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/home/<user>/<someotherpath>" failed: Input/output error (5)
[E] Error: rsync: recv_generator: failed to stat "/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/mnt/path/to/file1": Input/output error (5)
[E] Error: rsync: recv_generator: failed to stat "/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/mnt/path/to/file2": Input/output error (5)
...
[E] Error: rsync: recv_generator: failed to stat "/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/mnt/path/to/file9": Input/output error (5)
[E] Can't rename /tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot to /tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/20171207-182817-176
[E] Failed to take snapshot 07.12.2017 18:28:17 !!!
```

The folder `/tmp/backintime/<user>/1_14828/`doesn't exist, don't know why it's looking for that...
There's the folder `/tmp/backintime/<user>/1_14799`

The original files like `/tmp/backintime/<user>/1_14828/backintime/<hostname>/<user>/1/new_snapshot/backup/mnt/path/to/file1` are okay.

I've tried at first sth like [here](https://github.com/bit-team/backintime/issues/597) but that didn't work.

I've seen (on the filesystem where the backups are located) that there was a symlink which was pointing to a non-existing file/folder and renamed it from 

`/media/<user>/backup/back-in-time/4XA,qBZw6Vru7mgyaBZo2cty/B6VGv1Ku04qQIC-uzXo5-gvj/iH6dQTV4SmuPTJvoCqNahRF7/tntV3p6TjP4q,cgvGMkzcerP/GGmbCl0ymCupSTtOusQhJbcY`

to

`/media/<user>/backup/back-in-time/4XA,qBZw6Vru7mgyaBZo2cty/B6VGv1Ku04qQIC-uzXo5-gvj/iH6dQTV4SmuPTJvoCqNahRF7/tntV3p6TjP4q,cgvGMkzcerP/_GGmbCl0ymCupSTtOusQhJbcY`

but that didn't make a difference.

The most recently created folder is

`/media/<user>/backup/back-in-time/4XA,qBZw6Vru7mgyaBZo2cty/B6VGv1Ku04qQIC-uzXo5-gvj/iH6dQTV4SmuPTJvoCqNahRF7/tntV3p6TjP4q,cgvGMkzcerP/GpZ,vNx5yJ7udJNrcsGibjTk`

Any idea how to fix that?

**Comment by Germar** [comment]
1.0.34 is quite old and outdated. Please update to a more recent version (`1.1.24`) and then run `backintime --debug backup`

**Comment by sschwarzmann** [comment]
Hi Germar,

thanks for your help.
1.0.34 is the version from Mint 17 repositories, I've now updated to latest (1.1.24).

After ~12 hours I've stopped `backintime` because it was still saying "save permissions".

The output on the console was:

```
$ backintime-qt4

Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Mountpoint /home/<user>/.local/share/backintime/mnt/20ED4C2C/mountpoint is already mounted
WARNING: Command "rm -rf "/home/<user>/.local/share/backintime/mnt/1_6379/backintime/<host>/<user>/1/new_snapshot/backup"" returns 256
INFO: Compare with old snapshot: 20171028-173635-315
rsync: readlink_stat("/home/<user>/.local/share/backintime/mnt/1_6379/backintime/<host>/<user>/1/20171028-173635-315/backup/home/<user>/<path/to/file>") failed: Input/output error (5)
rsync: recv_generator: failed to stat "/home/<user>/.local/share/backintime/mnt/1_6379/backintime/<host>/<user>/1/20171028-173635-315/backup/mnt/daten/<path/to/file>": Input/output error (5)
...
rsync: recv_generator: failed to stat "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/M<path/to/file>": Input/output error (5)
...

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
WARNING: Command "rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/home/<user>//.local/share/backintime/mnt/1_6379" --exclude="/home/<user>//.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/<user>//" --include="/home/" --include="/mnt/daten/" --include="/mnt/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/<user>//Ubuntu One" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/mnt/daten/lost+found" --exclude="/mnt/daten/.Trash-1000" --include="/home/<user>//**" --include="/mnt/daten/**" --exclude="*" / "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/"" returns 5888
INFO: Create hard-links
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//.config/<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//.config/<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>': Input/output error
...
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>': Input/output error
WARNING: Command "find "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/" -type d -exec chmod u+wx "{}" +" returns 256
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>’: Input/output error
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>’: Input/output error
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>’: Input/output error
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>’: Input/output error
cp: cannot create directory ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/mnt/daten/<path/to/file>’: Input/output error
cp: cannot create directory ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/mnt/daten/<path/to/file>’: Input/output error
cp: cannot create directory ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/mnt/daten/<path/to/file>’: Input/output error
cp: cannot create directory ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/mnt/daten/<path/to/file>’: Input/output error
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>’: Input/output error
...
cp: cannot stat ‘/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>’: Input/output error
WARNING: Command "cp -aRl "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/"* "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/"" returns 256
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//.config/<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//.config/<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/home/<user>//<path/to/file>': Input/output error
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>': Input/output error
...
find: `/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/mnt/daten/<path/to/file>': Input/output error
WARNING: Command "find "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171028-173635-315/backup/" -type d -exec chmod a-w "{}" +" returns 256
INFO: Call rsync to take the snapshot
WARNING: Command "rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/home/<user>//.local/share/backintime/mnt/1_6379" --exclude="/home/<user>//.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/<user>//" --include="/home/" --include="/mnt/daten/" --include="/mnt/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/<user>//Ubuntu One" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/mnt/daten/lost+found" --exclude="/mnt/daten/.Trash-1000" --include="/home/<user>//**" --include="/mnt/daten/**" --exclude="*" / "/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot/backup/" 2>&1" returns 5888
INFO: Save config file
INFO: Save permissions
INFO: Create info file
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 874, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 459, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 635, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 79, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/<user>/apshots.py", line 1050, in take_snapshot
    ret_val, ret_error = self._take_snapshot( snapshot_id, now, include_folders )
  File "/usr/share/backintime/common/<user>/apshots.py", line 1481, in _take_snapshot
    os.rename(new_snapshot_path(), snapshot_path())
PermissionError: [Errno 13] Permission denied: '/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/new_snapshot' -> '/home/<user>//.local/share/backintime/mnt/1_6379/backintime/<host>/<user>//1/20171208-221138-667'
INFO: [qt4systrayicon] end loop

```

If there's anything else I can help with (output, tests), please let me know.

**Comment by sschwarzmann** [comment]
**PUSH**

The problem is still relevant, I've not tried anything new so far, and couldn't backup for quite some weeks. If there's no solution to fix the problem, I may need to start with a new series of backups.

**Comment by Germar** [comment]
Sorry I missed your last post. Please check your destination drive for errors and repair them. If it has a native Linux filesystem (e.g. EXT) you can use `fsck -a /dev/sdXX` where `sdXX` is the device of your destination drive. If it was formatted with NTFS you should rather check and repair it on a Windows machine.

**Comment by sschwarzmann** [comment]
Uh...I was sure that I've checked the filesystem (ext4) for errors before starting this thread, due to the `stat` errors, but when I used `fsck` yesterday it actually found and fixed errors.

Sorry, should have been more diligent.

Backups are working again.

**Comment by colinl** [comment]
On 25 January 2018 at 08:04, sschwarzmann <notifications@github.com> wrote:

> Uh...I was sure that I've checked the filesystem (ext4) for errors before
> starting this thread, due to the stat errors, but when I used fsck
> yesterday it actually found and fixed errors.
>
In that case you may have a failing drive.  Not ideal for a backup.

**Comment by sschwarzmann** [comment]
Yeah, I will have to watch the drive. It's actually brand-new, and I'm not sure whether it could be due to a bad unmount.
