### ISSUE TITLE
Crash due to bad keyring taking precedence (kwalletd)

### ISSUE THREAD

**Issue by j1elo** [bit-team/backintime#860]
System info:
- Back In Time 1.1.24
- OS: Linux Mint 18.3 Sylvia (based on Ubuntu Xenial 16.04)
- Desktop: Cinnamon 3.6.7
- Python: 2.7.12, 3.5.2

The program crashes when trying to create a new profile during the first run after a clean installation, choosing **Local Encrypted** type and **Keyring** key storage. The crash happens _if the KDE Wallet DBUS service is installed_, seemingly because of a wrong answer from the bus request:

```
$ backintime-qt4

Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: mount local_encfs: /media/backup/backintime on /home/juan/.local/share/backintime/mnt/E7BDEDBF/mountpoint
ERROR:dbus.proxies:Introspect error on :1.217:/modules/kwalletd: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1698, in accept
    if self.validate():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1452, in validate
    if not self.save_profile():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1342, in save_profile
    self.config.set_password(password_1, mode = mode)
  File "/usr/share/backintime/common/config.py", line 603, in set_password
    self.pw.set_password(password, profile_id, mode, pw_id)
  File "/usr/share/backintime/common/password.py", line 284, in set_password
    self._set_password_to_keyring(service_name, user_name, password)
  File "/usr/share/backintime/common/password.py", line 292, in _set_password_to_keyring
    return tools.set_password(service_name, user_name, password)
  File "/usr/share/backintime/common/tools.py", line 628, in set_password
    return keyring.set_password(*args)
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3/dist-packages/keyring/backends/kwallet.py", line 182, in set_password
    raise PasswordSetError("Cancelled by user")
keyring.errors.PasswordSetError: Cancelled by user
```

This issue happens right after simply installing the _Kate_ text editor in a cleanly installed Mint 18.3 system. Kate brings as dependency the package `libkf5wallet-bin`, which installs the files `/usr/share/dbus-1/services/org.kde.kwalletd.service` and `/usr/share/dbus-1/services/org.kde.kwalletd5.service`.

I don't know about the internals of how the service discoverability works on DBUS, but as soon as the mentioned files get installed, the crash in Back In Time is reproducible. Likewise, by forcing removal of those files, the issue disappears:

```
$ sudo rm /usr/share/dbus-1/services/org.kde.kwalletd*.service
$ backintime-qt4

Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: mount local_encfs: /media/backup/backintime on /home/juan/.local/share/backintime/mnt/E7BDEDBF/mountpoint
INFO: unmount local_encfs: /media/backup/backintime from /home/juan/.local/share/backintime/mnt/E7BDEDBF/mountpoint
INFO: mount local_encfs: /media/backup/backintime on /home/juan/.local/share/backintime/mnt/E7BDEDBF/mountpoint
INFO: unmount local_encfs: /media/backup/backintime from /home/juan/.local/share/backintime/mnt/E7BDEDBF/mountpoint
```

Seems that by the mere fact of being installed, those service files are taking precedence over the default keyring that comes installed with the system (called _seahorse_ as far as I know), which is the one that works properly.

Setting apart the reasons that KWallet gets pulled as a dependency of other KDE applications, the issue at hand here is that Back In Time is expected to be robust and not crash. The expected behavior is to handle the DBUS request and do whatever is appropriate in this situation. Maybe it could detect that the first DBUS response won't work and try with some other Keyring service provider (which would lead it to communicate with the one that actually works).

**Comment by buhtzz** [comment]
@j1elo There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Bug, Feedback

**Comment by aryoda** [comment]
@j1elo Thanks for reporting this bug. Would it be possible for you install the most-recent version of BiT (either via your package manager or even the current DEV version from Github here)?

Your reported BiT version is so old (1.1.24) that it code base may have changed so much since then...
If the problem still persists I would look into it...

**Comment by aryoda** [comment]
I'd wait another week for feed-back and then close this issue...

**Comment by aryoda** [comment]
Possibly related to #1025 (same OS and symptoms!)
