### ISSUE TITLE
'make test' fails because local SSH server is running on non-standard port (not 22)

### ISSUE THREAD

**Issue by bolgarov10** [bit-team/backintime#945]
I'm trying to build backintime on my local Linux machine (Manjaro Linux, clone of Arch Linux, if that's important), and the 'make test' fails with following stack trace:

```
Traceback (most recent call last):
  File "/home/alex/build/backintime/backintime/common/test/test_restore.py", line 187, in setUp
    self.cfg.setCurrentHashId(mount.Mount(cfg = self.cfg).mount())
  File "/home/alex/build/backintime/backintime/common/mount.py", line 134, in mount
    return backend.mount(check = check)
  File "/home/alex/build/backintime/backintime/common/mount.py", line 419, in mount
    self.preMountCheck()
  File "/home/alex/build/backintime/backintime/common/sshtools.py", line 183, in preMountCheck
    self.checkPingHost()
  File "/home/alex/build/backintime/backintime/common/sshtools.py", line 512, in checkPingHost
    raise MountException(_('Ping %s failed. Host is down or wrong address.') % self.host)
exceptions.MountException: Ping localhost failed. Host is down or wrong address.
```

I looked at at the code, I think it is failing because on that machine SSH server is running on a non-standard SSH port (not on port 22).

I guess this is not that important, and I just can skip tests and go ahead and run 'make install'. But still, would it be possible to fix that somehow?

**Comment by Germar** [comment]
You're right
Fixed in Master. Thanks for reporting
