### ISSUE TITLE
sip version mismatch, v1.2.0 won't run after upgrade of Ubuntu to 18.10

### ISSUE THREAD

**Issue by glyndon** [bit-team/backintime#953]
Have been using v1.2.0 happily for a year, but after jump to Ubuntu 18.10, the following:

'''
$ backintime-qt_polkit 
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 35, in <module>
    import qttools
  File "/usr/share/backintime/qt/qttools.py", line 21, in <module>
    from PyQt5.QtGui import (QFont, QColor, QKeySequence)
RuntimeError: the sip module implements API v12.0 to v12.4 but the PyQt5.QtGui module requires API v12.5
'''
Seems simple enough: Looks like I just need a newer version of sip, but how to obtain?

I've tried uninstalling/reinstalling sip using pip3, and reinstalling python3 modules using apt-get, but nothing affects this error.

**Comment by glyndon** [comment]
Update: Fixed

```
pip3 uninstall sip
pip3 uninstall PyQt5-sip
pip3 install PyQt5-sip

```
