### ISSUE TITLE
AttributeError: module 'dbus' has no attribute 'exceptions'

### ISSUE THREAD

**Issue by thomich** [bit-team/backintime#963]
Hello bit-team

I face following problem, if backintime is running with python 3.6:

**My System:**

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

uname -a
Linux hercules 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

python3 -V
Python 3.6.3
python3.5 -V
Python 3.5.2

Default python 3: 3.6.3

**Current error:**

AttributeError: module 'dbus' has no attribute 'exceptions'

**Details:**

starting backintime app, will do nothing.
starting backintime in console:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 23, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 31, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 43, in <module>
    import dbus
  File "/usr/lib/python3/dist-packages/dbus/__init__.py", line 81, in <module>
    import dbus.exceptions as exceptions
AttributeError: module 'dbus' has no attribute 'exceptions'

running the py file directly:

python3 /usr/share/backintime/common/backintime.py 

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 23, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 31, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 43, in <module>
    import dbus
  File "/usr/lib/python3/dist-packages/dbus/__init__.py", line 81, in <module>
    import dbus.exceptions as exceptions
AttributeError: module 'dbus' has no attribute 'exceptions'

python3.5 /usr/share/backintime/common/backintime.py 

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 454, in start_app
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 575, in getConfig
    cfg = config.Config(args.config)
  File "/usr/share/backintime/common/config.py", line 272, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1192, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

if running backintime.py with python3.5 i get error cause i run it in cli mode.. i thing..

i read trough other issues and web forums, but nothing helped to solve.

Thanks for hints, fix and your help.

Regards
thomi

**Comment by buhtzz** [comment]
@thomich There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug, External

**Comment by thomich** [comment]
Hello @buhtzz 

Currently i'm on kubuntu 20.04.5 LTS using python3 3.8.10 and backintime 1.2.1 and all works normal.
Will close this bug.

regards
thomi
