### ISSUE TITLE
Running `make test` errors out on filesystem Regex

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#981]
Building from latest git, I got the following failure.  Am I missing a dependency?

```
python3 -m unittest  -b test/test_applicationinstance.py
...................
----------------------------------------------------------------------
Ran 19 tests in 0.035s

OK
python3 -m unittest  -b test/test_argparser.py
.....................
----------------------------------------------------------------------
Ran 21 tests in 3.405s

OK
python3 -m unittest  -b test/test_backintime.py
..
----------------------------------------------------------------------
Ran 2 tests in 2.806s

OK
python3 -m unittest  -b test/test_backup.py
........QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
.QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
...
----------------------------------------------------------------------
Ran 12 tests in 0.719s

OK
python3 -m unittest  -b test/test_configfile.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
......................................................
----------------------------------------------------------------------
Ran 54 tests in 0.007s

OK
python3 -m unittest  -b test/test_config.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.013s

OK
python3 -m unittest  -b test/test_encfstools.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
python3 -m unittest  -b test/test_restore.py
.........ss
----------------------------------------------------------------------
Ran 11 tests in 0.092s

OK (skipped=2)
python3 -m unittest  -b test/test_sid.py
...........................................
----------------------------------------------------------------------
Ran 43 tests in 0.047s

OK
python3 -m unittest  -b test/test_snapshotlog.py
..........
----------------------------------------------------------------------
Ran 10 tests in 0.013s

OK
python3 -m unittest  -b test/test_snapshots.py
.......s.........s.......................s..........s
----------------------------------------------------------------------
Ran 53 tests in 0.235s

OK (skipped=4)
python3 -m unittest  -b test/test_sshtools.py
ssssssssssssssssssssssss...ssssss
----------------------------------------------------------------------
Ran 33 tests in 0.102s

OK (skipped=30)
python3 -m unittest  -b test/test_takeSnapshot.py
.........sssssssss
----------------------------------------------------------------------
Ran 18 tests in 1.703s

OK (skipped=9)
python3 -m unittest  -b test/test_tools.py
.....s..F.Fs.s..s......s................s..s.s...ss.s.s.............
======================================================================
FAIL: test_device (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/backintime-git/src/backintime/common/test/test_tools.py", line 447, in test_device
    r'/dev/.*')
AssertionError: Regex didn't match: '/dev/.*' not found in 'tmpfs'

======================================================================
FAIL: test_filesystem (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/backintime-git/src/backintime/common/test/test_tools.py", line 453, in test_filesystem
    r'(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs)')
AssertionError: Regex didn't match: '(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs)' not found in 'tmpfs'

----------------------------------------------------------------------
Ran 68 tests in 0.078s

FAILED (failures=2, skipped=12)
make: *** [Makefile:577: unittest] Error 1
```

**Comment by Germar** [comment]
Nope, I just didn't expect a `tmpfs` as a valid root filessytem while writing those unittest. But makes perfectly sense in sandboxed test environs
